# Introduction for Volume 4 The Collected Blog Posts {-}

This Volume 4 of Engaging Multiple Personalities is a continuation of what developed from reviewing my patient files upon my retirement from practicing psychiatry. From trying to present, in book form, my understanding of the nature, display and treatment approaches I learned from working with my patients with Dissociative Identity Disorder, it has evolved to a multi-volume series focused on how to work with this particular disorder arising from early childhood abuse. I believe much of the material in these volumes can be used by therapists and society to more broadly understand the more general topic of trauma and dissociation, not just DID. Clearly, dissociation is related to all kinds of extreme trauma, not just early childhood trauma.

After giving a broad presentation on a variety of contextual case histories on the condition in Volume 1, therapeutic guidelines were presented in Volume 2. Volume 3 was written specifically for those with DID who are unable to locate a therapist with experience treating the disorder. This present volume is comprised of written responses to inquiries and comments from readers of the first 3 volumes. Many issues are not covered in standard psychiatric text books and papers nor in general psychiatric literature. At the same time, it must be understood that the material is not based on research, but rather my experience as a clinician only.

In the years after Volume 1 was published in 2014, I received inquires and comments from different parts of the world. The Internet can, at times, provide a wonderful opportunity to connect people with DID who find it difficult to get help and guidance in their own city or even country. Dissociative Identity Disorder is now no longer considered as a “North American Disease.” It is beginning to receive more and more attention because of its prevalence throughout the world, without limitation to culture, ethnicity, economic conditions or religion. Why? Unfortunately, it is because early childhood abuse is similarly without such limitations.

As always, it is the task of the therapist to help people process trauma. To do so, one must be open to the fact that trauma can occur, does occur, and has long term effects. Reality has finally hit home, even in many countries that hitherto have never reported these cases. I fear that with ongoing warfare in so many parts of the world, the vast number children now living through trauma will uncontrollably display dissociative symptoms in the coming decades.

We must open not just our eyes, but our hearts. We must be prepared to listen deeply with empathy and kindness. Let us learn from the pioneers who were forced to understand DID from early childhood. As a society, know that by supporting their healing journeys, we support our own. 

*David Yeung*
