# Introduction for Volume 4 The Collected Blog Posts

After the publication of the first in what turned out to be a series of books on dissociative Identity disorder, Engaging Multiple Personalities Volume 1 Contextual Case Histories, I started writing a blog in response to readers’ comments and questions. Having retired as a psychiatrist whose practice focused on these issues for several decades, this was a way for me to continue to support the greater DID community. 
The posts cover many issues relating to the broad field of early childhood trauma and dissociative disorders. These experiences, unfortunately, are not uncommon experiences. But, they are often overlooked by psychiatrists in their work with patients searching for healing.

The blog topics tend to cover practical issues for patients and therapists, including patients waiting to find therapists, significant others who crave information on how to live with their DID partners, and therapists who find it difficult to identify and treat dissociative disorders when they lack past experience. It is hard to make the first step in working with dissociative clients - until one experiences the power of simply engaging in direct communication with the presenting alters.

My blog posts are available on the Internet for free.  This ebook of the collected posts is also available for free. I am releasing the posts in this way as it allows for interested individuals to have all the posts available in one easily searchable digital book.  It also allows me to update the collection for anyone wishing to update their personal copy.

Many individuals with DID lack the resources to purchase my books. This has always bothered me. While I offered copies of my books to various libraries as a donation, there was no real response. Because the books address many of the same topics, often with a somewhat different focus and level of detail, by publishing this as a free download, it is a way to further support those members of the DID community.

Many of the blog topics are not covered in general journal articles or standard text books. For example, first hand information on disclosure of DID, first hand experience on how to engage a new alter who appears the first time at 3 am in the morning, angry alters, and alters in despair etc. These are common place practical issues that call for genuine empathic and kind responses by the person who happens on site, at the most unexpected hours of the day.

Other issues are discussed in these posts. A glance of the Table of Contents will show readers what to expect from reading these collected posts. None of the material I publish should be taken as therapy. As always, read potentially triggering material in a safe place and in small doses to avoid retraumatization.

The purpose of my books and blog is to demystify DID as well as its treatment as it is a common phenomenon that has been neglected for far too long.

As always, I must thank my former patients who have taught me more about dissociative disorders than the several prestigious institutions where I was trained at the beginning of my career, or any of the continuing medical education programs I attended over the course of my almost 50 years practicing psychiatry. 

*David Yeung*
