# The Foundations of Hope

## The Importance of Hope

*Posted on March 6, 2015*

As a retired psychiatrist reflecting on a life of treating broken bodies, spirits and souls, I have had the extraordinary privilege to learn from my past experience, both successes and failures, and identify the most basic fundamental ingredients essential to helping people heal. 
They boil down to:

1. Establishing a genuine therapeutic alliance, which necessarily involves congruence and empathic understanding on the part of the therapist.

2. Installing (or restoring) faith and hope in the client.

In all the cases of successful suicide by patients that I am aware of, the common threads were the client being overwhelmed by loss of hope, and the failure of the therapist to instill or restore hope in the client. And all too often, when a patient successfully committed suicide, it was clear that they felt that their therapist had lost hope in their recovery too. It is a great sadness that therapists can and do lost hope in just that way.

We must do better as therapists, and it is possible to do so. I believe the key point is to understand that hopelessness, manifesting as depression, suicidal ideation or suicide attempts does not happen in a vacuum. Serotonin alone will not eliminate the risk of suicide if the underlying cause is not addressed. That underlying cause, in cases of abuse, is overwhelming fear. The dyad of hope and fear must be clearly understood.

In cases of Complex PTSD, the trauma is overwhelmingly powerful, leaving the client terrified. Being terrified, without any safe haven from the abuser, leads to hopelessness which must be recognized and addressed. For those suffering from Complex PTSD, the hopelessness is intimately tied to and a product of that fear. For abuse survivors, the fear is often tied to the direct inflicting of pain, physical, sexual, emotional, coupled with the repeated assertion that no one will believe that the survivor has been abused.

The patient hopes the abuse will stop, they fear it will not. They hope that someone will believe them, they fear no one will. They hope that if they act is whatever way the abuser demands, that they will be spared and they are not. Fear is the flip side of hope. 

While the psychiatrist assesses the patient, the patient assesses the psychiatrist. The patient hopes the psychiatrist will understand, and fears that they won’t. When those with complex PTSD have a long history of ineffective and somewhat destructive relationships with the mental health system, they fear – often correctly – that everything they had been programmed to believe about no one believing them is true. In this way, the dichotomy of hope and fear is brought into the therapeutic relationship from the very beginning. 

To combat this and strengthen the therapeutic alliance, the psychiatrist must effectively communicate that the therapeutic journey will undermine that foundation of fear. To avoid scaring the patient, one must encourage them that taking the smallest steps toward healing are the safest – particularly at the start of therapy. Each time any fear is undermined, a glimmer of hope emerges. That is the nature of the relationship of hope and fear to communicate to the patient.

Time and time again in my own practise, I was reminded that little gestures are the crucial building blocks of healing. Healing does not come from grand breakthrough of revelations or enlightenment. It is built on small building blocks even at the level of regaining the control of one comfortable breath.

Offer hope by helping the patient make tiny, achievable goals with each therapeutic encounter. Each session with the patient that enables them to exert some control, even in a very limited way, over the the runaway flashback symptoms is a critical “baby step” in healing.

As related in Chapter 1 of my book “Engaging Multiple Personalities”, I told Joan in our first session that my aim was to help her feel just a little better each session. According to her, this was a most powerful suggestion that propelled her toward healing when she was in the darkest period of her life, having almost given up as a result of the total dis-empowerment of PTSD.

In another case, my last patient of the day calmly told me that she was going to kill herself after seeing me. There was no doubt in my mind that she was simply stating her intention, and that it was not an empty threat or desire for attention. There was literally only one hour to intervene.

I related to the angry part of her, understanding that the source of the anger was the deep hurt of past trauma. I helped her connect to the anger as a source of valuable energy that could be redirected to her healing. I gave her hope that she could turn around the anger, the hate, and see that the best revenge was to overcome the trauma inflicted by the abuser by showing that the abuser had not succeeded in destroying her.

The best revenge is indeed to show the abusers that they failed to destroy the child. Many survivors of childhood abuse carry this sense of hope, of mission, to survive to tell the world that such abuse did happen. To stay alive, to fight for the future so that one could bear witness to such horrendous crimes. We need to change the world so that every child grows up nurtured, loved and protected from abuse. 


## On being a supportive spouse/partner

*Posted on February 16, 2015*

**This is a lightly edited response to a question posed by a spouse about alters coming out far more at night than during the day:**

In Volume 1 of Engaging Multiple Personalities, I discuss one of my patients who was similarly having alters, particularly highly traumatized young alters, come out at night. Her spouse had similar difficulties due to him being unable to go to sleep until the alters expressed what they needed to express – and yes, not going to sleep until 2 or 3 am night after night. For that patient, there seemed to be two reasons for the evening appearances of alters, both equally important: 1) they came out at the time of night when the abuse generally occurred, and 2) the alters were feeling safe enough to come out with the spouse and express what they needed to express as part of their therapeutic journey.

The spouse came up with some quite innovative approaches to helping the alters, giving them space and comfort as well as the recognition that they were with the spouse in a time and place where the abuser never was. These are also discussed in Volume 1. Check in with the therapist working with your spouse on any approach you wish to take. Certainly, the therapist should know about the alters coming out each night and what is happening. I do not encourage spouses to be therapists, but when alters come out, you do need to be kind, empathic and know what to do.

**Please take care of your own health while doing this.** To provide the support your spouse needs, you MUST maintain your health, your balance and your empathy. Volume 2 includes a section on self care for therapists, and the warnings I give there might be applicable to spouses that are meeting with traumatized alters at home late at night.

Know your own limits, and know when they are being reached. You cannot expect that traumatized alters will see the strain on your health, and they often do not have the capacity to stop once the flashbacks start. Set time limits with the alters so that you can help them the next evening as well, for example, rather than burning yourself out. You might  try some of the grounding exercises with them that I have written about in my books as well as on my blog, but again, check with the therapist.


## The Power of Dissociation

*Posted on November 17, 2015*

Without in any way trivializing the trauma that is the core of early childhood abuse, there is a fascinating aspect of MPD that is deserving of further exploration. The fact is that dissociation allowed the abused child to survive. That, in itself, is cause for appreciation of the power of the dissociative response. It is the habituation to dissociation as a response to triggers and unprocessed trauma arising that causes such tremendous difficulties for the patient including amnestic barriers and internal conflict. For some, dissociation can produce unexpected hosts of achievements as part and parcel of the impact of the disorder. In therapy, there is often an over-emphasis on the damage that has been done without a concurrent expression of how genuine healing is possible – that there is hope. 

Among those with DID that I have treated as well as those I have encountered after my retirement, some have accomplished extraordinary things both in recovery and in the world. While I discussed this aspect briefly in Engaging Multiple Personalities Volume 2, I believe it is worthwhile to go deeper into this aspect of DID. 

It is clear to me that I failed to diagnose certain patients as DID in a timely fashion because of their external accomplishments. I was misdirected by my own admiration for them. I will not identify those patients for obvious privacy reasons but they included people in the top tier of their various professions, in both business and academia.

The first point to make is that for anyone to survive the intensity of trauma that gives rise to DID, they must of necessity be extraordinarily brave, strong and resilient. Anyone coping with and surviving ongoing abuse as a child crafts strategies on a survival level that successfully deal with vicious adult abusers. Some abusers are hiding in plain sight as valued members of the family and/or community. Some abusers are individuals that frighten law enforcement, other adult family members and other adults in the community. Consider the pressure a child is under dealing with abusers which the outside world either cheers as a valued individual or fears as a dangerous individual. For the child, there is no hope of escape, nowhere to run, no refuge. 

Dissociation is a most brilliant survival strategy for such a small child. Fundamentally, that is the point I have tried to make in both volumes of Engaging Multiple Personalities as well as on my blog. To both therapists and those with DID, I say please do not turn away from the alters. However angry, mean, sad, or panicked they may be, it is the alters that were the means of surviving the abuse. The difficulties that DID individuals have is dealing with the aftereffects of habituating the use of such a radical means; the only means available to them as children.

Alters arise holding pieces of trauma as well as their own habitual modes of interacting with the world. The ability to dissociate provides a tremendous opportunity for an alter to completely focus when they are in control of the body. The single mindedness allowed survival as a child by focusing away from the trauma as it happened. As an adult, the dissociation via triggers can be an ongoing trap of retraumatization. Alternatively, it can be used to successfully accomplish things in the outside world. On a very basic level, dissociation allows DID individuals to go to work, take care of themselves and others such as their children, while holding the unprocessed trauma temporarily at bay until the system is overwhelmed. 

There are those with MPD who may excel in multiple disciplines. For these individuals, each dissociative part, each alter, can develop their focused interest in a topic without distraction. Any scientist, scholar or artist, has this ability of total concentration when working to the exclusion of other distractions. With the ability to dissociate somewhat completely at will, the result of such total concentration can be excelling in a field. If one part is an academic, another an artist, and still another an athlete, how interesting that might be.

Individuals who have publicly disclosed their DID have often been ignored or had their DID denied. However, there are a few individuals whose standing in their respective communities allowed them to disclose their DID without quite the same level of disparagement as others have experienced or rightly may fear. This is not to say that such individuals experienced no negativity following their disclosure. However, because of their stature, they gave pause to the deniers of DID. Indeed, they created the opportunity for non-DID individuals to begin to see DID in a less perjorative light. 

Robert Oxnam is an academic who revealed his MPD in his autobiographic A Fractured Mind (2004). Robert is a scholar of Asian studies, having taught in US universities as well as having lectured in Beijing University – in Chinese. His most famous role was to lead a cultural tour of China for the likes of Bill Gate, Warren Buffet and president HW Bush. He also was a China expert advising the former US presidents. He has authored several books and served as the head of the Asia Society in New York. However, apart from the focus on Asia, he plays the cello, and is now a prominent sculptural artist. Beyond that, at different stages of his life, he was a competitive archer, an accomplished cyclist and a prominent, in some circles, rollerblader. 

Another MPD autobiographer is Herschel Walker (author of Breaking Free [2008]). He was his high school valedictorian and a Heisman trophy winning athlete. He was an NFL player, and then excelled as a world class bobsledder, sprinter and mixed martial artist. He is a successful businessman in the food industry. In his autobiography, he mentions that his ability to dissociate allowed him to be apparently untouched by pain in the midst of crushing blows from opponents – to their utter consternation. 

Going back to the earliest days of psychiatry, Anna O. is believed to be the first MPD patient whose case history was described in detail. Her case is found in Freud’s book—- Studies on Hysteria (1895). Freud missed the diagnosis, or, to be more accurate, there was not an applicable diagnostic category at the time other then the general one of hysteria. Even in missing the diagnosis, he did note her concern about “time-loss” and having “two selves.” Both of these are primary and often the first indicators of a potential DID diagnosis. At different times, Anna O would speak different languages and refuse to believe, for example, that she actually knew others. There are several other points that would lead one to consider a DID diagnosis that are clearly laid out in the case history. 

Anna O (real name Bertha Pappenheim) was at one time a patient of Breuer (a colleague of Freud and co-author of Studies on Hysteria). He stopped treating her as she was becoming progressively worse and had to be institutionalized for a period of time. Breuer told Freud that she was deranged; he hoped she would die to end her suffering. One can imagine the depth of her depression through Breuer’s comment. However, she later achieved renown for her social work, such that the West German government issued a postage stamp in honour of her contributions to that field. She was an author of several novellas, poems and plays. In addition, she was a translator and a writer of several important pieces attacking the trafficking of women in eastern Europe and the Orient. Her focus on helping others who were sexually traumatized is not uncommon in the DID world. In my own practice, I saw clear examples of this practical application of empathy by DID patients in dealing with children and other at-risk individuals.

Unfortunately, the term MPD has trivialized the concept of dissociation into parts, offering endless possibilities of theatrical materials for movies and TV series. They tend to emphasize the histrionic parts of the multiple facets of a single patient. This trivializes the pain of the original trauma that caused the dissociation as a defense to protect the fragile ego. It somewhat makes light of the damage done to the growing individual and the possible ill effects impacting the next generations as well as the untold misery affecting many people involved. 

Psychiatry struggles to find a better name of the affliction, changing it from MPD to DID in 1989. I wonder if this change has made any difference. Die-hard disbelievers still cling to the pseudo logical argument that if a person can have more than one identity, then two persons hold the same passport or one person can have multiple passports – completely missing the point of the disorder. The book by Schrieber reawakened interest on this issue but some professionals got distracted by a fascination with the multiplicities of the “personalities”.

Because of the word personality or identity in the diagnostic label, many psychiatrists cannot make the paradigm shift to accept the concept of DID, nor accept DID as a genuine psychiatric disorder. Some serious academics still deny DID as a mental disorder, declaring it to be a condition that is produced iatrogenically, or otherwise non-existent. This mistaken view is much to the detriment of the welfare of DID sufferers trying to find a therapist. Even worse, it teaches new psychiatrists something that is simply wrong. Out of their ignorance, they will then perpetuate the same mistaken view and impact an even wider circle of patients. 

By studying the successes that individuals with DID have had in healing, in worldly activities and in displaying great empathy helping others, psychiatrists and other therapists can learn quite a bit about trauma, its treatment and the possibility of truly leading those with the disorder into health. The successes can be used to give hope, the critical element in working with those trapped in retraumatization cycles, that healing is possible, that joy is possible and that their very survival as a child is a mark of how creative, strong and successful they were as a child all the way through to this present moment.


## Spirituality and the Healing of Traumatic Wounds

*Posted on January 14, 2016*

I have thought about this topic a great deal but have hesitated to write much about it. Communicating about spirituality in the treatment of early childhood trauma is difficult because, for many, religion as well as pseudo-religious imagery played an integral part in the trauma. On the other hand, spirituality has also, for many, been a key foundation upon which healing has arisen.

In my experience, spirituality, whether with or without formal doctrinal religious faith, played a powerful role for many of my patients in their becoming successful survivors. I have seen patients rise up from the depths of despair despite horrendous and prolonged backgrounds of traumatic experience. For those, spirituality gave them the hope and strength necessary to overcome the tremendous difficulties that resulted from their history of early childhood abuse. 

Again in my experience, formal religion and religious doctrine can be a source of hope for patients as well as the source of their trauma. Therefore, as a therapist, one must be able to help a patient connect with the spiritual aspect of their life in a way that avoids the risk of re-traumatization. This means that one must be flexible enough to support the patient’s religious faith when it differs from one’s own as well as be able to invite a patient’s spirituality in the complete absence of or antipathy toward religious doctrine if that is the path of safety for them. 

A therapist friend of mine, a Buddhist, once sat with one of his patients in a church. The patient knew the therapist was a Buddhist and was surprised at the suggestion. But the patient had already made it clear to the therapist that religion was important to him and that he felt safe sitting in a pew in a church. My friend pointed out that if the goal was to make the patient feel safe as a way to set the ground for genuine therapeutic communication, why not do it in the place the patient felt most safe. To have taken him to a meditation center and asked him to sit on a cushion with legs crossed would have made him feel quite uncomfortable, if not completely unsafe. This is an example of the benefit to patients of therapists not being too stuck in their own personal religious view.

We tend to think of ourselves as amalgamations of mind, body and spirit. We have a general idea of the meaning of mind and body, but sometimes we don’t pay much attention to what we mean by spirit. Often, we simply assert spirit to be something that is mystical, with no presence or relevance in the everyday aspects of life. My understanding of spirituality is that it refers to that which is both of and beyond the material world. It is more than a weekly visit to a church, synagogue, mosque or meditation center. However, spirituality does not need to be tied up with religious dogmas, rituals, heavens or hells. 

I define spirituality as the framework of how we face our existence, how we face our selves. It is a fundamental understanding of how we might be kind to ourselves in both body and mind. It suffuses our awareness, leading us to be more in touch with our inner core. 

Trauma is a fact of life in the natural world – as when a tiger chases down a deer. Both therapists and patients have to accept this as part of the human condition as well, and each of us needs to find our own way to handle it. We need spiritual strength in our own life journey but we also need to cultivate, protect and enhance our spiritual strength when we try to guide someone on their healing path. 

In 1968, Joseph Campbell said, “In India, two amazing figures are used to characterize the two principal types of religious attitudes. One is ‘the way of the kitten; the other, ‘the way of the monkey.’ When a kitten cries ‘Miaow,’ it’s mother coming, takes it by the scruff and carries it to safety; but as anyone who has ever traveled in India will have observed, when a band of monkeys come scampering down from a tree and across the road , the babies riding on their mothers’ backs are hanging on by themselves.

Accordingly, with reference to the two attitudes: the first is that of the person who prays, ‘O Lord, O Lord, come save me’ and of the second of one who, without such prayers or cries, goes to work on himself.” In China and in Japan, the two attitudes are termed, “outside strength” and “one’s own strength.” No matter which religion one pursues, or for that matter, or spirituality in the absence of a religious tradition, these approaches need not be contradictory. I respectfully request the indulgence of those literal dogmatists in any particular religious affiliations to accept that it is an individual matter to choose either of these approaches or a mix of the two, no matter if you are a Buddhist, Muslim, Christian, Jew or none of the foregoing.

You have to find a reason to fight to overcome the tremendous obstacles of an abusive childhood. One good example of a reason to overcome the obstacles of abuse is to defy the abuser’s threats, to make yourself whole despite and against all odds, surviving the trauma and betrayal. If you subscribe to a personal deity, prayers asking for specific help and guidance can give you strength to overcome those obstacles. Like escaping from a deep well, you may need the sense of an external power to throw a rope for you to grasp and pull you out. On the other hand, if you do not engage a religious tradition, simply touching the power of the earth or feeling the warmth of the sunlight, those fundamental connections of life that are beyond you, may be enough to chase away the dark clouds and overcome past trauma. 

In short, you need to have hope. Many of my atheist/agnostic patients relied on AA, NA or church fellowship for support in their difficult journey of healing, there is no need to fight alone. 

Accessing genuine spirituality requires intention, practice and experience – rather than just wishful thinking. Spiritual practice within a formal religions tradition is usually quite clear within that tradition. One can see spiritual practice outside of religious strictures as keeping still and paying attention to the now, the present moment of existence. 

Be still. Within that, learn to be kind to your own mind. Start doing one-breath meditation. The gradually advance to more than one breath, then to 5, 10 or even 20 minutes. Move toward being non-judgmental. Slowly learn to love yourself, without evaluating that thought as being good or bad.  Do not worry about closing your eyes, you may let them open if you so choose. Breathe each breath slowly, be alert and be stable in your sitting position.

You might try something like this: 

Breathe in God and breathe out darkness
*or*
Breathe in love and breathe out fear.

The need for a spiritual component to one’s life applies equally to therapists who, day in and day out, listen with deep empathy. Listening in that way to the horrendous tales of their patients’ extreme past and often present sufferings, therapists are in need of strength to purge such toxic material that is capable of inflicting vicarious trauma on them. I have suggested extracurricular activities such as physical workouts as well as creative hobbies of music, sculpture, pottery etc. These remind you that there is something wholesome, beautiful and noble in this world, that it is not simply filled up with ugliness, betrayal and negativity. 

In their uncertainty, people tend to grasp hold of dogmas to anchor their sense of security. They tend to gravitate to an extreme end of some belief, unable to see compromise as healthy in their dogmatic system. But, kindness transcends dogma. It is the secret and quite magical ingredient for healing. Always be kind. 


## Co-consciousness

*Posted on March 20, 2016*

Among DID individuals, the sharing of conscious awareness between alters exists in varying degrees. I have seen cases where there has appeared to be no amnestic barriers between individual alters, where the host and alters appeared to be fully cognizant of each other. On the other hand, I have seen cases where the host was absolutely unaware of any alters despite clear evidence of their presence. In those cases, while the host was not aware of the alters, there were alters with an awareness of the host as well as having some limited awareness of at least a few other alters. So, according to my experience, there is a spectrum of shared consciousness in DID patients. From a therapeutic point of view, while treatment of patients without amnestic barriers differs in some ways from treatment of those with such barriers, the fundamental goal of therapy is the same: to support the healing of the early childhood trauma that gave rise to the dissociation and its attendant alters.

Good DID therapy involves promoting co-consciousness. With co-consciousness, it is possible to begin teaching the patient’s system the value of cooperation among the alters. Enjoin them to emulate the spirit of a champion football team, with each member utilizing their full potential and working together to achieve a common goal.

Returning to the patients that seemed to lack amnestic barriers, it is important to understand that such co-consciousness did not mean that the host and alters were well-coordinated or living in harmony. If they were all in harmony, there would be no “disease.” There would be little likelihood of a need or even desire for psychiatric intervention. It is when there is conflict between the host and/or among alters that treatment is needed.

Conflict in DID patients is usually quite evident. A system full of clashes is usually playing out a power struggle internally that is manifesting externally. In some cases, dictatorial alters may have an ironclad control over the information flow and behavior of the system as a whole. In addition, because of their strong individualistic feelings, some alters may appear to behave in a callous or selfish way with no regard for the needs of the host and the other alters. This can result in one alter hijacking control of the body for a time, short or extended, for the pleasure/intentions/wishes of that one alter alone. The result is usually the host’s experience of time-loss, one of the key markers for DID and one of the primary causes for seeking therapy.

Such a hijacking alter may think, “I don’t care that others in the system are tired and may need to sleep. It is my time, and I want to go out. I want to have a good time at the bar.” For example, I had a patient with one alter who regularly took off to have fun cruising around with motorcycle gangs. She totally disregarded the safety of the system, the boundaries of her support network, and the host’s appointments to see me. I would note that this kind of conflict can occur even in the context of a patient with some level of co-consciousness.

It is not uncommon for a patient’s host or front to vehemently deny the presence of alters despite clear evidence in diaries, letters, and even recorded messages of alters talking. This is the opposite of co-consciousness – at least with respect to the host. It must be terrifying, not merely disconcerting, for an individual to realize that an alter, another inside part of that same individual, can so completely take over the executive functions of the system to the point that they establish a functioning separate life in the outside world. In fact, I have had patients whose alters would, on occasion, establish a completely separate existence for a few months at a time using that alter’s name. In one case, the alter established her own residence in a different apartment, connected with a different social milieu, and, in that case, earned money as a sex trade worker.

I know hosts who have staunchly fought against such recognition of alters and even the idea of co-consciousness. One cannot blame them. The fear is so intense that I sometimes had patients leave therapy rather than work with the recognition. As a result of those experiences, I learned to sometimes withhold revealing or confirming a DID diagnosis so as to avoid scaring the patient into abruptly terminating therapy. In my judgment, it was occasionally justified to delay confirmation of the diagnosis at least until the foundation of a genuine therapeutic alliance was established.

With respect to cases where the alters are completely hidden from one another, one must tread gently. When the presence of alters is pointed out, some DID individuals may take a long time to be convinced that there are indeed other alters coexisting in that same physical body. As a therapist, do not push the point about alters or co-consciousness as a path to healing. It is not a debate to win or lose. Again, if there weren’t problems, then the patient wouldn’t be in therapy.

The question for the therapist is how to gently promote co-consciousness. First, one must prepare the patient to hear the news that there are alters inside. You must wait until you have confidence that the message is not going to create uncontrollable panic in the host. Establishing a therapeutic alliance with the host is absolutely critical to this. As the therapist, you may or may not have met some or all of the alters directly. Establishing a therapeutic alliance with alters that you have met, or with whom you can otherwise communicate, can strengthen the host’s ability to hear the news.

Remember that the amnestic barriers arose for very good reasons. Breaking them down without permission invites further trauma. So, make sure the news is given in a way that makes clear that as a therapist you can help bridge the amnestic barriers when the different parts are ready. One helpful analogy for promoting co-consciousness might be to note that you, the therapist, might be frightened to walk down a dark street alone but would feel much safer walking that same street if you had a friend (or two or three) with you. Even if that friend was also scared, the companionship would be helpful to both you and your friend. Please use the analogy with respect to your own fears about walking down dark streets, not theirs. They will understand the point.

This analogy was quite helpful to some of my patients that had very young alters with similar but not identical trauma memories. The point was not to encourage or even suggest integration. Instead it was to allow each of those alters to know that they were not alone, that there were others inside that could truly understand. That can be the beginning of a friendship within the community of alters. Once that first companionship among alters arises, it can be referenced when talking to other alters that are stil blocked by amnestic barriers.

In this way, you can encourage the direct experience of feeling safer through the experience of co-consciousness. It is a step-by-step process. The patient may feel like they are treading on thin ice in terms of their fear and panic. The simple answer is to encourage them to go very slowly, just as you would when walking on thin ice. When you walk on thin ice, you do not know for certain if it is strong enough to hold you. You go inch by inch, testing and seeing what happens. It is the same here.

A not uncommon experience of one alter starting to consider the possibility of companionship with another alter (though not yet safety) is when they become aware that their traumas had strong similarities to the traumas of another alter or perhaps several alters. This is akin to the analogy of walking a dark street together rather than alone. In addition, when there is the experience of a frightened alter witnessing the emergence of a protective alter in the outside world, both alters can begin to appreciate their respective roles in the system. In this case, it might be the frightened alter identifying a danger and the protective alter reacting to that identification and fulfilling its function. This is again a prelude to developing a sense of safety and can occur more easily when the alters begin to become aware of each other. When this takes place without re-traumatization, this is the beginning of seeing the possibility of healthy teamwork that is a mark of healing.


## Christianity and Forgiveness – Part 1

*Posted on February 8, 2016*

This post is a follow up to the short post entitled [“The Trap of Forgiveness”](https://www.engagingmultiples.com/trap-forgiveness/). It was written following feedback and questions from some readers that are very focused on the Christian notion of forgiveness as part of their healing. It is directed primarily to Christian patients and therapists whose therapeutic work is based on forgiveness as one of the central teachings of Jesus.

Some patients and therapists with deep roots in Christianity see forgiveness as the confirmation of healing. It is sometimes their view that being able to forgive is the ultimate expression of being healed. It is my experience that one needs to be extremely wary of how forgiveness is defined in the context of treating survivors of early childhood abuse.

For example, it is not uncommon for a typical female patient who has survived early childhood abuse by her father to face a spiritual crisis when that father, late in life and perhaps with failing health, asserts his dependency on her as a command. Now insisting on a “normal” father-daughter relationship, he may be conveniently ignoring, making light of, or rationalizing his abusive behavior. The patient may then struggle with this: Should she abandon her abusive father or perform her duty as a Christian daughter forgiving him his past sins?

I cannot emphasize enough the importance of defining forgiveness. Depending on the definition you choose, it is either a path to further healing or a path to further retraumatization. In the absence of clearly defining forgiveness, it is a dangerous goal to set for a DID patient. 

Therapy must be practical. It must take into account the trauma that patients must process in order to heal. One must consider the likelihood of success, as the goals in therapy must be within the grasp of the patient. Positing conventional notions of forgiveness as the path, goal or indication of success in therapy seems to set both the therapist and the patient up for failure. Setting an unattainable goal will only reinforce the patient’s negative self-image engendered by the abuse. 

We must be clear that forgiving a living abuser is not like forgiving someone who stole an extra cookie when your back was turned, nor is it like forgiving someone when they are no longer able to harm you – such as someone who has already died. Promoting or attempting forgiveness can be very dangerous if it involves an abuser who has brutally harmed the patient in the past and is still capable of inflicting further deep wounds and retraumatization through physical or psychological means.

A colleague of mine listened to a woman speak of her sexually abusive father, explaining that he really loved her and the abuse was simply his confusion about how to express it. This seemed to be her conventional version of having forgiven her abusive father for his conduct – having an explanation she thought she could live with. My colleague told her in no uncertain terms that her father did not love her, that calling his molestation “love” was a psychological tactic common used by many abusers – particularly paternal or older male abusers, and that until she understood that power dynamic she would not be free of the abuse, not healed. She reacted as if he had thrown a bucket of ice water on her; causing her to reconsider the import of what she herself had said. 

It later came out that her father had continued to abuse other children – including her toddler aged daughter. When this was discovered, she and her family moved within a week to another country to escape him. Had she not “forgiven” her father in that conventional sense, she would likely have been more on guard against him and thereby protected her own daughter as well as others. I use this real example to demonstrate that conventional notions of forgiveness can hold ongoing danger to the patient and others.

Most trauma that leads to DID is so overwhelming that ordinary individuals cannot truly imagine or comprehend the experience. To presume that one will eventually be able to forgive their abuser and, as a result, have an ongoing positive or at least neutral relationship, as a general rule, is a fantasy. From the Christian theological view, Jesus was able to forgive all their trespasses and sins. From that point of view, one can take joy in Jesus’ power to forgive and leave that level of forgiving to Him. However, this is not something within the capacity of ordinary people whether they are DID or not, so do not push that as a therapeutic path or goal. 

If you are bitten by a poisonous snake, you can forgive that snake its poisonous venom and understand that it was simply defending itself when you accidentally stepped on it in the jungle. Having venom is in the nature of being a poisonous snake. To forgive the abuser and engage him as if there was no current danger, would be like forgiving that poisonous snake and deciding to carry it back home with you in your pocket to prove your forgiveness. Don’t do that! 
One must work with forgiveness in a way that is not predicated on continuing to put oneself or others in danger of further abuse. The risk of retraumatization is too great to permit a patient to confuse conventional forgiveness so as to blur the boundaries of their personal safety. 

It must also be understood that the critical sense of safety a patient is developing in therapy is the key. Forgiveness, from a therapeutic point of view, must be understood to be an internal process that does not require endangering proof of accomplishment. There are many important reasons to protect the patient from the danger of retraumatization. There is absolutely no need to test the depth of one’s forgiveness by engaging an abuser as an expression of forgiveness to him. Patients can be encouraged to simply check their own hearts. Neither from a spiritual nor psychological point of view does forgiving an abuser in your heart mean that one presents the abuser with another opportunity to harm you.

I set out some realistic therapeutic goals for this kind of case in Engaging Multiple Personalities Volume 1 and 2 as well as some practical exercises for establishing safe boundaries in those volumes and in my blog posts. Hopefully, they will prove helpful to readers.

I have yet to define forgiveness in this piece, in part because there are many aspects and understandings of this in Christianity. However, before any notions of forgiveness can arise, it is important in DID therapy to understand and make sure the patient understands that it was often the angry and protective alters that enabled the patient to survive the abuse. So, while I consider that it is a healthy aspiration to forgive others, meaning letting go of bitterness and hatred that is rooted in the past, in therapy one must be very careful to allow that to come to its own fruition. Introducing or promoting forgiveness is denying the insight and role of the angry alters. It will be counterproductive to the therapeutic alliance and the overall healing path. 

In my view, being unwilling to forgive means holding on a hateful feelings and bitterness which results in further suffering and prevents healing. My definition of forgiveness does not mean that you go have coffee with your abuser and chat about current events in the world. My definition of forgiveness means letting go of the hatred in your heart. That should happen as a by-product of therapy, maturing in its own time as the system’s sense of safety permits. Forgiveness like that, with the warmth and lightness in the heart that results, is an indicator of the final stages of therapeutic success. 


## Christianity and Forgiveness – Part 2

*Posted on February 29, 2016*

Forgiveness, Christian or otherwise, does not mean condoning or giving excuses to wrongdoing. Sanity may be defined as the ability to tell right from wrong. So here it is: Sexual abuse is wrong. Traumatizing young children is wrong. There is no way to twist logic that makes such abhorrent conduct acceptable. But it is important to remember that the prerequisite to genuine forgiveness is that the victim no longer feels the pain, that the past ceases to intrude into the present. 

There are two aspects to an abuser’s wrongdoing: his intention and his action. In other words, he might perform despicable acts based on self-serving so-called “reasoning.” Many child molesters proceed with rationales they know to be false such as, “It is really quite harmless. She is only 2 years old. She will not remember this when she grows up. After all, I don’t remember what happened to me when I was 2 years old.” 

It is likely that with the addition of alcohol and/or rage, the abuser may think that he was justified in his conduct or have forgotten it because it was not a particularly significant event to him. If the victim believes that the original infliction of the trauma is unintentional, they may believe that it will be easier to forgive. In fact, abusers may play on that but it reeks of shifting the blame to the patient along the lines of “It never would have happened if you weren’t such a bad child” or “I was drunk so I am not really responsible.” With respect to the latter, I have colleagues that have studied the Bible and wonder how Lot’s daughter’s might feel about being blamed for their father’s incestuous conduct. 

One cannot advise a patient to forgive beyond their own heart if there is even the remotest possibility that the abuser might get a feeling of pathological pleasure, knowing that what he once did decades ago continues having a powerful effect on his victim. The therapist’s task is to lead the patient to understanding that holding on to the bitterness about this past experience continues the entrapment by the abuser. The patient’s task in therapy is to work through this, to process this part of their past experience so as to be liberated from the retraumatization power of the past. 

If you are holding something tightly in your hand, it will fall as soon as you loosen your grip. It is the same with processing trauma. Letting go of a painful memory’s strength is possible after you genuinely feel you have shared the experience with a significant person, like your therapist, and that you have finished the task of bearing witness to the crime – the series of childhood traumas. This process of successful therapy is often accomplished by deep listening and empathetic sharing of the pain on the part of the therapist. 

Know that forgiveness does not mean forgetting. You need to remember it as part of your experience in life. You need to maintain a certain vigilance, not hyper-vigilance but still vigilant awareness, to make sure you are not preyed upon in the future. If and after you forgive, you have a choice as to whether or not to include the past abuser in your life.

By forgiving, you are accepting the reality of what happened and are able to free yourself from the past’s interference with your current life. This is a gradual process—and it doesn’t necessarily have to include the abuser. Forgiveness isn’t something you do for the person who wronged you; it’s something you do for yourself.

As I and others have said many times, the trauma that leads to DID is so overwhelming that ordinary individuals cannot truly imagine the experience. To presume that one will eventually be able to forgive their abuser in any conventional understanding of forgiveness is, in my opinion and for practical purposes, a fantasy. The aim of treatment should focus on the task at hand, teaching the patient to experience and hold on to the safety of the present. It is to teach the patient that skill so that they can experience the safety of the present when memories of the past arise. When memories are just memories, and are no longer the involuntary reliving of pain, that is what it means by healing.

Here are some therapeutic goals I consider to be realistic for patients. They are practical applications of forgiveness in one’s own heart.

1. On the social side, measures that limit and circumscribe interactions with the abuser must be monitored. For example, patients may not be able to say “no” in daily life if they are still in contact with the abuser. Therapeutically, the first step is to establish a firm base of a pain-free and safe present. The patient needs to learn the real meaning of the present, which is the immediate experience of breathing this very breath. Forgiveness in this context is being non-judgmental towards oneself. There are usually alters that are in conflict and angry with others who participate in any way, shape, or form with an abuser. Introducing each conflicted alter to the possibility of forgiving alters with a different point of view is a very positive start. It is not telling them to go along with that other alter’s view. Rather, it is explaining how that other alter feels. In essence, it is teaching the foundation of empathy. This is not easy, nor is it something that happens quickly. In my experience, it is best introduced talking about how the alter might wish to comfort a confused child – not by yelling but by holding them with warmth. Then, within that warmth, clarifying the present danger rather than re-working the past.

2. In order to forgive oneself, a therapist introduces exercises that teach the patient how to find a physical/psychological safe place in the present. Patients are taught how to put put themselves in a physically relaxed and psychologically comfortable state. The immediate goal is for the patient to make sure that he/she is in a safe distance from the abuser. Within that experience of safety, one can develop the understanding that abusers are both dangerous and usually survivors of abuse themselves. In other words, through the physical and psychological experience of safety in the present, one can remain vigilantly awake, without being hyper-vigilant, and see that abusers are likely acting out the impact of their own history of having been abused. This is training on extending forgiveness without permitting further abuse.

3. Teach the patient to go back and process the past trauma in a titrated/controlled manner. In that way, the patient can eventually experience the arising of that memory without their present consciousness being flooded with sympathetic fight-flight-freeze reactions. Various techniques [such as “the 5% rule”](https://www.engagingmultiples.com/the-5-rule/) have already been explained elsewhere.

4. Eventually the patient will develop the ability to separate the emotions associated with past trauma from the present recall of that past in a manner which avoids retraumatization. A commonly observed sign of progress is the patient’s increasing ability to spontaneously bring back some detail of the past trauma with less panic and more ease. She will speak in a calm voice, without being entrapped in fear or horror. This is usually accompanied with a sense of sadness – which is completely appropriate. That sadness is another gateway to developing further forgiveness towards oneself and the alters in conflict about the abuser. 

5. Sometimes there is a wish to understand why the abuse happened. There is the hope that if one can understand the why, then forgiveness will follow because there is a context for the abuse. As a therapist, one must be very clear that there is no acceptable context that permits abuse. One can understand what drives an abuser may have, but that does not grant the abuser permission to abuse. Sometimes there is a ready understanding of abuse – such as a clear trans-generational abuse pattern. It is important that such a connection is discovered spontaneously by the patient. This is not something to be brought up by the therapist. The patient may show the beginning of understanding by replacing fear or anger with sadness. This means that the patient is developing empathy that is being extended to the abuser. Whether or not genuine forgiveness flows out of this should be left to the natural course of events for that patient. I think it is risking an inappropriate imposition of one’s own religious ideas on the patient to bring up forgiveness to the patient as applied to the abuser. It is positive to encourage internally generating forgiveness by the patient for the patient. But, forgiveness is a heavily loaded term in Christian dogma. One must be extremely careful so that the burden of that loaded term is not imposed, intentionally or unintentionally, on the patient. 

6. There may come practical real life situations that are difficult, such as whether the patient is obliged to visit, support, help, or nurse the abusive parent who may or may not be incapacitated but desires the patient’s help in one form or another. My view is that a biological parent, having abused the patient, forfeits their parental status. He has disqualified himself as a parent just as a a physician can be struck off the registry because of misconduct involving a patient. The patient has no obligation towards the abuser as a parent, just as a physician is no longer a physician when his conduct has been found to be unbecoming of that position. 

If the patient insists on offering forgiveness, complete or otherwise, then the prerequisite should be that he/she is healed and recovered from the ill-effects of that abusive experience, to the point that they are truly no longer subject to retraumatization. The way he/she speaks of the past abusive experience will make it quite clear whether or not full recovery has been effected. While engaging the abuser as part of one’s expression of forgiveness may be seen as a laudable goal from a religious point of view, for an abused individual it is unrealistic. It is not the appropriate goal for DID therapy.


## Instilling Hope

*Posted on September 16, 2016*

A decade after retirement, I remain preoccupied with some basic issues pertaining to psychotherapy. I believe it is important to express some of the misgivings I have about the general training and preparation of therapists, based on the experience I gained over 40 years as a psychiatrist.

After one graduates with a basic medical degree, the training to become a psychiatrist lasts for several more years. There are usually pre-medical school studies of basic science or humanities that one takes before embarking on subjects such as anatomy, biochemistry, physiology and psychology. But, somehow, the positive factors relating to healing and restoring individuals to wholeness are not discussed. They may be implied but they are not specifically engaged. Factors that directly influence the work of a therapist are usually not mentioned, the two key ones being hope and compassion. Perhaps they are regarded as self-evident and therefore not in need of exploration but, by failing to focus on them, therapists are not guided to consider their importance or trained in how to put them into action.

The fundamental message of compassion exists in every religious tradition I have encountered. It is an essential practice for many Saints in the Christian tradition; it is one of the principal teachings of the Buddha; and it is the most used word in the Koran. Clearly, the importance of hope and compassion transcends sectarian differences. In the absence of religious traditions, most individuals express their common humanity through kindness and compassion.

It is kindness, the active component of compassion, the instills hope. Hope offers a path back to a sense of possibility in our lives when all, or almost all, seems lost. It’s about relief and restoration. There is a Chinese proverb that says, “Beyond the dark willows and bright flowers, there is another village.” A western proverb says, “A dark cloud has a silver-lining.” These can give sustenance to us going forward, strength to continue putting one foot in front of the other. They communicate the opposite of despair, the opposite of a “dead-end street.”

As a therapist, it is worth considering a few questions concerning hope: how important it is to instill or invoke hope it in your client; how does one engender and nourish hope; what might undermine hope in a patient; what does it feel like for you, as a therapist, to hope; and, crucially, what does it feel like when you, as a human being, lose hope – even briefly. While everyone’s answers are different, asking the questions are critical for one’s own understanding of the role hope plays in your work and life, as well as specifically they might apply to individual patients.

We all should, or are presumed to learn, these positive attributes of hope and compassion though the love and nurturing we receive from our primary caregivers. Generally speaking, they are learned from our parents, or perhaps our teachers in kindergarten and/or Sunday Schools. But, this is less and less the case in modern life. For patients, those positive attributes may not be accessible following trauma – particularly repeated early childhood trauma caused by primary caregivers.

All of therapy is built on a foundation of hope. Hope that things can change: habits, behaviours, emotions, outlooks, relationships and even people themselves. 

For those who do not find inspiration from religious texts whether it be the Bible, the Bhagavad Gita, the Koran, the Buddhist sutras or others, let me point out that hope is associated with life itself. The organism knows best. Just as plants grow towards the light, the human organism intuitively knows a healing path back to well-being. A good therapist can point out the light to a patient, but part of therapy is getting to what is blocking this intuitive understanding. Perhaps it is our chaotic day-to-day struggles, perhaps it is confusion that is the result of early traumatic experiences. 

To properly provide a therapeutic container, a place where the light can shine on a patient, the therapist must be clear about their own internal obstructions. Therapists are prone to depression and negative mind-sets, just as their patients may be. Many therapists, unconsciously, are drawn to the profession as a way to work out their own psychological issues. Some may simply become overwhelmed by the intensity of their patients’ suffering. Others may survive by becoming inured to it.

A depressed therapist tends to be bogged down by the client’s problems perhaps because they are wearing glasses with that same tint. A therapist may also become depressed as a result of vicarious re-traumatization though their empathic listening. Trauma-fatigue is common for the therapists who have neglected their own mental health in the past, and/or fail to maintain it under the stress of their profession. My training was primarily in British institutions, where professionals are expected to keep a stiff upper lip and maintain one’s dignity as a professional regardless of any internal turmoil. The risks of vicarious trauma and trauma fatigue were never mentioned in my training. 

Looking through the case files of successful suicides, I have come to the conclusion that the common element was that hope was missing. There was a failure by the therapist in that critical goal of instilling a sense of hope in the patient. Hope is the predicate to reversing the suicidal path. Sometimes the right medication, or even electro-convulsive treatment, was able to slow down and perhaps reverse the progress towards self-destruction, but not always and certainly not in a majority of the cases I reviewed. If a therapist is honest in their self-reflection, consider the possibility that one if one gives a subtle signal of giving up on the patient, that can and often will be seen by the patient as a message of “permission” to end their life. 

To put this in a practical context, when a therapist faces a patient who is imminently suicidal, the first response is to determine, by knowing the patient’s personal circumstances and/or through truly deep listening, how serious the risk is for that patient to act out on their suicidal ideation.

In my previous post on the [importance of hope](https://www.engagingmultiples.com/the-importance-of-hope/), I discussed briefly a particular patient who was suicidal. She was the last appointment in my day’s schedule. I know that many therapists would decide that immediate hospitalization would have been the correct response to this situation, and in many cases, if not most, they might be correct. However, this was a DID patient and I did not see hospital admission as likely being helpful to reverse that decision.

Hospitals can be a negative experience for the patient, especially when the treatment team or the ward milieu is not suitable for DID patients. One must remember some mental health professionals do not even acknowledge DID as a legitimate diagnostic mental disorder regardless of its inclusion in the DSM. Hospitalization in this particular case would have meant a cop-out for me as the therapist as it would not address the actual triggering issue or the loss of hope. So, I decided the only way to approach this was to see if I could actively instill hope in her.

The key was that I took her words of hopelessness as a simple direct statement rather than a threat of any kind; empty or genuine. Her decision to end her life was averted once hope was instilled in her. I am confident that hope was what saved her.


## Imagery and Imagination in Healing

*Posted on March 26, 2016*

This is posted in response to a question from a reader. I think it is an important question with much relevance to the individuals with DID as well as others with trauma in their personal history. Again, as always, I am retired and cannot give therapeutic advice for individual cases. My thoughts on this and other topics are intended to be suggestions that are generally applicable and something to perhaps discuss with your therapists.

In therapy for healing past trauma, it is often suggested that one use “imagery” or “imagination” to create a safe place “inside” for the alters. These can be visual, auditory (hearing), tactile (touch), temperature and kinesthetic (sensations that inform us of our position in space). In my experience the most effective cues leading to relaxation are using the temperature, touch, and kinesthetic modalities. In most cases, the least effective is the visual modality. Generally, we do not need hearing in imagination because we can produce sound, such as raindrops falling on a rooftop, from a music player – whether it comes from a record, CD or audiotape. 

Instead of imagining oneself laying on the beach of a tropical island safely enjoying a protected holiday by utilizing visual cues of the white sand and the distant sails in the horizon, I would suggest that the person to imagine lying on the warm sandy beach (feeling the warmth on one’s back), and feeling the heaviness in the limbs and the backside as one is lying down after a long swim. It is my view that in seeing, one places oneself in the position of an observer watching something happening to another person. In concentrating on the sensation of touch, you become the person who is experiencing it.

I often sought to fully utilize the kinesthetic sense in imagery to produce better result. One way is to imagine oneself lying on a mattress which made of a huge bag full of little balloons. Imagine that the balloons are full of helium which is lighter than air, so that it is gently lifting you up in the air. Then imagine your legs are gently bending, flexing and extending all while being supported by the mattress holding you up. In your expansive imagination, you now are capable of doing simple yoga postures in the air because you are lighter than air, floating in the air. When you are imaging that, it is pretty difficult to remain tense. Fully using your imagination, give yourself the magical power to do whatever acrobatics in the air that you wish.

One can consider that two different aspects to the sense of touch: external and internal. Externally, we have our touch through our skin. Internally, through our muscles and joints, we can tell if our legs are straight or bent, if we are bending backwards or curling forwards into a ball. We do not need our sight to tell us that.

So, I suggest that you fully utilize your sense of touch/temperature/kinesthics with imagery; whether it is imagining that your body is feeling cool in a hot day under the shade of a tree or floating in the air. Pay attention to the bodily sensations of your breathing, the feel of the air moving in and out of your nose, the rising and falling of your chest. Bringing in a sense of relaxation, and most important of all, a sense of being in a safe place, you can re-learn what is it like feeling safe and enjoying the present moment.


## Do Young Alters Need to Age?

*Posted on July 9, 2017*

A reader of my blog asked me a private question about whether or not alters age (or remain stuck mentally at their age) even though it appears that they are able to do some adult tasks. This is an interesting and important question that I did not address in either Volume 1 or Volume 2 of Engaging Multiple Personalities.

I did not address this question in those volumes because my experience in DID therapy was focused on treating the alters as they presented. My recommendation is always to address the issues that are being presented by the alter or alters that are presenting them. I did not, nor do I recommend, that therapist try to “dig” into the background of a DID patient. In other words, I did not treat each alter as an individual for in-depth psychotherapy. If an alter’s problem was panic with hyper-vigilance, then that was the problem to be treated. 

The age of an alter, like the color of a client’s hair, is not a feature we need to focus on.  There is no therapeutic advantage in seeking to convert an 4 year old alter into a mature woman of the system’s chronological age, say 40, because the age of the alter is not the problem. 

Given that I never sought to help an alter “age” or “mature”, my thoughts on this question are somewhat speculative.

First and foremost, it is quite clear that alters arise as part of the dissociative process in order to allow the system to survive early childhood trauma. However an alter arises, it is tied to that particular trauma. I don’t see why there would be any need for such an alter to age, given that is served and may continue to serve a protective function should the system perceive the same or similar trauma environment. I see every reason for the system to permit the alter to remain as they arose in order to have that mode of dissociative protection available if and when needed.

I do not say that the alters don’t change. It is my experience is that they do change. However, for my patient’s, the alters didn’t change their age. What did change was their ability, with therapy, to remain ever more grounded in the present so as to more properly distinguish danger from the ordinary ups and downs one encounters in life.

In other words, the hyper-vigilance was tamped down. I did not encourage eliminating vigilance as there remain dangers both ordinary and trauma related. It is the hyper-vigilance that was interfering with their life.

Second, I think it is a conceit of those who do not have DID, that have a unitary ego structure, to think that the “correct” or “healthy” result of therapy is that the alters age to the system’s chronological age. It would be far better for therapists to appreciate the brilliance of dissociation as a protective mechanism that arises in the fiery cauldron of early childhood trauma. Knowing its roots in that horrific early childhood trauma, one can have a much deeper appreciation for the strength of the system that enabled survival through dissociation and the consequent alters.

Third, my approach to therapy was always to encourage cooperation among the alters. I think this occurs to some extent all the time, but in times of stress, when unprocessed trauma simply erupts through the appearance of one or more alters, therapy is critical. In DID therapy, we seek to eliminate the internal conflicts that prevent such cooperation. Eliminating the conflicts allows for greater cooperation and a more clear experience of co-consciousness. This limits the hold that the past trauma has on one’s present existence.

In fact, I often encouraged systems to designate alters within that could comfort each other when no therapist is available, to provide an empathetic ear to listen to frightened or angry alters, and to help communicate across amnestic barriers. As cooperation was enhanced, the systems were generally able to use that cooperation as a way to strengthen their ability to remain grounded and healed.”

As their lives become more peaceful (less roller coaster like, and less stormy) the system’s need for different alters to violently seize control, as opposed to cooperatively working with each other, will diminish.  We are definitely not asking them to disappear, but they seem to lose the need to insistently take charge.  Instead, they will begin to behave in a non-disruptive way. 


## Progress in the DID Community – Part 1 of 2

*Posted on January 27, 2020*

Since the publication of Volume 1 of Engaging Multiple Personalities, followed by Volumes 2 and 3, many members of the DID community have written to me expressing appreciation for those books. They have said often, directly and in Facebook groups, that the material has been helpful to them as well as to members of their support network. In fact, many have brought copies of my books and blog posts to their therapists to help communicate their needs as a patient with DID. This feedback from the DID community allows me to continue to push forward to communicate the importance of correct diagnosis and correct therapeutic support.

I have even received some notes directly from therapists about how helpful the volumes have been in their own work with DID patients. That is the good, actually wonderful, news.

Almost 6 years have passed since Volume 1 of Engaging Multiple Personalities was published. Volume 1 reviewed patients identified as having experienced early childhood trauma and dissociation. Some of these had been treated successfully with psychotherapy as their antidepressants were simultaneously tapered off and discontinued. I tried to identify the reasons why some were treated successfully while others were not. From members of the DID community, there were expressions of relief both that their difficulties had a context and that healing was possible. A year later, Volume 2 was released which specifically focused on guidance for therapists. 

Unfortunately, it seems that the psychiatric community still remains, for the most part, fundamentally unchanged in its view of DID. Copies I sent to colleagues failed to cause even a ripple in their consideration of DID and early childhood trauma. In my naivete, I expected them to be at least disturbed enough to re-examine their prejudice against DID diagnoses. I hoped to raise their index of suspicion when meeting patients with depression, self-harm and dissociative presentations to at least consider the possibility.

From colleagues, I got the uncomfortable feeling that Volume 1 in particular was treated as a book of curiosities. They were not so interested in the other Volumes either. Because my peers had not identified any such cases in their decades of practice, they ignored my suggestion that perhaps they had simply missed them. 

Nevertheless, I was confident in this explanation. Why? Because in the many patient referrals I received, their files included notes identifying them as having dissociative tendencies and presentations *without a primary or even secondary diagnosis of a dissociative disorder*.

I am confident that psychiatrists see many dissociative patients in their daily practice. They don’t identify them as such because they are not expecting to see them. This is based on their own incorrect training mischaracterizing DID as extremely rare, Therefore, their index of suspicion is very low. Further, therapists are routinely distracted from the dissociative symptoms by their search for symptoms of depression. Why? It is because their index of suspicion is geared towards symptoms that will justify and support the prescribing of medication; i.e.  antidepressants.

It is of ongoing concern to me that psychiatrists and other therapists are so stuck in their habitual way of looking at patients that they are not able to raise their index of suspicion to include dissociative disorders, despite overwhelming evidence.

Many years ago, a friend told me that he took a course on how to identify edible wild mushrooms. As soon as he completed the course, he suddenly started to notice just how many wild mushrooms were all along his daily jogging path. If only that kind of change had happened in the psychiatric community after we published the book(s). We can still work toward that.

Is it worthwhile to repeat this *ad nauseam*? I think yes. Why? Because of the response noted above from the DID community itself. 

## Progress in the DID Community – Part 2 of 2

*Posted on January 28, 2020*

In today’s psychiatry, medication has become the de facto treatment plan. Many colleagues are no longer even pretending to do psychotherapy. They are being trained by representatives of the pharmaceutical industry to see all mental disorders as brain diseases. While there are definitely therapeutic uses for psycho-active medications, using them as the wholesale solution to all mental health issues gives modern psychiatry a false air of scientific credibility.

This is a disaster in the 21st century. There is massive early childhood trauma throughout the world. This includes violence and sexual trauma in war torn regions as well as in refugee camps, not just in so-called healthy societies. There is no treatment focused specifically on those children because of the overwhelming nature of warfare and its consequences.

Make no mistake about it, the trauma is there and will become a massive problem that will show up in a few decades for those children whether we acknowledge it now or not. This is on top of the ongoing early childhood trauma that arises in the absence of war but in the realm of our own somewhat hidden and somewhat exposed plague of abuse. 

The foundations of psychiatry include Pierre Janet’s classic papers on PTSD at the end of the 19th century. It also includes Freud’s original assertion in 1895 that incest was the root cause of several of his patients’ difficulties. That initial assertion was withdrawn by him following a withering attack from the medical community of the time. They were insulted at even the idea that professionals, men of wealth and power, or that men in general, would do such a thing. Although perhaps Viennese society was not ready to look at its own dark side, that initial assertion was likely quite correct.

The early leaders in psychiatry pulled back from identifying early childhood sexual trauma for what it was. We should not do that, nor should we countenance others doing that. DID is a specific consequence of early childhood PTSD. We can be honest about that. That is the path forward. We can also use the acknowledgment of DID as a special sub-classification of PTSD to move forward the conversation and treatment of DID.

The common understanding of PTSD in soldiers was acknowledged throughout human written history. Physicians characterized it as “nostalgia” as early as the 1600s, “soldiers heart” in the US Civil War, shell-shock in World War I, “battle fatigue” in World War II, and PTSD in the DSM-III. By the end of the Viet Nam War, PTSD was being seen correctly as not a failure of will or defect of personality, but a product of trauma.

It is this understanding of the wartime foundation of PTSD which is the key, in my opinion, to bringing awareness of DID to the professional community. They accept PTSD. We should use this acceptance to highlight and identify DID as the product of (early childhood) trauma which it is, just as (battlefield) trauma results in soldiers with PTSD. 

If you are someone with early childhood trauma in your background, or speak with someone who does, you will know that the analogy of battlefield trauma is spot-on. Any child who is being or has been traumatized early in their life on an ongoing basis experiences life as a battlefield. They live surrounded by potentially overwhelming adversaries seeking to harm them again and again and again. 

Please continue to use whatever of my books and blog posts you think will help educate your own therapists to help you on your personal journey of healing. 

I continue to hope that the small contribution the books and blog posts have made to support those with DID will ultimately produce a sea change in psychiatry away from automatic pharmaceutical intervention. I hope that they lead to the return of proper psychotherapy for the benefit and protection of those that were abused as children who are trying to heal now as adults.

## The Therapeutic Alliance – Part 1: Our Fundamental Humanity

*Posted on February 13, 2020*

When two people meet, be it just for a handshake or making a deeper connection, there is much more that takes place than what meets the eye. There is a kind of transaction that takes place, whether it is a mere acknowledgement or a meeting of kindred spirits. With this reference point, Eric Berne developed the concept and paradigm of transactional analysis. In that paradigm, all social engagements are seen as transactions between people in their parent-like, child-like, or adult-like ego states. 

For me, the ideal state is when 2 people meet in what Martin Buber’s referred to as an “I-Thou” relationship for a soul to soul encounter. I imagine that was the experience when Martin Luther King met Thích Nhất Hạnh or Father Thomas Merton. Although they were from very different backgrounds, they related as brothers, soul to soul. What they didn’t bring into the experience was an ego defence barrier. They were completely open to one another without asserting or subsuming their background in the engagement. 

Well, we are not all able to do that but we can see that as a most positive aspiration. But, let us find out what we ordinary human beings can do, as therapists and clients in a healing relationship. 

I cite the religious and philosophical thinkers above because in being practitioners of science based medicine, we somehow often forget we have souls. In that forgetting, we turn away from our fundamental humanity. But, that fundamental humanity matters most when we are dealing with crisis, trauma and healing. It is the key to a successful therapeutic alliance between therapist and patient. 

In looking at books regarding different approaches used in psychotherapy, I find that little time is spent discussing the very basic fundamentals of psychotherapy. Perhaps they are so self-evident that authors and teachers assume it is unnecessary to restate them. I disagree. It is always necessary to return to and remind ourselves of the foundation of therapy, empathy, which is integral to our humanity.

I respectfully request that you not let my use of a word like soul, or to speak of religious thinkers, discourage you. I use these words for that which I am unable to communicate using conventional language. Most of our speech refers to concrete things such as a chair or a pound of butter. While such materialistic terms are necessary to our everyday existence, they are inadequate in communicating the wider sense of our experience. 

When we use words like compassion, empathy, and understanding, we cannot use materialistic terms. You cannot scientifically measure the love you have with your significant other. You cannot scientifically measure the pain you experience when someone close to you passes away. So, we start to use words differently. For anything beyond the materialistic world, we need to use poetic language and often metaphors. 

So please allow me to use words like love, humanity and God in that way. The way I use the word God, God is not an object I can pinpoint or describe in any literal way. For example, I cannot say, “God is here, not there.” I cannot place God in a location. As with love, God has no color, no size or weight. What I reference as God is not confined by time and space. It is in that same context that I speak about “soul” as in “meeting of souls.”

Carl Rogers emphasized the critical nature of a person-to-person relationship between therapist and client/patient. That is the environment which can provide the patient with genuineness (openness), acceptance (being seen with unconditional positive regard), and empathy (being listened to and understood). To me, this is the necessary and basic requirement for the foundation of a proper therapeutic alliance, from which healing is possible. 

Time and time again we are shocked when we encounter practitioners of healing professions that are lacking in such qualities. I mentioned the meeting of souls as the highest ideal. It is one that we seldom achieve. But, that is the lodestone we aspire to in seeking to create the person to person therapeutic alliance so critical to healing. 

These days, patients need to make a great deal of effort to see a therapist. One must spend the time and energy getting a primary referral from one’s doctor. And then, one must phone for an appointment and often experience an automated recorded voice saying something like: 

“Please hold……If you wish to speak in English, press 1. If you are a new patient calling for an appointment, press 2, if this is ……. press 3. If …………..press 4.” After days, weeks and sometimes months on the waiting list, you finally arrive at the psychiatrist’s office. Then when you see the psychiatrist, all he does is acknowledge that you are not doing so well. It can be along the lines of: “You are depressed. You need to take this medication. It usually takes up to a few weeks to work, so be patient. We will start with this dose and then see from there.” Does it sound like a therapeutic relationship, a space in which healing will take place? 

All the years of learning in university are irrelevant unless we keep in mind that we absolutely must connect with a patient. Without that connection, we will be unable to help them work with their trauma. Expertise can make a difference to the outcome but if, and only if, it is leavened with empathy, with compassion, and with openness. 

That is why I believe the most fundamental issue is to create a field for healing to take place. It is like sowing seeds, some fall on to rocks, and others to concrete ground. Only those seeds falling onto suitable ground, with the right amount of moisture, the right kind of soil mix, and the right amount of sunlight that will enable the seed to mature into a plant. This suitable ground for healing, this fertile milieu, is what we call a *therapeutic alliance*.

It is the foundation of a relationship between a healthcare professional and a client (or patient), hoping that their engagement will effect beneficial change in the client. This relationship is the milieu, the soil from which will facilitate the sprouting of a seed that will grow into a healthy plant reaching down into the earth for nourishment and up toward the sun to flower.


## The Therapeutic Alliance – Part 2: Genuineness, Acceptance, And Empathy

*Posted on February 13, 2020*

With a proper therapeutic alliance, the emphasis of the therapist on one side and the client on the other changes. It is shifted to the medium in which the communication occurs. It focuses not so much on what the therapist can do, but whether a milieu has been nurtured such that the client feels safe and trusting enough to take the hand offered, as it were, to get out of a difficult situation.

As therapists, we must bear in mind that we are not the only ones doing the assessment in an assessment interview. Your patient, after waiting for a few months to see you, has more invested in this venture than you. They are assessing whether they can trust you enough to share their innermost vulnerabilities, their most private concerns. If you don’t establish the ground for that therapeutic alliance, if you have not engendered the feeling of safety, space and time to open up, then it will not happen. 

It is in this context that the effectiveness of CBT (cognitive behavioural therapy,) EMDR (Eye movement desensitization and reprocessing and DBT (dialectical behavioral therapy), all recommended therapeutic approaches for cases of trauma, dissociation, and borderline personality disorder, must be evaluated. Without considering the importance of a therapeutic alliance, it is misleading to say that CBT, EMDR, DBT or any other therapeutic model are the treatments of choice.

When a psychiatrist offers you an antidepressant pill for your depression, in the absence of the correct therapeutic alliance – even if it is an appropriate prescription – you will remain locked in your belief system. That will counteract the psycho-active effect of the drug. It is noteworthy that most people understand the placebo effect; the beneficial effect that cannot be attributed to the pharmaceutical properties of the drug itself and must therefore be due to the patient’s belief in that treatment. People are less aware of the nocebo effect, which is the opposite. The nocebo effect is that the patient’s disbelief in the treatment lowers the positive pharmaceutical impact of that drug.

Therapists take heed: One’s therapeutic effectiveness is directed related to quality of the therapeutic alliance we create in each and every one-to-one therapeutic session. It depends on how you say “hello” or even months prior to that, when and how the appointment was made.

*The genuineness of a therapeutic alliance often explains how a history of early trauma is sometimes given to one therapist in the first visit, while other psychiatrists may have spent years with that same patient and still missed it.*

This is the mechanism by which some world known professors and heads of major universities as, well as the chief editor of a major national journal of psychiatry, erroneously declare that dissociative identity disorder is non-existent, is a fake disorder or created by over-enthusiastic therapists. They assert it is impossible because they never have encountered one such case. In fact, the odds are that they simply failed to recognize those cases. Instead, they decided upon common misdiagnoses such as treatment-resistant depression (which should usually be more correctly identified as drug resistant depression), bipolar disorder(s) and borderline personality disorder. 

With self-reflective insight, they might come to understand that they have never given the time, space and safety for their patients to show them their innermost pain and suffering. The fact is that when a patient feels safe enough during therapy, spontaneous catharsis happens without asking. Our duty as therapists in such an event is to protect the patient from inadvertent re-traumatization throughout the cathartic process. 

Focus on the process of healing, not the detail of the trauma. As always, the right therapeutic alliance guides the therapist to be sensitive to the need of the patient.

Being a brilliant scientist is of no use if one forgets that one is basically human. Religion is not about arguing whether or not God exists, whether or not God has this or that quality. The men I have quoted in Part 1 of this post are all from different religious backgrounds. Ultimately, it is about being reminded that we are human. 

I offer and will repeat to offer the following guidance of Carl Rogers’ emphasis of a person-to-person relationship between the therapist and their client, one that is characterized by genuineness, acceptance, and empathy. That emphasis is worth more than any diploma on your office wall.


## Using a Card for Communication

*Posted on February 25, 2020*

I received an inquiry from a DID FB group participant asking if I could suggest a card that might be carried by someone with DID. The idea is that it could be used to explain what they needed when dealing with a difficult public situation, like waiting too long in a doctor’s crowded office. In short, something that could be used in that kind of situation to let whoever you are dealing with know what you need without having to explain in detail.

The analogy that came to mind was the cards some deaf individuals use to alert people that they are deaf and so lip read or use sign language to communicate. For those who are deaf, it is something along the lines of “I speak in sign language. If you don’t, in order to help with communication, I also read lips so please look directly at me and speak normally.” This alerts others that there is an issue in communication for which there is a simple clear solution.

Here, we are talking about a communication card to do the same thing for those with trauma issues in public situations. The card language I suggest below identifies the issue, which is anxiety and panic, and the solution. It is **not** necessary to identify oneself as having DID or other dissociative disorders. (I have cautioned in other blog posts concerning the risks involved in that.) In any event, your DID diagnosis is more information than is needed in most ordinary interactions, like at a doctor’s office or for a meeting at a government agency administration office.

Perhaps something like:
***“I have a problem with anxiety and panic. It can be triggered by being in a crowded or enclosed space as well as having to wait for appointments too long, even in a comfortable waiting room. If I have to wait in this room for longer than 15 minutes, it will be difficult for me. It is easier for me to slowly walk around the block while waiting. I will not be more than 10 minutes away. Please call me on my cellphone:  ____________ with a 15 minute warning and I will return immediately. Thank you for your understanding.”***

Keeping it short (this will fit on a business card) and simple, avoids the need for detailed explanations. Most questions in those kinds of social situations begin with asking for identification information. I would not have that information on this card – just your cellphone. I suggest you have your driver’s license and Social security information separately ready to hand to a receptionist, for example, as needed. This again limits the need for you to speak if you are worried about being triggered in that environment.

Keep your verbal responses to a simple yes or no. Perhaps have a pad and pen if it is easier to write a short answer rather than speak out loud. This is the kind of accommodation that is made for many difficulties. Once you identify yourself as having an anxiety problem, I think it unlikely that people will suddenly conclude that you have DID and proceed based on their confused understanding of dissociative disorders.

The general public is well aware of anxiety issues and the idea of a panic attack. This may be a way to meet them where they are comfortable, in their understanding of anxiety, so that they can help you feel safe navigating the situation.

I never thought to suggest this to my DID patients when I was practicing psychiatry. In retrospect, I likely would have suggested it as something to try. I am happy to say that I continue to learn from the DID community. I hope this is helpful. If other members of the DID community have further suggestions, or perhaps better language, please do share that.

