# The Purpose of this Blog Collection

## A Wonderful Use of This Blog and Engaging Multiple Personalities Volume 1 and 2

*Posted on October 10, 2016*

I received a personal message giving me permission to discuss how one member of a DID Facebook group used my books, Engaging Multiple Personalities. With great joy and appreciation, this is the message I received, lightly edited for clarity and anonymity:

*“Yes of course you can have permission to use my words as you see fit. If it wasn’t for your blogs, I very much doubt I would be helping mental health [workers] in my tiny area make small changes. On Sept 16th 2016 we managed to get a training day on DID for all who work in mental health in our rural sleepy little town in the [UK]. Until we appeared in this little place, the psychiatrist tells me they never had a case of DID!? I suggested that they have but didn’t see them, misdiagnosed them or they are hiding still out of fear, fear they will lose their children, fear we will get that wrong label and be forced to take all sorts of unhelpfully unpleasant drugs. We weren’t accepted easily though. We were taken away from our family put on a section. We were forced to go through a forensic evaluation to assess the risk we were to the public and our youngest child, he is 14. They failed to see he is the last child at home of 6 who was never abused or made to witness our self-harm. We passed the core assessment and forensic evaluation 14 months ago but were only given the right to be alone with our child 2 days ago. We committed no crime, we hurt no one. We were just brave enough to tell our psychiatrist that we have DID. But things are changing [here now]. Another 5 clients have stepped forward to reveal their DID but was in the local [mental health] system far longer than me. It does make us smile now that every person from mental health services we have seen since the training day now knows about DID. We are kept busy with appointments to speak to more CPN’S, social workers, therapists, crisis team nurses to help them in their education about what DID looks like, sounds like and to share our experiences with them. If we didn’t stumble on your books none of this would be possible. So, if we can give a tiny bit back to you to show our appreciation we are more than willing. Thank you from all 17 of us.”*

I commend this individual for her bravery and strength in first dealing with the difficulties of her local mental health system for herself and for then helping that same mental health therapist group learn about DID. I am delighted that my blog and books continue to help individuals and mental health workers far from my home! My guess is that with the DID education of the therapists, those additional 5 clients felt safe enough to then disclose their DID. This is how the DID community’s strength helps each other to heal, transforms therapists’ understanding of DID, and can continue to do so.

It was very kind for this system to want to give back to me, to show appreciation. But, truly, this is appreciation for the hard work my own DID patients put into helping me understand how to work with DID. In many ways, my books and blogs are their messengers – their gift of healing to others with DID.


## On Using the 3 Engaging Multiple Personalities Volumes

*Posted on July 10, 2018*

I want to express my thoughts on how best to use the 3 Volumes of the Engaging Multiple Personalities Series.

For those with DID, If you have a therapist, then Volume 1 may be very helpful to clarify issues you might be working on with your therapist. Given that DID manifests in many ways, some of the case histories might be useful by way of saying “this is somewhat similar to my experience” or “this is not what I experience.”  The therapeutic keys can also be good points to bring forward with your therapist to the extent they ring true to your experience.

For therapists, and for individuals with DID who may have found a therapist willing to work with them but who has little to no experience with DID, Volume 2 will be most helpful for the therapist while Volume 1 can be a bridge through which you can work toward a positive therapeutic journey.

For those with DID who do not yet have a therapist, Volume 3 was written specifically for you. It can help you understand that there is a definite context to your experience. That in fact, dissociation is a critical response to enable you to survive abuse rather than something crazy. Dissociation is not insanity, far from it. While Volume 3 is not self-therapy, it may give you a strong foundation, self-empowerment if you will, upon which you can build a therapeutic alliance that will work for both you and a therapist in the future.

I find it very interesting that while the books get a very positive response from those with DID as well as from therapists that have read them as a result of patients’ suggestions. I find it painful to have to repeat so often that the mainstream psychiatric community, and most therapists, still do not appreciate the impact of early childhood abuse that results in DID.
There are very few reviews on Amazon, where the series is sold. So, the outreach for these volumes is limited to those in the DID Facebook groups in which I post, and to which those members share. If people do find the different volumes helpful, and you feel safe enough to do so, please post a review on Amazon. I think it is likely best to do it anonymously or under a pseudonym. In that way, perhaps a wider audience of therapists, and those with DID that do not connect with the Facebook groups, may encounter the books.

Finally, I also learned recently that one of the libraries that purchased Volume 1 no longer has it on the shelves. Why? Because it has been read so much that it has fallen apart. If you contact your local library, perhaps they will purchase a hard copy which would then be a resource in that community.  But, at the same time, I know that the ebook version will not fall apart when it is used – no matter how many times! So, I am happy to donate the ebook to any library that wishes to have a copy regardless of whether or not they purchase a hard copy. There are certainly more libraries in the world than I can afford to do this with, but I am happy to start with 100. If your library is interested, please have them email me at [engagingmultiples@gmail.com](mailto:engagingmultiples@gmail.com).


## Post Stroke Thoughts

*Posted on August 5, 2015*

I apologize for not updating my blog or participating in any of the DID Facebook groups for awhile.

I am recovering from a small stroke. While the recovery is going well, such events are always an important opportunity to take stock of one’s life, conduct and aspirations. As you know, I wrote Engaging Multiple Personalities Volumes 1 and 2 last year in order to pass on the extraordinary knowledge and insight I received from my DID patients. Prior to my stroke, I was doing a bit of traveling but each evening I kept coming back to recollections of my patients. In hindsight, before I actually became aware of my lack of understanding, it is clear that I missed several DID cases.

In fact, early in my career there were a number of cases where I believe I fell into the traps I warn about in my books, diagnosing patients as bipolar or borderline. Like other psychiatrists of my generation (even up to now), I had been taught the DID was simply so rare that it was highly unlikely that I would ever see even one case. The result was that I did not pay attention to alters that showed up to see if I was trustworthy and open to their presence. Unfortunately, for some of my patients, out of my own ignorance, I missed the correct diagnosis/therapeutic path.

I hope that my books will guide other therapists to avoid making those same mistakes. I will continue to blog and participate in supporting the DID community as best I can during my recovery.


## Surprising Responses to Engaging Multiple Personalities

*Posted on November 13, 2016*

It has been about two years since the publication of Volume 1 of Engaging Multiple Personalities. While I have received numerous and important responses from individuals with DID and at least a few therapists, I have solicited responses from other readers from whom I had somewhat surprising feedback. I am putting up this post as it highlights some of the obstacles facing those with DID. Forewarned is forearmed, so I offer this as something to help prepare individuals with DID to deal with mistaken views on the part of therapists who should know better – and others they may encounter.

1.*“Trauma happened decades ago, surely patients can forget and move forward.”* This was also expressed as *“They should stop dwelling on the past and focus on the future.”* This is the most common response to my book by both general (non-DID individuals) readers as well as highly learned or qualified people, including two professors in Medicine, one church minister and headmaster. I am flabbergasted! I thought that by now it would be general knowledge that after some trauma, the memory is stuck in the body, and that one cannot wipe it clear based on the strength of one’s will. The saying is “The body keeps the score.” (Van der Kolk.)

General Dallaire of the Canadian Forces peace keeping soldiers Rwanda wrote a moving account of a flashback he had that was triggered by seeing a person chopping open a coconut shell with a cleaver. Simply seeing that image, he immediately began to re-experience watching people being killed with machetes. His ability to intervene and rescue anyone, to stop the slaughter, was blocked by the UN mandate prohibiting any intervention by him or his men.  He re-experienced the trauma of seeing what was going on, as if he was there once again.

That is the way flashbacks work, it is not a question of choice. They come back faster than a rocket, by-passing the conceptual process. They take over your mind and your body through the autonomic nervous and motor system before coming to one’s awareness. They take over your perceptions so that you are no longer grounded in the present, rather the past reaches out its hands to pull you back. People with PTSD all experience that.  DID survivors commonly experience that kind of flashback regarding early childhood trauma that might have happened decades ago.

2.  Another frequent question was, *“Do they really appear like that, as a 4 year old child in the body of a 50 year old woman?”* Rather than commenting on the depth of abuse that must have occurred to generate the protective mechanism of dissociation, this is the topic that generated interest. General readers, again referring to those without DID, sometimes get sidetracked by the dramatic aspect of the DID presentation, of an alter suddenly appearing. In doing so, they fail to grasp the impact of the trauma, the fear and suffering experienced the individual experienced in the past or in the present moment of a flashback, and consequent loss of function.

This is worse than unfortunate! In general, people do not want to face the ugly facts of childhood trauma. Because of how terrible the trauma must have been, people cut off their own empathy – perhaps afraid that they themselves will be overwhelmed just contemplating it. Instead, they often refer back to their own experience of a mild loss of details of events from their own childhood. But those references are to what life was like when they were 4 years old rather than imagining the trauma someone else experienced at that age that results in dissociation. It is safer for non-DID individuals to get carried away by the drama, and avoid the trauma.

3. *The general reader (and society in general) simply does not grasp the immensity of the problem, the number of individuals affected, and how horrific their experience must have been.* It impacts an enormous number of psychiatric patients who are looking for therapists to help treat their trauma and dissociation. It may be that this will change as the impact of foreign conflicts involving large numbers of traumatized children, just as it was not until the tidal wave of PTSD impacting military personnel returning from Vietnam forced society to at least acknowledge that it was there. And just as with the returning servicemen, the impact of the wartime trauma on children in foreign conflicts will take decades to truly unfold.

Certainly toward the end of my psychiatric practice, I repeatedly received confirmation from patients I meet suffering from depression that they were prescribed antidepressants without questions even being asked about their possible adverse childhood experience.    I am well aware that even when such questions are asked, they may not yield the correct answer in the first place – which may correctly be yes or no. However, when patients are not even given the chance to offer any information on past trauma, the therapist has failed in a fundamental way.

I encourage you to have confidence in your own experience as you proceed on your healing journey rather than be subject to the confusion and ignorance of even professionals. Find therapists who do understand DID, or train decent therapists, who simply don’t have experience, through the honesty of your journey.


## How to fight remotely
