# The Importance of Grounding

## Grounding Exercises and Working with Flashbacks

*Posted on February 9, 2015*

**All my postings are general comments, and must not be construed as treatment instructions for any specific individual. Should you choose to consider any of my suggestions, you must first consult your own physicians before exploring them.**

I do not find hypnosis useful while the client is having a panic attack or a flashback. However, hypnotic trance practice can be useful as a grounding exercise.

If you have had an experience of being in a hypnotic trance, you can easily go back to a trance by just remembering what it was like, how you felt, the last time you were in a trance. In other words, there is some of truth in the saying that “all hypnosis is self-hypnosis.”

People who have severe PTSD or Panic Attacks all have forgotten what it feels like to feel comfort in their body. It is good to remind them so that they can set that up as a goal in their practice.

**Grounding Exercise:** Do it while you are **not** having a panic attack or a flashback. The more you practise grounding, the better you are equipped for coping with the next flashback. One useful self-hypnotic practice is choose a private place, such as in your room. After locking your door sit down, close your eyes, and imaging walking down a flight of stairs. Slowly and with each breath, go one step down. At the end of ten steps, you will find a door, through which you can enter a state of deep relaxation. You can imagine, for example, being suspended in mid-air resting on air-cushions. If you wish to be more relaxed, go down another flight of stairs. The most important thing to remember is to take your time, walk down slowly, with each exhalation. **GO SLOW!** Once there, stay and enjoy the peace and quietness.

**Flashbacks:** One aspect of DID is the PTSD suffered by some of the alters. PTSD is similar to Panic Attacks in that once turned on, the anxiety is fed into a vicious cycle. It gets energized and stuck in a closed feedback loop. Forget trying to relax, it does not work to try to force relaxation. To get out of the cycle, one has to take over the control of one’s body. For example, start doing 10 push-ups. What happens when you do 10 push-ups? Your heart rate probably goes up beyond the heart rate produced by you panic. If not, you do another 10. Then sit down and notice your body settling down to a comfortable state. **It will on its own.**

If you have had an experience of a hypnotic trance, it will make it easier if you remember what it feels like to be in a comfortable and relaxed situation. Notice I don’t say try to relax, but just notice the *inevitable* relaxation after 10 push-ups.
Alternatively, instead of doing 10 push-ups, you can go have a shower. You can have a hot shower, then turn off the hot water and let the cold water shock you a little. In Finland people go into a hot sauna and run out to roll in the snow, so why not?

Instead of a shower, you can go out and walk briskly or run around the block. Take the initiative to find a way that is uniquely helpful to you. The natural state of calmness and ease that results from these grounding exercises will show you that you are master of your body. This mastery helps you to overcome the flashbacks and panic attacks.


## Mindfulness Meditation and DID

*Posted on October 6, 2015*

There was a posting on a DID facebook group that expressed some real difficulties with a mindfulness meditation based therapy the DID individual was trying. This individual was not alone in having difficulties as a DID person trying to do mindfulness based therapy. I discussed the issue with a friend of mine who is also a long time Buddhist meditation instructor. He did not want to criticize the facilitator of the group because no doubt they were trying to be helpful and hopefully were for most people. However, he said quite definitely that if you are afraid to close your eyes, then don’t. It is not necessary and usually not advisable to do so anyway when practicing mindfulness. His point was that if you are trying to be “here” mindfully, then why would you close your eyes or imagine a stream? The practice is to just be where you are.

He suggested being very simple about it. A traditional technique is to start with a good posture (a straight back), comfortable sitting position, relax your jaw, eyes looking gently ahead angled slightly down and so that your gaze is falling to the ground about 6-8 feet in front of you. Allow yourself to settle and then simply count your outbreaths up to 10. Don’t try to manipulate your breathing, just go with how it is happening. If you lose count, just start again with 1. Do not criticize yourself if you lose count, do not praise yourself if you get all the way to 10. Either way, it is no big deal. If you get to 10, start again with 1. Do it for a short time, especially when beginning to become familiar with mindfulness. Even just 1-2 minutes is good or you can try just 5 or 10 breaths, however long that may take. If you can do it even just a little each day, that is great.

For someone with DID, it is critical to experience feeling safe, so don’t do anything that is going to frighten you or any parts – such as closing your eyes (or scanning your body which is a technique in some mindfulness therapies) if that is a problem. Try just sitting and counting outbreaths in a safe physical space of your own choosing. The first experience of most people starting mindfulness practice is that they become aware of just how many thoughts they really have. This is because there is so much more space for thoughts to appear when you are quieter than usual and not focusing so much on external tasks. 

But for someone with DID, those many thoughts can be quite scary. Individual parts may see that open quiet space as their chance to be out and carrying all their traumatic memories. The thoughts may be coming from many different alters so quickly it seems that they are all happening at the same time. With that intensity of traumatic memory and seeming chaos, it is not surprising that dissociation would occur right away. So, DID individuals must go very carefully with mindfulness meditation so that the open space doesn’t trigger the fears of all the parts at the same time and result in retraumatization instead of healing. 

But, if you can do it for only a few minutes or even just a few breaths, that starts you on the road to having confidence that you can indeed feel safe – even if just for 1, 2 or 3 breaths at a time! 

Experiencing safety starts with that one first breath. Make a decision before you start about how long you will do the counting. Try to do it for that long but once you reach your goal for the session, gently stop. That way you start to get the habit of being able to create a time-defined safe space which is a great habit to engender.

If and when you become more comfortable with the practice of mindfulness, you can increase it by just one or two more minutes or a just few more breaths. If you dissociate, no problem. When you recognize that you have dissociated, just go back to counting breaths without praise or blame directed to you or any alter. Encourage whoever is out during the dissociation to please try to continue to do the counting of the breaths while they are out. If they will do so, great. If not, don’t worry. You can always gently (always gently) invite them next time. You can express that encouragement to the parts before you start, so they are acknowledged and even a bit prepared. 

Slowly, there will likely be some benefit to the host, to the alters that participate, and also to those that watch without participating. Even a small benefit will encourage other alters to start to watch, maybe even participate, and to share that taste of safety in the breath. In fact, inviting the ones that appear when you dissociate is a very kind way to empower those alters, to show them that they too can be mindful of the “here and now” also – safely and without struggle.

Remember, keep it short – especially at the beginning – and always safe . Later, if the practice is helpful, keep it safe and extend it for just a bit longer. The critical point is experiencing safety in the here and now.


## Breathing

*Posted on November 24, 2016*

It seems a bit silly to tell someone how to breathe. After all, everyone breathes. But,”take a deep breath” is something people have been saying to others for generations when trying to help them calm down. What is the connection between breathing and healing, or potential healing in connection with DID?

Therapists have clued in on yoga and meditation as having some benefits in the psychological healing and restoration process. Many therapists encourage patients to engage in breathing exercises and “controlled” breathing. They usually connect this to mindfulness; meditation stripped of its spiritual/religious context. Previously, [I posted on the risks of mindfulness meditation with DID](https://www.engagingmultiples.com/mindfulness-meditation-and-did/). In my experience with patients, the benefits are not so automatic as some people say. And, there are risks.

Breathing is governed by the brain’s respiratory center. While you can control your breathing as a voluntary act, your brain will continue to instruct your body to breathe without you having to continually give conscious instructions to do so. Beyond that, even though one can willfully hold one’s breath, the eventual lack of oxygen and accumulation of carbon dioxide in the lungs causes the brain’s respiratory center to overwhelm your will: You breathe again whether you want to or not. The point here is that breathing is governed both involuntarily as well as voluntarily. 

Breathing patterns change when a person is under stress. A person under stress, any person, is likely to automatically to hold his breath or to breathe laboriously. In a genuine panic attack, one often feels as if one has to catch their breath, or as if one cannot breathe at all. A person in a panic usually takes very shallow and very fast breaths. This comes back to the common message we all get – to “take a deep breath” in order to calm down.

In my opinion, “take a deep breath” is the wrong phrase to use. I preferred to tell my patients to slow down their breathing. Why not tell them to take a deep breath? There are two reasons. First, I want to avoid encouraging already panicking patients to continue with their rapid breathing, just try to grab more air as you pant.. That doesn’t address the panic – the patient continues to panic. As a therapist, you are then encouraging them to experience their panic attack like a drowning person trying to suck in all the air they can. Second, and most important as a therapeutic intervention, panic attacks are about experiencing a loss of control. Fear is coupled with that sensation of the loss of control. Therapeutic intervention needs to address the physiological connection between breathing, fear and the loss of control.

It is my experience that enabling a patient to reclaim control over their physiological response to fear gives them a tool for coming back to the present moment. It is often a very effective tool that opens a door to escaping the entrapment of the triggered physiological panic response. Go back to the fact that breathing is a blend of voluntary and involuntary control by the brain: It is within your power to slow down your breathing. One can start by slowing the breathing down just a little bit. With practice, a patient can utilize their voluntary control of breathing in a gentle way to slowly bring themselves back to a place of psychological safety. That is enabling a patient to connect with and rely upon their own fundamental strength. That is empowerment – the opposite of loss of control.

Slowing down the breathing, rather than fighting the gasping for air head-on, allows the brain to blend back the voluntary control back into the involuntary panic driven breathing. Going from 100% involuntary control of panicked breathing to 98% involuntary control and 2% voluntary control can happen without inducing further panic responses. Then one can slowly increase the percentage of voluntary control, perhaps to 5% voluntary control and then maybe 10%, and so on. So, for me and my patients, the key phrase was “slow down the breath.”

Once the patient is willing to try to slow down the breathing, even asserting only 2% voluntary control, they then have the direct experience of being able to assert some level of control over their breathing. That small level of control is the experience of having power over the impact of the past trauma – even just that little bit. The patient discovers the fact that it is possible, through one’s own breathing, to regain control over their body – which is taking control away from the past trauma.

Slow breathing is always associated with a sense of “equanimity and tranquility.” In slowly breathing out, one activates the parasympathetic nervous system and engenders in the body a trophotropic state – a state where the body rests and recovers its energy. It is a physical sensation that enables the distressed person to discover such feelings in the midst of chaos and fear. This is the way to redirect one’s attention from the impact of past outside trauma to the genuine sensation of inner well-being.

Phrases like “take a deep breath” or ” controlled breathing” are action-oriented. I choose to use more laid-back expressions that suggest lack of confrontation, expressions that call to mind receptivity and awareness. Encouraging a patient to slow down their breathing a little bit at a time lacks any harsh quality of an external command by the therapist. It remains as it should, a suggestion that we can tap into our strength safely. Putting it simply, all is not lost when you are still breathing.

In recent years, there is strong scientific evidence for the benefits of mindful breathing. Mindful breathing is a spiritual practice thousands of years old that is used in many religious traditions. But traditional instructions on mindful breathing are not about control, they are about letting go of the thoughts that tend to take one away from the present moment. The instructions are, effectively, to ride the breath, in and out, as the vehicle to do that letting go. 

In the West , as Allen Watts pointed out, it is difficult to understand the concept of “being” as distinct from “doing.” Broadly speaking, in the Judeo-Christian Western world it is uncomfortable to “just be.” It seems that one has to be doing something at all times. The story used to explain this involves  a group of villagers debating what a man, a distant figure far away, is doing. When they approached the man, asking him exactly that. He replied, ” I was just standing here.” That’s it. One does not have to be doing something in the active sense to justify one’s existence. One can “just be.” Arriving in a new place, one can just absorb the experience of sound, sight, smell and taste of the land he is visiting. 

While numerous neurological studies have concluded that prolonged practice of meditation can actually change brain structures and alter its way of reacting to stress, DID individuals must approach it slowly, gently and with protections in place. Again, in my experience, start by slowing down the breath when you panic. Practice that slow control mechanism until it becomes a habit. In that way, you are always enhancing your ability to protect your connection to safety in the present moment. 


## The Meaning of Forgiveness – Part 1

*Posted on February 25, 2018*

During the past few months, the question of forgiveness has repeatedly come to mind. I think this is somewhat both a haunting and daunting topic that usually arises at some stage of everyone’s healing process. 

In the context of DID, the question is why should anyone even consider forgiving the person who abused them? It is not sufficient to do so just because one is told to believe that it is the right thing to do. Even if one is told to forgive as a matter of religious doctrine, one still needs to understand the connection between the doctrine and the forgiving of such a crime.

It is often instructive to understand the origin of a word that is used so often and that can be so loaded. In the context of Christianity, the Greek word translated as “forgiveness” in the King James Bible literally means “to let go,” as when a person foregoes demanding payment of a debt. In his parable of the unmerciful slave, Jesus equated forgiveness with canceling a debt. (Matthew 18:23-35.)

The word translated as forgiveness is used to convey the state of mind we have when we let go of resentment, for when we give up any claim to be compensated for the hurt or loss we have suffered. But forgiveness of debt doesn’t mean the debt never existed. It doesn’t mean you have to loan more money to the debtor. 

We must be honest with ourselves and with others: There is a big difference in letting go of a debt of few dollars as compared to letting go of the pain and anger connected with the abusive perpetrator of our early childhood trauma. If we lose some money because someone has failed to repay us, or someone has dealt with us in not such a good way, we can usually figure out how to proceed the next day or the rest of life because our core being has not been ruptured and split apart. An abuser has adversely affected one’s entire adult life, and we cannot simply go about our business. There is no way to give a clean slate back to the child who has been psychologically pulled apart by trauma. There is no do-over.

To put it in another way, if one’s whole life is ruined because of an early abusive relationship with the perpetrator, it is a different story than simply forgiving a debt of money or a minor inconvenience that one has the capacity to simply “let go.”

Forgiveness also means pardon. Is it possible to pardon a perpetrator if the perpetrator does not even own up to the damage he has caused? Does forgiveness means somewhat condoning the evil act and/or allowing it to continue, possibly hurting future victims? What are the options for forgiveness? 

First, one must be honest. Letting go does ***not*** mean denying the damage that has been done. Letting go does ***not*** mean nothing ever happened. Letting go does ***not*** mean condoning the evil act. 

Second, one must protect oneself. Most early childhood abuse is based on the most fundamental betrayals imaginable. Letting go does ***not*** mean allowing a perpetrator to ever get close enough to harm you again.

Third is perhaps the most difficult. If you let go of the pain and anger, you might be able to understand that most people who abuse others were themselves abused. This does ***not*** in any way shape or form undermine the critical important of the second point about protecting yourself. It simply means that you can understand the abuser was or is in pain, is confused, and is likely driven by their own trauma.

Again, that does ***not*** mean you let them anywhere near you ever. It does ***not*** mean you let your child or other children anywhere near them. Instead, it means that you can let go enough to wish that they are able to process their own pain and trauma. Letting to in that way is forgiveness enough so long as you remember that it is ***not*** your obligation to help them process anything. It is their obligation, and it is theirs alone.

In this way, you can be very clear why you might forgive them, while at the same time remaining absolutely firm that your letting go does ***not*** permit them to come anywhere near you, ever. If they wish to make amends, they can turn themselves in and confess to the authorities. If they wish to do something beneficial in penance for their evil deeds, they can anonomously donate all of their money to a charity devoted solely to protecting children from abuse. Why anonomously?  Because that prevents them from evey being seen as an angelic benefactor for abused children. Whatever they may choose to do, or not to do, is their choice, their problem, their concern.

*The original meaning of forgiveness requires nothing from you other than letting go of what you hold onto.*

It is a dangerously false assertion, religious or otherwise, to presume that forgiveness means giving someone a clean slate, to presume that it demands you ever share space with an abuser. You have nothing to prove to anyone about your forgiveness. Please be extremely clear and firm about that. Forgiveness is solely about your letting go, ***not*** what happens to or with anyone else.

In short, forgiveness does ***not*** mean forgetting what has happened and pretending that from now on, one can have a “real” relationship with the perpetrator, as if nothing pathologically evil had ever happened. It does ***not*** mean that with forgiveness, one can “be friends” with the perpetrator. It does ***not*** mean, in the case of incest, that one can have a normal father-daughter or sibling relationship with the abuser. Such things are ***not*** possible. To hold them out as a goal to strive for will prevent healing rather than foster it. 


## The Meaning of Forgiveness – Part 2

*Posted on February 25, 2018*

The reason to consider forgiveness in the way described in Part 1 of this 2 part post, to consider letting go, is that non-forgiveness carries its own deep penalties. Intense and completely appropriate deep resentment, the deep sense of betrayal, and the other conflicted emotions that all go along with those are harmful to your own well-being, both spiritually and physically. But, do not ever forget that it was those same intense emotions that saved you as a young child. 

Those same intense emotions may manifest as alters that you have difficulties with because of their intensity. By engaging those alters and acknowledging the truth of both your pain and their protective intentions, you can transform the intensity from conflict with alters to mutual cooperative support. In that way, you can forgive but not forget. In that way you honor those alters and your own survival. In that way, you protect yourself from falling into the trap of mistaken conventional understandings of forgiveness.

Persistent anger and resentment, feeling oppressed and being hyper-vigilant are mental states that are harmful to the those who do not forgive in a safe and protective way. It tinges their way of seeing the world. They are quick to look for, project out and only see the faults of others. They color their direct perceptions and adopt a negative way of seeing the world around around them. They are likely to miss the birds singing or the sun shining. They miss all the good stuff of being alive. 

Their hyper-vigilance makes them paranoid and mistrustful. They handicap themselves and put up roadblocks to all potentially healthy relationships. In the extreme cases, they are chronically depressed, often drowning themselves with chemical addictions. They miss out on so many of the good things in life. So work on dialing down the hyper-vigilance. Let go into ordinary appropriate vigilance. It is safer and respectful to your protectors. They are still and will always be needed.

Physically, failing to let go results in chronically raised levels of cortisol, the so-called “stress hormone.” Scientists have clearly determined that elevated cortisol levels interfere with learning and **memory**, lower immune function and bone density, increase weight gain, blood pressure, cholesterol, heart disease. Letting go allows us to care enough about our bodies to get rid of negative hormones circulating in our system.

Again, we must be honest. Healing is a journey, a path. It is difficult to let go and forgive. One must pay attention to the part (whether it is a fragment of the person that appears momentarily, or an alter with the capacity for ongoing executive function) who is too hurt to let go of that anger and pain. One has to pay attention to these parts. One cannot just rush in and tell a part to forget the past and move on, so to speak. If you are a DID, ask who cannot or is unwilling to forgive, then gently allow that part to process getting over the negative experience he/she is stuck with. It will help to reinforce that the goal in forgiving does not, absolutely does not, include forgetting. It does not, absolutely does not, include allowing a perpetrator close once again.

Notice how much hurt the “alter” is still feeling. Work on consoling that part. If you are a partner of the one with DID, you can still work on a part that is unwilling and unable to let go of the hurt. Treat that part as deeply real as that part perceives itself to be. Work on consoling it to allow healing from the wound. 

It takes time, but the goal is eventually arriving at the stage that you will be safely released from the negative emotions of anger and bitterness. Learn to be kind to yourself, or that specific part of yourself. Then you can truly be free.


## Comments on Depression and Integration from Healing Together Conference presentation

*Posted on February 6, 2015*

I just returned from a Conference on DID in Orlando Florida (January 30th to Feb 1) and posted on Facebook about how positive and supportive the conference was for all participants, DID, therapists, supporters and speakers. This was a great meeting, well organized by the group called “An Infinite Mind.” The conference is called “Healing Together.”

The Keynote speaker was Robert Oxnam, author of A Fractured Mind, who gave a most inspiring and affirming talk on the positive aspects of DID. I was honored to be one of the speakers in a breakout session in the afternoon.

This post is taken from my presentation at the conference and is drawn primarily from Volume 1 of Engaging Multiple Personalities.

In chapter 5, I discuss my patient Ruth. She was experiencing unrelenting flashbacks, and self-destructive behavior, so much so that she was hospitalized 20 times by the time she was 28. Her children were taken away by her family in preparation for adoption out. She was diagnosed with a single diagnosis of Depression, plus a personality disorder. The treatment she had received, exclusively pharmaceuticals and electro-convulsive treatment, failed to alleviate her depression.

Under the circumstances, any reasonable person should understand that her depression was a normal and appropriate response to the reality of her circumstances. With the correct diagnosis of DID and appropriate treatment, the “depression” quickly disappeared.

After 2 and half years of intense psychotherapy, she was fully recovered and fully functional, without need to have further therapy or medications. Following up19 years later, upon receiving correspondence from her, showed her to be fully recovered. **The depression was both a misdiagnosis and a smoke screen. It was covering up the DID which the doctors never saw or even suspected.**

Ruth had brought up her children and was living a highly functional and creative life. She is engaged in helping other survivors of traumatized individuals through running a website as well as writing and publishing a book for survivors of abuse. 

What can we learn from this clinical example? **Depression is too often mistaken as a stand-alone disorder, when the doctor will too quickly reach out for an antidepressant and ignore the core issue. Depression can be a normal and even healthy emotional response to life’s circumstances, or as a co-morbid condition with another psychiatric illness.**

Further, the fact that she had numerous alters, over 400 even after her recovery, means that a therapist should not be obsessed in pushing for integration as the final goal. Really, so long as the alters are cooperating with each other and not fighting, there is no real problem.

While some people may scoff at anyone having so many alters, when I reviewed her old letters from my file with the card signed by an enormous number of her alters, the handwriting of each alter that signed the card matched with that alter’s handwriting 19 years earlier.

I hope this message can help therapists not be blinded by the word depression, or be obsessed with the notion of integration. The fields of past trauma and dissociation, and the DID patients in particular, are waiting for the current generation of therapists to step in to help those suffering from something that is more than depression. Groups such as An Infinite Mind and Ivory Garden (that put on another incredibly supportive conference for DID survivors, therapists and supports on the West Coast) are doing a great job in supporting individuals with DID. Their work extends to the important task of raising the public’s awareness of the need for correct diagnosis and treatment.

I shall post something from my talk and my books on DID on this website from time to time, hoping to continue my effort to improve the well-being of those individuals with DID, for those who are supporters of DID individuals, and for therapists.


## Avoid Retraumatization

*Posted on February 24, 2015*

The sad and terrible truth is that people prefer to simply ignore the depth of horror that the abuse of children entails. They find it easier to dismiss stories, memories, and writings than to look directly at the evil of child abuse and confront it. It makes hiding the abuse easy for the perpetrator and places an overwhelming burden on children to deal with it, often decades later. People who have survived traumatic abuse know all too well the truth of such evil. The evil is compounded when, as an adult, they continue to have their traumatic history denigrated and dismissed.

PTSD and complex PTSD always involves the loss of control, whether it be in a courtroom at the hands of a defense attorney on cross examination or at the hands of a celebrity “therapist” seeking ratings and phony closure within the 45 minute segment they are promoting. If asked by a patient about the advisability of suing an abuser, I always cautioned about the risk of retraumatization.  While it was always the patient’s decision, when asked, I always urged careful consideration of this risk. Then, I supported whatever choice they made.

Re-learning the experience of safety is not easy when safety is taken from you at an early age, but relearning it is the key to healing. Therapy is often and correctly focused in many ways on protecting yourself from retraumatization so that you can genuinely experience being safe in the present moment. You are not obligated to relate to abusers, past or present, whether they be family members or celebrities, regardless of their demands and promises. They will likely have their own agenda, which is not necessarily your healing. Your healing must be the priority, and remember that you are *never* obligated to retraumatize yourself for anyone’s entertainment.


## The Trap of Forgiveness

*Posted on February 24, 2015*

**In Volume 2 of Engaging Multiple Personalities, there is a discussion entitled “The Trap of Forgiveness” which is directed to therapists counseling DID patients:**

“Therapy must be practical. It must take into account the trauma that the patient must process. Setting an unattainable goal will only reinforce the patient’s negative self-image engendered by the abuse. One must consider the likelihood of success, so set goals in therapy that are within the grasp of the patient.

Some therapists, particularly those with a religious background, see the goal in healing as forgiveness. It is the view that being able to forgive is the ultimate expression of being healed. While it is a fine aspiration and appropriate in religious contexts, it is a dangerous goal to set for a patient.

Most trauma that leads to DID is so overwhelming that ordinary individuals cannot truly imagine the experience. To presume that one will eventually be able to forgive their abuser is, for practical purposes, a fantasy. Focus on the task at hand, teaching the patient to experience and hold on to the safety of the present. Teach the patient that skill so that they can experience the safety of the present when memories of the past arise. When memories are just memories, no longer the involuntary reliving of pain, that is what it means to heal.”


## Working with flashbacks

*Posted on November 19, 2014*

Therapy comes down to one simple goal: *helping patients make friends with their own mind*.

**I often encouraged my patients to engage in physical exercise during a flashback.** By reclaiming the present moment in the body through exercise, my patients became more able to self-titrate exposure to their memories in a safe way. Teaching control and empowerment through the body experience of exercise in the present moment diminished the power of the past abuse in that present moment. Titrating exposure to the trauma in this way doesn’t deny or negate the flashback or its content. It is not telling the alter that the memory isn’t important. It is communicating that the system cannot safely handle the entire memory quite yet.

Over time, it makes the memory more accessible as it becomes less frightening and overwhelming. Learning to deal with one flashback in this way strengthens the system’s ability to deal with others.

## Panic Attacks

*Posted on August 19, 2015*

There are always many postings about DID and other PTSD patients being overwhelmed by panic attacks. I have discussed this in both volumes of Engaging Multiple Personalities in some detail but I want to emphasize that there is a path to dealing with panic attacks. 

The essence of any panic attack is the complete loss of control. First, one must engage in preparation – learning what you need to do to avoid that loss of control. For anyone, DID or otherwise, panic attacks are terrifying. They appear to come out of the blue, they arise with immediacy and always involve the sensation of a loss of control. It is very helpful to practice how to work with your mind and body at a time when you are *not* in the midst of a panic attack. 

For all human beings, there is a completely intimate connection between mind and body. If your mind panics, your body will follow. If your body panics, your mind will follow. Triggers, therefore, can come in many ways – events that trigger either one’s mind or body. While this can be confusing to some patients and therapists, it is quite straightforward.

The mind following the body and the body following the mind is actually quite good news. If the mind starts to panic, by calming the body the mind will settle down. If the body panics, by calming the mind the body will settle down. While it is sometimes too hard to settle a panicking mind with thought, you can often settle the body with exercise. Get the body in exertion mode (such as a brisk walk, push-ups or even dancing), exerting just a bit more than the bodily arousal produced by the panic. Then, as soon as you stop the exercise, the body will automatically settle down. As the body slows down, the mind goes along with it.

Alternatively, sometimes it is the body initiating the panicking. While it may be too hard to settle it down with exertion, by settling the mind through mindful breathing, the body will often follow.

Some patients ask what mindful breathing is. It is simply paying attention to a specific aspect of your breathing. There are many techniques, but the simplest is to count each outbreath up to 10 – and then repeat. You can also pay attention to the feeling of the air moving out through your nose on the outbreath and in through your nose on the inbreath.

You can be mindful of when the shift from outbreath to inbreath happens, and vice versa, just as you can be mindful of when you are holding your breath. When you see that you are tensely holding your breath, you can then control its release by intentionally breathing out. When you release the breath, the air goes out along with the tension that subtly caused you to hold your breath. 

Whatever method you use, understand that using a method rather than simply being carried along by the panic is an indication that you are re-asserting control. This is very positive.

Practice is what is called for, usually a lot of it done regularly. In a quiet safe space, you can intentionally allow a very small slightly negative thought to arise – something that is an ordinary everyday irritant and not a deep trauma. This is something which you are controlling, that is key. Remember, starting with baby steps is extremely important. 

As your heartbeat increases, choose to do some exercise or some mindful breathing. Then, after a few minutes when you choose to stop the exercise or mindful breathing, you will see that your mind and/or body has settled. Making a choice about the technique and trying it is a second indication/assertion that you are in control.

The point of the exercises is to re-empowerment. It is to create new habits in both your mind and body so that when you actually are hit by a panic attack, you have already created new pathways to react to it – all of which are marked by being in control. 

Do not try to generate thoughts of trauma and try to work them out this way. That is dangerous and will not be helpful. Please work directly with a therapist on the trauma material.

When in the midst of a panic attack, first try to remember what you have practiced, and second, try to do it. Don’t worry if you cannot quell the panic right now. Do not be angry with yourself if you remain terrified and panicked. That is not an indication of failure, it is simply an indication that you need to practice more in a safe place. Remember, this is a path that needs to be trod step-by-step. Even remembering that you are panicking more than you had hoped you would is an indication that you have retained some level of control in the midst of the attack.

While medication can support you in working with panic attacks, genuine healing occurs only when the disempowerment experience of the trauma is overcome. Re-empowerment is the goal. It is much more important than simply wrestling the agitated mind into submission again and again by a chemical which will have limited ongoing impact on the panic.

You have that power for re-empowerment in the present moment. Practicing before a panic attack, again and again, enables you to access that present moment power when you need it.


## Self-Soothing Techniques for Those Unable to Locate a DID Therapist – Part 1 of 3: Background

*Posted on December 14, 2015*

This post is to encourage the development of self-soothing skills. It is not psychiatric advice, as I am retired, no longer have patients, and cannot give therapeutic counsel. I am posting these thoughts and recommendations based on approaches I took with some of my patients that had positive results. If you do not have a therapist at the moment, please make sure that you remain safe as you consider or try developing self-soothing skills. If these seem like they might be helpful to you, and you do have a therapist, please discuss them with your therapist before trying any of them. 

I have posted this because it is common knowledge that there is a dire unmet need for competent DID therapists. This is true all over the world. Even if one gets past the barrier of being able to find a therapist who acknowledges the validity of DID as a diagnosis in accordance with the DSM, one still has to find a therapist within that group who is willing to work with DID patients, and who has the time as well as the training to do so. These obstacles can sometimes appear to be insurmountable, at least in the short term.

The clear problem facing DID individuals then is what to do in terms of self-care if circumstances dictate a long waiting period to find a therapist. However, we can start with the understanding that even in therapy, self-soothing techniques are complimentary to basic one-on-one psychotherapy. Just as Olympic athletes in training needs to do daily weight-lifting and stretching exercise routines, self-soothing practices should be part of the routine for DID individuals. 

The fundamental point of any self-soothing practice is learning to be kind to yourself. In general, DID individuals are in conflict and pain – often both internally and externally. They generally experience being trapped in a haze of confusion, sometimes with and sometimes without an ongoing conscious awareness of their DID circumstances. They are struggling with the consequence of dissociation. This can show up in the conflicts between the host and some alters, between alters, and with others they encounter in society. There is the ongoing suffering from the pain of early childhood trauma, whether it was physical and/or sexual assault or lack of emotional attachment to the primary care taker.

With DID, just as with any other form of PTSD, one is easily triggered into flashbacks. In a flashback, your body is behaving out of the host’s control. On an ongoing basis, there is likely an accompanying self-destructive behaviour such as substance abuse, eating disorders, and/or attacking one’s own body. 

Substance abuse is related to taking a short-cut, using chemicals for self-soothing as are eating disorders. Repeating self-destructive behaviors has a similar impact and consequence. Unfortunately, these do not fundamentally do anything for your healing. It simply provides a short term impact that creates an ever increasing need for more of whatever substance or conduct is being abused. Relying on this kind of external and negative source of comfort falls short of processing the basic trauma, because it does not empower you.

Without processing the trauma and gaining the self-empowerment that goes along with that processing, one continues to feel empty, weak and passive. There is a loss of personal power, or dis-empowerment, that began with the original early abuse. DID has that component of PTSD which robs the individual of his or her innate basic confidence because the nature of abuse-based dis-empowerment trains you to believe that you will always be a victim, no matter what. This fundamental dis-empowerment needs to be exposed for the lie that it is, a lie told by abusers to further subjugate the abused. 

The basic therapeutic approach to correct this destructive imprint involves re-empowering the DID individual. Positive conduct that promotes the personal power and confidence of someone with DID would be a most beneficial adjunct to the therapeutic goal of processing the trauma.

Is there some basic principle to follow? The answer is yes; definitely yes. Learn to make friends with yourself. This is not a platitude, it is an actual thing to practice. You must learn to be kind to all the parts. That can only happen when you are open to understanding why the different parts may seem to have competing attitudes, agendas, and demands. 

Do practices that strengthen the system as a whole. You are all in that one body together so stay connected and learn to function as a team. Visualize you are like an Olympic team with a distinct common goal in mind. As an Olympic team, you have a target and a purpose, which is to score goals. The target and goal here is to be kind to each other.


## Self-Soothing Techniques for Those Unable to Locate a DID Therapist – Part 2 of 3: Practical Suggestions

*Posted on December 14, 2015*

Here are some suggestions for self-care in practice:

### A. Create Imagery For Yourself That Is A Sanctuary, A Place Of Refuge. {-}

You can easily make your mouth water simply by imagining sucking on a slice of lemon. If you can do that so easily, have confidence that, similarly, you can create a mental image of a safe place where you can rest and recuperate. Begin to heal your wounds by creating that place of refuge where you can allow healing to take place. Do not underestimate the power of suggestion. Here, we are using that power of suggestion to heal ourselves. It is the exact opposite of what abusers do, which is use the power of suggestion coupled with abuse so as to try to deny you this innate ability we all have to heal.

If one breaks a bone, the doctor puts the broken pieces as close together, and immobilizes the injury in a cast. Now the fracture is stabilized with the bones fragments held in place. This allows for the body to go through its non-conceptual and completely natural healing process. The cast is the safe environment which allows your bones to heal together while protecting the injury from further disturbance. 

You don’t have to give instructions to each part of the bone to grow a little this way, a little that way, now join with this other piece and that other piece, and now all of you grow together… The knowledge of that healing is already available to you as a result of having a human body. The job of the doctor is to make sure the bones are close enough together that they will knit strongly and quickly, and that the injured area is protected from breaking again due to external forces during the healing process.

For someone with DID, the same kind of process can be put in place. The parts are brought together in an environment in which they can become close rather than in conflict. Within the visualized place of refuge, they can start to knit together. In that visualized place of refuge, they are protected from re-traumatization, which is the equivalent of a bone breaking again in the previous analogy.

When a child is hurt outside of an abuse context, a protective adult holds the child, soothing her with soft words and reassurance. That nurturing kind of remedy is love in action, highly creative and healing. So, within the place of refuge you have established through imagery, when the protective parts are close enough to hold the frightened ones, the injured ones, the ones that continue to feel torment, self-soothing and healing can take place. 

Healing is best visualized in kinesthetic (sense of touch) terms. Through the sense of touch, one can connect with warmth and security through the imagery of being enclosed and protected in a cocoon. Caterpillars transform into butterflies while protected in the cocoon. Your place of refuge can serve you in that same way.

There are many DID individuals who have expressed positive experiences using a healing blanket, one which is weighted that they feel safe under. To me, this is reminiscent of the circumstances of a fetus in the womb. Before birth, one is protected by the tremendously strong uterine muscles of the mother’s body, floating gently in the warm liquid of the amniotic sac, protected without effort. 

There are both religious and secular imageries that can be used. One should strive for a kinesthetic imagery that creates a physical sensation that is beneficial for the hurt individual or part seeking relief. For patients of mine that were devout Christians, I borrowed the imagery from Jean Vanier that “Prayer is rest; it is to be still, to abide in the presence and in the arms of God, knowing that we are loved just as we are; we are held and safe.” I would literally ask the patient to feel the sense of gentle pressure one experiences while being hugged. For patients of mine that were atheist or agnostic, a similar imagery was used without an anthropomorphic God (God in human form). 

For one patient, the imagery that she found most helpful, i.e. most safe, was to be alone on a tropical island with a white sand beach that was so warm and comforting in the sun while all the while a large thick tropical forest, which started at the edge of the sand, kept anyone else from finding her. She could feel the very fine sand warm against her skin warming her from below and the sun warming her from above. She could smell the ocean and feel its warm breeze.

Use the imagery that is kinesthetic and safe. Religion vs secularism is not the point. Healing the sick is the purpose of psychotherapy so find the safest, most acceptable and effective way for you to re-learn the empowerment of experiencing safety in a place of refuge so that you can heal.

Traumatized individuals often have forgotten what it is like to feel comfortable and secure. So, small step by small step, explore ways to establish the sensorial feeling of comfort and security. There is comfort and pleasure in simply eating a piece of warm buttered toast when you have a cold, or drinking a glass of water when you are parched. In some mindfulness groups, the teacher starts their instruction in class by handing everyone a raisin. Participants are instructed to appreciate the simple sense perceptions connected to that raisin: how it looks, how it feels to the finger tips holding it and the teeth biting it, and how it tastes when it is in your mouth. 

Comfort is usually accessible as we encounter ordinary objects in our everyday life, but we have forgotten about it, or are in such a hurry that we bypass the experience. We need to allow ourselves to re-experience it. I suggest the following simple ways you could try: When you go to sleep, feel the comfort of a warm heavy blanket enveloping you. Re-create the primal environment of the baby floating in the womb. Explore the foetal position when you are in bed and see how comfortable it is when you curl up in that position under the blanket. Don’t tell yourself about it or guess at what it might be like. Instead, actually feel the sensation.

Experiment with physical comfort. A security blanket, literally, is one that is heavy, warm and protective. There is a direct sensation of protection and comfort that happens when you are all nicely wrapped up and tucked in. 

Though your own effort, imagine you are on a beach, a castle at the top of a mountain or in some other place of refuge that you choose. Find and define your safe place wherever you want to nurse your wounds. In that place, re-learn the sense of comfort and security which can be generated in and through your body. You have the power to generate the feeling of comfort and security. Make the time and space to practice doing so.

### B. Stay Connected To Your Body {-}

1. Sunlight – bright light increases the production of serotonin in the body. Spending time in the sunlight can absolutely improve your mood and also soothe muscle aches. Full spectrum lighting can be helpful if you live in areas where there is little sun. 

2. Massage – physical contact from working your muscles stimulates the release of endorphins. Massaging your own scalp and using shower massagers can provide an affordable alternative to expensive treatments. Massage therapy can feel wonderful. 

3. Meditation – meditation helps the nervous system operate at its best. There has been quite a lot of research done to confirm its benefit. There is more about this later. 

4. Physical Exercise – one of the best natural ways to produce serotonin, dopamine and endorphins. Vigorous exercise is best because the stronger the physical demand you place on your body, the greater the release of endorphins. You should try weight training as well as high and low intensity exercises. Work out only for so long as you can based on your capacity at the time. You want exercise to gradually strengthen your body, not to overwhelm it. Engage in regular physical exercise in muscle building, cardiovascular aerobic exercises, and stretching exercises. Learning and practicing yoga and taichi can be very supportive of both the mind and body.

5. Music – music is powerful and can move you emotionally. That is why you can tell what is going to happen in a movie scene based on the music. Good music can absolutely help your mood and get you positively grounded again. Try and listen to mostly upbeat music. Try dancing to it in the safety and privacy of your own home – combining the music with joyful exercise.

6. Laughter – savor the feeling of laughter with friends (or with other alters you might connect with) or watch a good comedy movie. 

7. Sex – is a powerful producer of endorphins. One must be very cautious as it comes with responsibility, obligations and is often connected with dangerous triggers for retraumatization. I may be castigated for suggesting this but, as I suggested in Engaging Multiple Personalities, if sex is important for you, and particularly if you are unattached, the safest sex for healing and grounding may be masturbation.

8. Acupuncture – increases circulation and stimulates the release of endorphins. Of course, one must find a well-trained and capable acupuncturist just like when you look for any other professional.

9. Nourishing Teas – in the absence of diabetes, a warm ginger, honey and lemon tea can make you feel quite nice. 

Remember the general principle that you can gently retrain the body and mind so as to correct the feelings of “I am a powerless victim”, feelings which are inherent in the process leading to DID. A gentle transition through kind and inviting body connections is therapeutic. Do not seek an easy way out that is simply a repetition of the experience of dis-empowerment – such as self medication through drugs, alcohol or other compulsive behaviors. If you feel better physically, through exercise and connectedness, you will gradually enlarge your capacity to work with all the parts as a team, in harmony. Keeping the mind in a creative mode through art music communing with nature and the like are foundations for improving and healing the wounds of DID.

### C. Stay Connected with Others. {-}

Close friends for support are essential in healing. Join an online support network so long as the administrators are properly protective of the members, on guard for individuals who are not there for the purpose of supporting others seeking to heal their DID. Online groups can have a truly positive impact. Active groups usually have people online 24/7 so that if you need to communicate with someone supportive in the middle of the night, it can actually happen. Make sure when joining such as a group, that they require warnings to be posted before writing anything that might be triggering. 

Join a choir if you like music and singing. Join a photography club, a drawing or pottery class if you are artistically inclined. Join a hiking club. Well-defined interest groups are safer and more functional than other social clubs. These amateur groups are usually filled with enthusiastic members and they offer valuable support within the specific interest that can help you build a creative hobby. Connecting with people in such clubs can fill your life with warm memories. 

Altruistic volunteer groups of people who are willing to contribute their spare time for the welfare of others can enrich you life in very meaningful ways. There is nothing more rewarding than to devote time to turn your kindness towards the less fortunate. 

In this vein, remember that spending time with animals can also establish a sense of well-being and non-judgmental connectedness. This is discussed in more detail later on. In short, if you don’t have a pet or cannot afford one, there are always opportunities to help at an animal shelter. Supporting an abandoned or traumatized dog or cat is another way to nurture the strength of your own compassion. Training in that way can also lead to establishing roots of internally focused kindness – toward alters that can help the amnestic barriers slowly and safely begin to dissolve. 

Note that I have not included traditional support groups in this category. That is not to say that they do not have value, and often tremendously positive value. However, one must be careful to keep to the specific purpose of such support groups. Alcoholics Anonymous, Gamblers Anonymous, Narcotics Anonymous and the like all have long and important histories of making real positive differences in the lives of people with those addictions. The very nature of such groups is that the focus is the addiction. Here, I am suggesting connecting with groups where the focus is quite different – not about dealing with a deep problem but instead about singing, art, hiking and so on. 

Please do go to and continue to participate in AA, GA and NA meetings as much and as often as is helpful. Nevertheless, there are predatory individuals that attend such meetings so keep the boundaries quite firm. 
Just as you need to maintain firm boundaries when you might encounter individuals that are triggering, understand that there are reasons protective alters emerge. Respect their intentions always. By maintaining firm boundaries, you let them know that you are giving credence to their assessments. Having done so, invite them to re-assess the individuals periodically. This is a way to gently allow them to moderate the hypervigilance common to protective alters while allowing them to fulfill their protective function.

### D. Being With Animals. {-}

Pet therapy has been extended to help individuals in many ways with many different kinds of difficulties. For example, there are now courts that permit service dogs to support child witnesses testifying about being abused. There are service dogs for the emotionally disabled, just like service dogs for the blind. It is obvious to all, when a service dog, or almost any dog or cat, is brought into a nursing home or old folks’ home, it immediately gently energizes the atmosphere, and brings joy to the residents. Horses have also been incorporated into PTSD therapy.

Pet-Therapy is an encouraging trend.

I have a few colleagues, and am aware of other therapists, that have dogs in their office. One in particular has a three legged dog he rescued from the SPCA. The impact of having that dog in his office has been incredibly effective in communicating to patients that his office is a safe place. Were I to be starting out as a new psychiatrist, rather than being retired as I now am, I would consider having a dog or cat around for my patients.

If you are emotionally traumatized, consider having a service dog. There are substantial costs to get a trained service but tremendous potential benefits. As an alternative, you can go to the local SPCA and claim a rejected and/or traumatized dog. He/she will understand how you feel and will give you years of companionship. It can be a tremendous healing experience. 

A dog is usually quite in tune with how its owner feels. When a stranger appears at the door, the dog will sense how the owner feels about that stranger and behave accordingly, either aggressively defensive or behaving in a warm and friendly way. For those with DID and the deep experience of betrayal trauma, a dog is far more reliable assessor of both your state of mind and that of the other person. Further, from the point of view of protective alters, a dog is far less likely than the host, or another person, to be deceived into betrayal by someone’s surface smile.


## Self-Soothing Techniques for Those Unable to Locate a DID Therapist – Part 3 of 3: Practical Suggestions Continued and Conclusion

*Posted on December 14, 2015*

Part 2 of 3 discusses practical suggestions for self-care. This Part 3 of 3 continues that discussion.

### E. Slowly Engage The Practice Of Mindfulness – Including Walking Meditation {-}

This kind of practice is allowing your mind to become more stable. You begin by holding your spine as straight as you can. You train in focusing on the here and now. The most important thing is to accept yourself and simply start taking one breath at a time. Do not congratulate yourself when your mind seems calm just as you shouldn’t get annoyed and scold yourself if you drift off course. It is the nature of mind that we keep drifting off the course in meditation. The practice is to always come back to the here an now when you notice that drift. 

*Begin with very short sessions*. Do not aim for even 10 minutes to start with. Aim for doing it during the time that you are taking just one breath. Then do another breath. You can just start with 1 breath as the entire session until you feel at ease. 

Ordinarily, our mind is always chattering and full of distractions. When you can stop this chattering, even for a split second, or the time it takes to breath in, you are into the practice of meditation – paying attention to the reality of the now. This is no mean feat. It may seem like a drop in the bucket, but the ocean itself is made up of water droplets.

I suggested very short sessions for a reason, a warning. As always, one must be aware of the very real risks of re-traumatization. For individuals with DID, sometimes creating that little space results in the alters seeing it as the opportunity to emerge uncontrollably, flooding you with their many separate agendas. These usually include retraumatizing flashbacks.

While taking one breath alone is unlikely to provoke an immediate flood, please check yourself. If you begin to feel the flooding of a flashback starting, stop the mindfulness practice by moving your body. Stand up from your seat. Stretch your arms fully. Straighten your legs completely. Identify the room you are in right now. Perhaps start your journaling ritual (see below) and allow some communication to happen in that way.

Go back to the mindfulness practice the next day, but don’t try to just jump back in trying to extend the duration of the practice. Always check your sense of safety first. Take this approach until your mindfulness practice is stable enough to allow thoughts to arise without the retraumatizing flooding of flashbacks.

When your mind begins to stabilize, you start to be aware earlier on and ever earlier on in the flashback cycle. The sooner you see the cycle start, the easier it is to ground yourself and avoid retraumatization. Consider how much easier it is to stop a car going 5 miles an hour than a car going 100 miles an hour. In that same way, grounding yourself at an ever-earlier stage of a flashback cycle is far easier than trying to put the brakes on a full-blown flashback.

Remember to take baby steps: Connecting to the safety of the here and now for even a fraction of an in-breath is better than just digging into flashbacks and being trapped in the retraumatization cycle. 

### F. Establish Empowering Rituals. {-}

We can make a positive ritual out of a simple sequence of thought and/or conduct so that it is turned into a daily habit. It only takes repetition to build a habit and a routine – good or bad. So, take the steps necessary to build a positive empowering habit. 

We all already have a routine when we get up in the morning and one before retiring at night. We have already ritualized and habituated ourselves to these routines. So, we do not have to struggle thinking about them. Build into this existing habit the focus of learning to feel safe and secure.

For example when you wash, at the sink or in the shower, imagine that you are not just washing the day’s dirt off your hands and face, but that you are washing down the drain the feelings you might have of having been dirtied by abuse. When you wash your hair in the shower, as you rinse out the shampoo, imagine that all of the physical and psychological dirt along with the sense of being soiled, simply goes down the drain. Imagine that you leave the shower both physically and, even just a little bit, psychologically cleaner than when you entered. You can extend this into brushing your teeth and other ordinary cleaning activities.

I often encouraged my DID patients to establish a clear ritual for safe communication with and between alters by ongoing journaling. In essence, it is creating a form that is empowering because it is within your control. Pick a book to write in that is only for this purpose. Establish a place and regular time to journal. It can be used for meetings of all the parts, it can be used for parts to leave messages for other parts, it can be one of your places of refuge. Always begin with some grounding exercise(s), open the journal, allow everyone inside that wishes to say something to do so by writing in the journal. In that way, communications from different parts can be shared with the host and other alters.

A critical point of this approach is to authorize the closing of the journal if things become triggering. In such circumstances, close the journal in accordance with the ritual you have established, with the express intention of allowing what has been raised to be processed. Include the promise of allowing further journaling on that triggering issue as soon as the system is able to process it. Then, and most important, following closing of the journal and always putting it away in its designated place, do a closing grounding exercise. 

Often, the best grounding following journaling is to go for a walk outside. When walking, keep your senses as open as possible to the air that you breathe, to the trees you walk by, to the stability of the earth that you walk on. The earth, in particular, has the capacity to ground the energy the journaling has generated, in the same way that when you connect a lightning rod to the earth, the lightning’s electricity is safely absorbed.

**Concluding Remarks**

All healing that is effective has to come through one’s own effort. So, consider working on self-soothing practices before you have a therapist. The more you participate in such practices, the more effective and self-empowering is the healing. This way, when you are able to connect with a therapist, you will have already started to build a strong foundation for the therapist to support your continuing healing journey.

All the above may be used as complementary tasks for healing even after you have found a therapist, but make sure you tell the therapist what you have been doing in terms of self-care. It is an opportunity to assess the therapist and for the therapist to assess you – and for the therapist to give you further direct guidance for self-care. 

None of these self-soothing approaches are a panacea, a cure-all. They are merely, but potentially powerfully, supportive of the overall healing process. Remember that DID is not the pathology, it is the resultant display of extreme trauma. Its manifestation in alters is the message, the instant emoticon you could say, that there is deep unprocessed trauma. In my opinion, the problem is not the alters. It is the amnestic barriers and the resulting internal conflicts, which get played out both internally and externally, that are the problem. 

Above all, understand that healing is possible and is within your capacity.


## Anxiety and Panic Disorders

*Posted on June 27, 2016*

If we suddenly encounter a danger or a threat, we will fight, try to get away or be in such fear that we are immobilized and freeze. The fight, flight or freeze responses are daily experiences in the animal world. A gazelle lives its life grazing in the field and propagating for species survival, while simultaneously being on the alert for predators. Anxiety is an alarm system to keep an animal on its toes, to maintain a look-out for possible life threatening danger. The nervous system is fine-tuned to anticipate danger or threat so that there is time to escape danger. 

These responses are normal in the human condition. Something may trigger our alarm system and we are thrown into the emergency alert mode. If the internal alarm goes off when there is no obvious danger or threat, how does one handle this internal warning? You really cannot completely ignore it. You will try to find an explanation to account for it. Your mind may start building up a scenario to account for such fear and anxiety. It may be a subliminal flashback of memory that is the trigger. 

More fear will feed on that initial intangible fear, and perhaps a bodily sensation gets misinterpreted. The alarm system will convince you that something is wrong, that there is still danger. And then, you get into a full response mode of fight, flight or freeze. Even if we are getting a clearly false signal of impending danger, we may have already set into motion those patterns of getting ready to fight, running away, or becoming frozen with fear. This is a primitive reaction that is in our genes. It is a reaction cycle that kept our ancestors alive for tens of thousands of years. 

The problem is that this kind of response behavior is *usually* no longer adaptive for survival in modern life. In most cases we do not have a natural predator lurking behind the tall bushes in the park to prey on us. However, as is clear from the statistics on early childhood abuse, there are predators out there, sometimes in the child’s own home. In later life, if some past trauma for which our body has been keeping the score raises its ugly head as a fragment of implicit memory, we receive the same alarm signal warning us of possible life-threatening predatory danger.

Traumatic memory does not function like narrative memory in our ordinary life, like remembering coffee yesterday with a friend. Traumatic memory is often cued by sights, smells, tastes and the feeling tone in an environment. The memory often arises in a pre-verbal way. So, not conceptually remembering the specific trauma doesn’t mean that we have not experienced it, nor does it mean that we don’t carry that trauma in our mindstream. 

Therapists in clinical practice see that anxiety comes in all forms. The purest form is anxiety that emerges seemingly out of the blue, without an identifiable reason. When a person reacts to a small triggering sensation, often without even identifying the sensation, the associated traumatic memory of fear itself will emerge quickly into a full blown panic. The sensation can be as small as the tinge of an odor similar to one that was experienced in trauma, or the passing twinge of a painful sensation. The mind is brought back to a danger of the past. The entire body shifts into “battle station” mode. It is not that one is not afraid of something unknown, rather one is on the lookout for something familiarly frightening.

It is very instructive for a therapist to watch anxiety developing right in front of them. I have had the experience of watching a patient developing a panic attack right in front of me in a hospital when I was the psychiatrist on call one night. While remembering that  any physical discomfort or symptom such as chest pain may actually have a real pathological rather than psychological basis – which will be left to the Emergency staff physician to handle – but with respect to a possible psychologically based anxiety attack, there are a series of steps for the therapist to take.

1. The first thing is to convey to the patient of your empathic understanding of the magnitude of fear the patient is experiencing. The worst thing is to make light of the patient’s panic, saying that there is really nothing to worry about. 

2. Once you have their confidence, you will have to ascertain that the condition is really a panic disorder, not some physical problem that mimics a panic attack. 

3. The preferred treatment depends on the orientation of the physician as well as the time available. In my experience, the efficacy of medication is uncertain. I believe the effects are often largely a matter of how much the patient trusts the therapist. In purely relying on the pharmaceutical effect, one runs into the danger of having to use a colossal dose to suppress the physiological arousal of a panic attack. At best, medication is useful as a short-term temporary intervention.

Panic disorders are related to the patient feeling loss of control over his/her bodily power. I characterize it as a disorder of "dis-empowerment." The patient is thinking, "Why is my heart racing so fast when I am sitting down, not even walking." He/she does not realize it is the response reaction that has spun out of control, with the mind and body setting itself up in preparation for dealing with some as yet unseen but monumental threat. Whether that threat is a present danger or artifact from the past, the physical response is entirely understandable and beyond self-control.

The test of the therapist’s skill is how to suggest or assist the patient in reversing that escalating panic response. Stopping something when it is already in motion is very hard. For example, if a car is moving at 100 miles per hour, and the driver’s foot is pressed down on the accelerator, it is exceedingly difficult to stop the car. The first thing to do is to let him/her  regain confidence that the car is still controllable. It is easier to let the person continue speeding while gently steering it in a different direction, perhaps up a hill, rather than insisting to the person that they get their foot off of the accelerator and stop short. The patient is already overwhelmed by the intensity of the panic, it is impossible for them to stop doing whatever their body response dictates.

Remember the analogy of heading the speeding car uphill. Highways that run through mountains have special lanes for runaway trucks with failed brakes – they exit from the main road and head up a hill so that gravity, that invisible hand, acts as an environmental brake. How can a therapist use this analogy? Redirect the patient’s energy rather than confront it. Focus attention onto something for the patient to do that is not connected with denying the panic. There is the well known “Brown Paper Bag” method. This invites the patient to breathe in and out of a brown paper bag. I know of many patients who have successfully used this method. In fact, some carry a brown paper bag with them in case the panic returns.

The paper bag method is so simple. It is not asserting anything about the panic being correct or imaginary, therefore there is usually no obstacle to doing it. When someone is in a panic, the natural tendency is to “do something.” Just as with grounding exercises, this method fits into that protocol every well.

The reason it works is psychological, not physiological. Blowing into a paper bag is a simple task. The mind and body are engaged in a task. Through that engagement, the mind and body energies are redirected rather than suppressed. 

There is another reason I like this method. It is because it is something the patient does which leads out of the panic. That is what counts. The best treatment is one that patients can do on their own, which engenders the confidence that they can control their bodily functions. This is re-empowerment.

Most psychiatrists advocate relaxation as the central focus in psychotherapy. This is difficult to apply, and generally not possible in the  midst of a panic attack. To ask a patient to try to relax during a panic attack is like saying to a drowning man, "Relax, your body will naturally float." It doesn’t work. 

There is a proper time and place for discussion of the patient’s fears, whether they are seen as rational or irrational, but it is not during an attack. The cognitive or rational-emotive approach is appropriate only later, in the context of a supportive therapeutic relationship and environment. For example, a behavioral approach emphasizing graduated exposure to panic-inducing situations is only appropriate after the patient is taught methods of regaining self-control, that he is again the master of his body. 

I do not have confidence in the long-term benefits of the text book treatment of panic attack such as: 

* Carrying items such as medication, water or a cell phone 

* Having a companion (e.g. a family member or friend) accompany them places 

* Avoiding physical activities (e.g. exercising, sex) that might trigger panic-like feelings 

* Avoiding certain foods (e.g. spicy dishes) or beverages (e.g. caffeine, alcohol) because they might trigger panic-like symptoms 

* Sitting near exits of a room. 

All of these may be helpful short-term supports but they generally involve increasing the dependency of the patients, confirming that they are helpless and remain unprepared for the next onslaught of panic. These methods are not based on, nor will they result in, re-empowering the patients.

I have practiced slow breathing long enough to be able to hold my breath for about 2 minutes. Given that, I was able to show and reassure my patients that it is quite safe to not breathe for 15 seconds. Then all I asked them to do is to slow down their breaths to say 4 times a minute. Once they were willing to try to slow down their breathing, even just by counting to 10 between each inhalation and exhalation, their panic dissipated.

No one can sustain panic when the breath is slowed down. The usual difficulty is convincing a patient to slow down their breath because they all feel they are struggling for air. By having them breathe along with me, they can see that they are able to work with their own breath. Then, they do it themselves. Once this is accomplished, the panic will usually not return in that intensity, and the patient will not become dependent on medication for anxiety.

After the panic is under control, find out what else needs attention. Is there past trauma? Is the current life-situation full of difficulties? Tell your therapist. In the absence of a therapist, or if you have yet to establish a safe therapeutic relationship, tell yourself by writing into your diary. Putting your troubles into words is always better than just stewing about it. In writing, it becomes something tangible with boundaries that can be worked with. Too much thinking often becomes a fruitless exercise – like a dog chasing its own tail. 

Panic disorders are not something that you need to find a magic pill to cure. Even if there is such a pill, it will only work temporarily. I am generally against giving pills for this because on the one hand, they may not work and on the other hand, they most certainly will not re-empower you. Grounding exercises are critical for a patient’s re-empowerment. Practice them regularly before a panic attack arises so that you develop a personal panic toolbox to keep you centered in the present moment.

Panic attacks are self-perpetuating, tail-chasing, vicious cycles that distract us. What do they distract us from? Usually, they keep us from getting near a deep unhealed wound. A bacterial infection needs an antibiotic for healing, but panic attacks are not caused by an external agent like a bacteria. To eliminate a panic attack, one needs an inoculation of the present moment’s safety. Grounding is that specific inoculation.

Panic may be your body telling you that there is danger or that something needs to be fixed. Take heed of its warning—use your time and energy to deal with the real issue, rather than seeking a medication to suppress the alarm signal. If you cannot yet find the reason for your fear, through grounding, you have at least found a way to control your body, to re-own it again.

A famous psychotherapist in the mid 20th century, Frieda Fromm-Reichmann, wrote about a man, probably not her patient, who was suffering from severe anxiety. He underwent in-depth psychoanalysis. In this case, there was a real yet seemingly unrecognized reason for the anxiety, even though he was then at the peak of his wealth/fame/family bliss. Soon after he was “cured”, the Nazis took over and he was taken to the concentration camp to be exterminated. 

There is an important lesson in this: Anxiety, like depression, is not always a symptom to be eliminated. Don’t limit your focus in therapy to turning off the alarm. Check to make sure whether or not the alarm signal is correctly assessing a present danger.


## When You Don’t Want to Leave Your Therapist

*Posted on December 18, 2016*

In general, therapists and clients have an extraordinary relationship. While therapists make their living by providing therapy services, their relationship with clients must be genuine, congruent and empathic to be effective. It is not the same as having a conventional or ordinary close friendship because the trust and power dynamics are neither conventional nor ordinary.

Naturally, some alters, particularly the young ones, want to cling on to the relationship with their therapist after termination of therapy. This is true whether it is the end of a single session or the end of therapy completely. This is an important issue in the therapeutic relationship. Expressing the confidence and willingness to be there for the next session is something a therapist commonly does to encourage and support the client in ongoing therapy. It is saying that the relationship is not over – just the session. This is quite different from ending the therapeutic relationship. This is something I dealt with in preparing my patients for my retirement a decade ago. I took a year to help prepare them for that transition.

Clients often see their therapist as a particular *kind* of a close friend: One willing to communicate confidentially about the client’s personal history for the sole purpose of helping them heal from trauma. It is someone with whom clients can talk about issues and histories that are not so safe for them to communicate about outside of the therapeutic environment. So, even thought the therapist/client relationship is based on payment for services, it is also like the best part of a friend who gives you their undivided attention. They give that undivided attention for an hour every week or 2 weeks. This is different than an ordinary friendship, no matter how genuine.

In normal personal relationships, you choose your friends based on certain qualities that appeal to you, whether he/she is funny, handsome or smart, etc. There is an expectation of sharing information about one’s life, more or less deeply depending on the depth of the friendship. Change and growth are implicitly expected in any relationship, but in a therapeutic relationship that expectation is solely about the change, growth and healing of the client.

Therapists don’t choose patients in the same way they choose their friends, such as common interests, social circles, and the like. They treat the individuals that come into their office, whether or not they have friends, hobbies or other things in common. Unless there are exceptional circumstances, the therapist takes whoever comes into their office needing his/her service. It is important to understand that your therapist-friend has problems of his or her own, but, unlike a conventional friendship, he does not share them with you. He maintains this boundary in order to ensure that he is there solely for your needs, not his own. Your therapist has to keep his problems to himself in order to properly be there for you.

Deep down, the therapist treating DID is often providing a corrective parenting experience offered in the safety of a therapeutic relationship to support the client processing past trauma. What is a corrective parenting experience? It is being there for someone when they are hurt, reassuring them of their basic goodness and helping them feel better. For example, when a child falls down and scrapes their knee, a proper parental response would be picking up the child, looking at the injury, assessing it and either getting the child medical treatment or reassuring them that the injury will heal without much of a problem. In other words, providing comfort and safety.  A traumatizing parental response would be something belittling, mean. It would be using the incident as an excuse to further crush the child’s self-esteem and sense of safety by eliminating the idea that the parent will ever serve as the child’s adult protector in the world.

There is a risk that the young alters in particular will not understand that the therapist providing a corrective parental experience is *not* the same as the therapist becoming a replacement parent. This is something the therapist must gently and consistently clarify for the client.

After termination of therapy, there is no legal requirement that there be a complete cessation of contact. However, for ethical and genuinely therapeutic reasons, it is risky and inappropriate for the therapist to engage in a direct relationship of friendship with a former client. The power dynamic inherent in the original relationship will not disappear. Further, and critically important, is the fact that should the client need therapeutic assistance in the future, a direct relationship of friendship will cut off that possibility.

It might be OK if the client wishes to send their former therapist an occasional greeting card. Sometimes that may be done *by the client* in order to leave open the possibility of returning to therapy with the original therapist. In fact, one of my patients continued for years to send the occasional brief letter to my secretary to maintain some continuity with my office. in my experience, maintaining that boundary is important for the well-being of the (former) client. It is my view that when the client finishes with therapy, it is important that he/she feels the improvement is based on their own efforts, rather than something to be credited to me. It is their successful processing of the past trauma, their survival, that is the point – not my achievement. If they can move on in life without further therapy, it is all for the better.

This is very difficult for some of the alters to understand, particularly when they remain infantile or of very young age. This does highlight another question, whether or not young alters grow and mature in their age during therapy. As is shown in some of my other writings, integration is not necessarily the goal. If the alters integrate, and their age approximates that of the body’s chronological age, that is fine. But, in my opinion, the most important mark of successful DID therapy is that the conflicts among alters are resolved so that they are working together rather than at cross-purposes based on unprocessed trauma.

This answer will not satisfy all, especially those who remain having young alters in their system. There are really no comforting words that are guaranteed to reassure a group of children (in DID – the young alters) when we take away their caregiver (in DID – the therapist) and say everything is OK. It doesn’t work for a child traumatized and separated from their loving parent as a result of worldly circumstances like illness or war, and it doesn’t work for a DID system traumatized in the past and now separating from their therapist.

However, one can give them all confidence in their ability to continue on their healing journey. That is part of the preparation work, prior to termination of therapy, that I tried to do for all of my patients. Perhaps some of the adult alters in the DID system can take over some parenting function transferred from the therapist. Perhaps the alters can become really good friends inside, supporting and mentoring each other. Perhaps the system can become more firmly established in their self-care and grounding exercises. The best reminder for the system is that all the parts are there for a reason so be kind to everyone inside, always be kind.


## Anxiety – Part 1: Symptom and Message

*Posted on March 29, 2017*

In a psychiatric practice, anxiety is the most common complaint among patients. But consider how common it is that a psychiatrist facing an anxious patient immediately concludes that the patient is suffering from “Anxiety Disorder” and simply prescribes a pill for the anxiety. The same holds true with patients complaining of depression. No wonder that a consensus is slowly building everywhere but in the pharmaceutical industry that there is an alarming number of North Americans – men, women and children – are over-medicated for pain, anxiety, or depression.

In an ordinary medical practice, pain is the most common complaint among patients seeing their family doctor. For example, when hearing a complaint of pain in the stomach area, the doctor first tries to find out a little more about the pain before making a diagnosis. The doctor will ask if the pain is acute, chronic, triggered by a particular movement or food, whether it hurts when it is pressed here rather than there, and so on. Only after the analysis concerning the source of the pain is made would a diagnosis be made and an analgesic (a pain killer) be prescribed. 
Just as many cases of pain can be traced to bad posture, lack of exercise, and lack of mobility in the elderly, many cases of anxiety and depression can be traced to very real experiences of deep trauma. 

Life is filled with mixtures of joy and sadness, carefree laughter and deep worries. Joy and laughter are seldom experienced as a problem. But when something in the environment triggers your internal alarm system, you will start worrying. Worrying is not per se a bad thing. It can be helpful in deciding to focus your energy in preparation for a task at hand, for problem solving or securing a level of certainty. However, when worry becomes one’s normal state of being, it becomes difficult to control. It can result in persistent anxiety, loss of sleep and/or raising blood pressure. When worry becomes ongoing anxiety, inappropriate or disproportionate to the object of concern, it is no longer helpful. 

Clearly, not all worrying is pathological. For instance, if your teenage son is going out for a casual ride but you suspect that the driver has had a couple of beers, then your worry is perfectly justified. It is an alarm bell going off that is to be taken seriously. But once we have done the necessary scrutinizing of a situation, and ensured that reasonable actions have been taken, worrying is a waste of energy. If that worrying continues to the point of paralysis, it then fits into the psychiatric category of an Anxiety Disorder. 

The next question needs to be asked though, “Does that mean that drugs are necessarily the best treatment?” One argument against pharmacological treatment is that while drugs can ease your mental tension, they may also take away the ability to encourage yourself to practice self-regulation while potentially leading you down the path of chemical dependency. Being trained to deal with tension via a quick chemical fix is not particularly that far from the entryway of addiction. In the long run, is this beneficial for you? It is my view that as therapists, we should be encouraging patients to engage in correcting and refining the balance of their internal alarm system through therapy that may include medication as an adjunct but not the sole treatment. 

Life is full of obstacles past, present and future. One must beware of relying solely on drugs to protect you. Relying on a drug that helps, without embarking on the necessary internal re-calibration work of psychotherapy, is a mistake. Why? Because you have not used the situation to learn about the root causes of your difficulties in dealing with the obstacles you face. This leads to the ongoing undermining of your own sense of self-empowerment.

If you visit your family doctor because of a pain in your right shoulder, I certainly hope the doctor does not say, “We will open up your shoulder and take out whatever is bothering you.” No, you want the doctor to ask more questions, to further examine the shoulder, and order some tests to find out the real pathology. Shoulder pain can be what is called “referred pain” which can indicate potential pathologies as diverse as abdominal, pelvic, heart and lung problems as well as, of course, a strain or tear in the shoulder muscles. In a similar way, simply treating anxiety or depression without identifying the actual illness or circumstances causing those symptoms is at best lazy medicine and, unfortunately, has the capacity to be far worse.


## Anxiety – Part 2: Patterns and Recommendations

*Posted on March 29, 2017*

In psychiatry, just as in any other branch of medicine, the real cause of a symptom may be hidden from the patient, the doctor or both. In psychiatry, the root causes of disorders are often unintentionally hidden because of internal conflicts that are submerged below one’s consciousness. We all have experienced worrying about one thing only to eventually discover that the real issue is something quite different.

1. Anxiety may be caused by a taboo subject we simply cannot or do not wish to face.For example, a young woman married to an abusive man may not consider divorce an option, will not even see it as a possibility. Sometimes that is because there are children involved, sometimes it is because of financial circumstances or religious teachings. Such a person coming to a therapist for help presenting a variety of anxieties and depressive symptoms may never mention the domestic violence – even though it is the core issue. It behooves the therapist to exercise their sensitive radar to clue in because direct questioning will often elicit a simple negative answer resulting in everyone involved heading down the garden path of deception. 

2. Anxiety often creates other symptoms in order to create a distraction that can lead both the patient and therapist on a wild-goose chase. For example, a sore back, a stiff neck or a splitting headache or compulsively cleaning at a specific time late each evening may be the complaint. Focusing on the distractions soon turns the distraction into a real problem that even more strongly leads away from the root issues.

3. Anxiety is characterized by a state of helplessness, of complete loss of self-control. Typical examples include, "I cannot breathe" in a panic attack as well as "I can’t sleep" in insomnia. Normally breathing and sleeping are part of the effortless behavior pattern of a living being. The anxiety is interrupting the basic human operating systems.

4. Anxiety leads to cognitive distortions. Even doctors have anxiety/depression. I know of a doctor, a specialist, who in the depth of his depression, without any reason, worried that no one would come to see him in his practice when in reality, the usual waiting time to see him was 6 months.

### Key Remedies to Consider:

#### 1. Come back to the present. {-}

For runaway anxiety such as panic attacks, the first thing to do is to bring oneself back to the present moment. That is empowerment. In other words, don’t fight the panic in your mind: Reassert control over your physiological response to the thoughts. How to do this? Well, the most common complaint in anxiety attacks is "I cannot breathe." Under the circumstances, until the patient is able to do this alone, the therapist will have to strongly take over and direct the patient to breathe SLOWLY. I would reassure my patients that it is safe to regain the control by holding the breath for ten seconds. I would tell them that even at my age, I could still hold my breath for one minute without causing any harm to my body. That usually caught their attention. By seeing that it was harmless for me to hold my breath for 1 minute, they were reassured that holding their breath for 10 seconds would not hurt them. Once they had intentionally slowed down their breathing, they generally felt re-empowered, back in control of their most basic body function. This was simple, immediate, effective and *within their capacity*. The fact that I was willing to throw myself into their fearful experience reassured them that I was taking their concern seriously, not casually dismissing their complaints as trivial.

#### 2. Learn how to worry constructively {-}

Some worries are necessary while others are not. Let us call one group “constructive” and the other “destructive.” First, we need to learn to distinguish between the two. The reason we usually cannot separate one from the other, leading to the paralysis of anxiety disorder, is that we are too emotionally involved with the subject of our worry. Effectively, we are talking about correcting cognitive distortion. 
Destructive worrying is worry that entraps one onto a vicious self-perpetuating cycle. The resultant worry feeds into whatever is causing the worrying making it worse, creating a sense of loss of control or “dis-empowerment.” There are usually two internally opposing voices at work. One tells you that your worrying is justified. The other says that you are just worrying too much, that you should not be worrying. Constructive worrying enables you to consider the issues without entrapping yourself in a vicious self-perpetuating cycle. 

How can we determine whether or not our worry is constructive? A patient came to see me once for anxiety issues. I applied the paradoxical intention concept from Victor Frankl’s Logotherapy approach. I asked my patient to sit still for a few minutes to prepare himself, organize his thoughts and review what was bothering him, before telling me all the things that were bothering him. In other words, I was asking him to worry without trying to fight it. 

As a result of my request, he gave himself permission to worry. He sat down and focused on the internal turmoil without worrying about his worrying. When he was sitting and reviewing what he was supposed to be worrying about without that self-criticism, he was able to process his situation without further outside input. After a few minutes, to my surprise, he opened his eyes and said that what he was worrying turned out to be of no real significance. He did not even need to tell me! His body language confirmed it.

Be very clear about your non-verbal language as a therapist because it carries a lot of weight – often more weight than the spoken word. It was clear to my patient both verbally and non-verbally that I took his complaint seriously and respectfully, rather than being dismissive of his worries.


## Anxiety – Part 3 Meditating on Anxiety

*Posted on March 29, 2017*

Sanjay Gupta, the CNN Chief Medical Correspondent who is also a neurosurgeon, [documented the personal instructions on meditation that Dalai Lama gave to him](http://www.cnn.com/2017/02/15/health/sanjay-gupta-dalai-lama-meditation/?ref=yfp). The Dalai Lama taught him to meditate by focusing on his worry while imagining isolating it in a bubble. He did this as a daily practice of meditation for a few months and vouched for it having changed his life in a significant way. By putting his worries in a bubble, he allowed himself to worry, but in a way that did not generate a vicious self-perpetuating cycle. With this approach, the worry does not get worse. It can either stay the same or get better. If the worry is inappropriate or disproportionate, it will not only get better by having you see it in a more reality based perspective.

One of the worst aspects of anxiety is that it has an all-pervasive quality. So-called “free-floating anxiety” is everywhere which means that one can find it hard to pin-point anything about it. What I sometimes asked my patients to do was to use their imagination to put the anxiety onto some part of their body, such as the chest, or their abdomen. It is like finding a location or a point that enabled them to keep the anxiety in one place. I suggested that they continue, gently but steadfastly, to focus on this point, to look at it and feel it. I encouraged them to keep returning to it if their mind wandered off. I sometimes asked them to move the anxiety just a bit with their breathing; an inch here or there.  

Once you’ve localized some anxiety, just breathe and feel it. Treat it like your friend, stay with it through thick or thin. You can even begin to play with it!

Keep breathing, and keep practicing just accepting this feeling of anxiety – kind of like accepting the feeling of the weight of your pillow on your abdomen. If the sensation of anxiety starts to fade, bring it back and accept it. Simply stay with the anxiety instead of trying to get rid of it or fight with it. Treat it as your friend. Eventually, almost everyone ends up having difficulty maintaining the anxiety. 

Call it whatever name you like. Some call it “paradoxical intention”, some call it “reverse psychology, some call it “mindfulness practice”. Whatever you call it, it is a way to empower yourself to work with anxiety rather than being disabled by it.

I do not rule out that in special circumstances, medicine may still be justified. However, it must not be given without considering all the alternatives – including using medication as a support for the kinds of self-empowering practices described previously in Part 1 and 2. It is far better to begin to learn how to heal yourself rather than giving up the autonomy which is your own power, and blindly trusting chemicals alone. 


## How To Worry Constructively – Part 1

*Posted on April 13, 2017*

In life, one experiences alternating and sometimes mixed emotions of joy and sadness as well as of carefree laughter and deep frowning concerns. While joy and laughter are seldom experienced as problems, when something in your environment triggers an internal alarm, you will start to worry. Worrying can encourage you to focus energy for a task at hand, in problem solving, or in securing a needed level of certainty. However, when worry gets out of control and results in persistent anxiety, loss of sleep and/or ongoing increased blood pressure, it is no longer helpful. At such a point, it no longer helps you achieve a goal. Instead, it self-perpetuates in a seemingly endless loop of stress. 

Nowadays, there is a tendency to see every ordinary emotional up and down as a kind of pathological disorder in need of treatment. If you present concerns about your emotions to a busy doctor, it is likely that a magic pill will be prescribed “to take the edge off” whatever worries you.

In DID, worrying can transform into an almost perpetual anxiety, which may then get taken to the extreme of crippling hyper-vigilance. Psycho-active medications can be very helpful when worrying has become incapacitating anxiety. Nevertheless, thoughtlessly employing medication may mean that we miss out on opportunities to mature, to grow stronger and to become more self-reliant. My recommendation was always to include psychotherapy as part of any regimen that included psycho-pharmaceuticals.

But, are all kinds of worrying pathological? No.

If your teenager is going out with friends, you may worry and automatically look for specific danger signals. If the driver has had a couple of beers, then your worry crystallizes – you identified a true predictor of the risk of catastrophe. You may need to actively intervene as a result of this clear and present danger. 

Your worry in that example is clearly not pathological. It is a sane response to evaluate known risks of danger. Once we have scrutinized the situation, and ensured that the driver is not drinking then the worry has resulted in reasonable actions of protection. At that point, continuing to worry is a waste of energy.

Having taken reasonable precautions, remaining paralyzed with disabling worries fits into the psychiatric category of “Anxiety Disorder.” If that is the case, then yes, you have an Anxiety Disorder. This leads to follow-up questions, “Are drugs the only treatment? Are they necessary?”

When necessary, I sometimes prescribed medication *but only as an adjunct to psychotherapy*. A principal argument against pharmacological treatment alone is that while drugs can ease your mental tension for a short period of time, they take away your autonomy and the possibility of self-empowerment. Taken alone, medications can lead you down the path of chemical dependency.

Training yourself to deal with tension solely with medication does not allow for correcting and refining the balance of your innate alarm system or for modulating your responses to those alarms as appropriate. For example, if you hear a car horn honk some distance away, you notice the sound and scan to identify what is going on. You do not jump and run in a panic. If you are jay-walking and you hear a car horn honk very close, then the appropriate response may indeed be to jump and run out of the way.

Life is full of obstacles for everyone. You will likely meet situations in the future that are similar to what is triggering the anxiety. Relying solely on medication without embarking on the necessary internal re-calibration work of psychotherapy, brings only an even stronger reliance on the drug! It is like starting on sleeping pills to put you back to normal sleeping pattern. Once you find them helpful, you start worrying that you will need them again. But this time the worry is truly justified! Why? Because you have not used the situation to learn about and process the root causes of the obstacle you face. This is the task, this is the essence of the healing journey.


## How To Worry Constructively – Part 2

*Posted on April 13, 2017*

It is clear that some worries are helpful while others are not. Let’s call the first group “constructive” and the second “destructive.” When worrying is helpful, justified in the circumstances, it is constructive. When worrying is not helpful, not justified in the circumstances, it is destructive. 

We often cannot separate one from the other. But, we need to distinguish them for our own well-being. So, it is important to learn how to determine whether or not our worry is constructive. 

When a patient came to see me about his paralyzing anxiety, I applied the paradoxical intention concept as used in logotherapy, developed by Victor Frankl. I asked him to sit still for a few minutes before telling me all the things that were bothering him. I asked him to prepare himself by organizing his thoughts and reviewing what was bothering him. In other words, I was asking him to allow his worrying to come out without contesting it. 
When a patient came to see me about his paralyzing anxiety, I applied the paradoxical intention concept as used in logotherapy, developed by Victor Frankl. I asked him to sit still for a few minutes before telling me all the things that were bothering him. I asked him to prepare himself by organizing his thoughts and reviewing what was bothering him. In other words, I was asking him to allow his worrying to come out without contesting it. 
As a result of my request, he gave himself permission to worry. First, appearing somewhat subdued and dull, he sat down. Then, he focused on the issues of concern without the internal turmoil of worrying about the fact that he was worrying. After a few minutes, he opened his eyes and said that what he was worrying about turned out to be of no real significance. To my surprise, he did not even think he needed to tell me about it further! His body language clearly indicated that his mind was lighter, unburdened by the anxiety. Simply allowing his worry to come out in a safe environment had empowered him to solve his difficulty with no other assistance.

Mind you, there were important factors at work in the interaction. Remember, the therapist’s communication in non-verbal language way can carry as much weight, if not more, than the spoken word. So, my body language and verbal communication were in accord with each other – entirely respectful, rather than being dismissive of his concern. It was clear that I took his complaint seriously. 

My interpretation of this event was that when he was encouraged to go ahead and explore his concerns in a safe and nurturing environment, he was free from the paralysis of being unable to determine whether he should or should not worry. Without that internal tug of war, without that self-criticism, he was able to focus on and process his concerns without getting in his own way.


## Working with Self-Victimization

*Posted on April 17, 2017*

I received a request from a reader about a major issue encountered by many with DID, self-victimization. In my experience treating DID patients, self-victimization and self-harm seemed to be the rule rather than the exception.

Survivors of early childhood abuse often get attached to successive abusive partners, one after another. It is one of the most unfortunate aspects of the abuse cycle that one goes out to search for an abuser to complete the abuser-victim transaction sketched out in the Karpman Triangle (also known as the Drama Triangle) of the abuser-victim-rescuer socio-gram. Survivors also have similar dynamics within their systems, with different alters playing out similar roles on the inside.

This happens for a variety of reasons, with many different excuses and rationalizations. But rather than respond to the internal logic (or lack of understandable external logic) in the self-harming conduct with arguments, the key point to understand is that healing arises from connecting directly with the alters who are willing to engage, and warmly/gently/kindly inviting others to try to engage.

What does that actually mean? Whether you are seeing a therapist or you have an alter within the system helping out, patiently connecting with a punitive alter (or alters) who wants to inflict pain is critical. Honestly generating empathy for that angry punishing later is key – faking empathy will make things worse. You can generate real empathy by remembering that such alters arose for the same reasons that every other one did – dealing with the direct impact and aftereffects of horrific trauma.
Begin by telling him/her that you understand the feelings of anger, desperation and pain. Be honest if you don’t understand the self-victimization. In that case, you can ask for guidance on how you can better understand his/her view. Gently suggest that the trauma is in the past, but do so by encouraging the alter’s connections with the present. It can be done by identifying the current date. If you are not in the area where the abuse occurred, remind them of where they are right now. My office window overlooked a bridge so I often suggested to my patients that they look at the window and identify that bridge so they could note that the abuse did not occur in this particular city, in this present time.

Physical cues are also helpful. By asking him/her to take a deep breath with you, he/she may then experience even a moment of distance from that traumatic experience. Again, it is encouraging the realization that the trauma can be viewed from a distance in time and space. In other words, it is inviting the experience of safety in the present. It is putting the flashback where it belongs – in the past. It is a memory, not a current experience even though it seems like it is happening now because your body is having the same response of fear, panic, hyper-vigilance and a pounding heart. This is the therapeutic process of disengaging from a flash back.

It is just as important to connect with the alters that are being harmed inside – not just the ones doing the harm. Remember that while some alters seek to do harm, others feel the need to be harmed. It may be phrased by those alters that they deserve to be harmed or that there is no other option. Both need empathy, compassion and understanding as well. Within an environment of understanding, empathy and compassion, the suffering alters will be able to make a shift.

Help those alters in conflict find a safe place to process and heal the wounds. Encourage others in the system to help modulate the conduct of the angry harmful alters, to become their friends. Encourage those that are being victimized inside to connect with other parts of the system that can act as their protectors – not from the point of view of fighting with the other angry alters but rather as a bridge to understanding each alters particular suffering, generating empathy for each other and a spirit of healing teamwork.

For example, the soft and comforting voice of the therapist, or your self-appointed internal therapist, can shift the alter who is still stuck to the past traumatic experience back into the present moment of safety. The pathology is that the particular alter will remain tenaciously stuck to the past trauma. The therapist, no matter from inside or outside, has to persevere to achieve a small, step-by-step separation from the past trauma into the present. It is difficult but this is often the very central practice in DID therapy.

I want to be quite clear that in this I am directly addressing an alter, treating him/her as my client and giving them my full attention. Some therapists prefer to speak only to the host. In fact, colleagues have criticized my approach as reinforcing the splitting aspect of DID pathology. As I have written elsewhere, fish swim, they are not taught to swim. In that same way, DID individuals dissociate, they are not taught to dissociate. For fish, to swim is instinctual. For DID individuals, to dissociate is similarly instinctual – it is their instinct for self-preservation in the context of massive early childhood trauma. 

In my experience, a large part of DID therapy is one-on-one psychotherapy directed to individual alters. If you have an internally appointed self-therapist, working as an adjunct to your therapist or alone because you are unable to find a therapist, one can encourage the same approach of communication between the inner therapist and the self-abuser. Knowing that the self-abuser is acting out unprocessed trauma allows one to communicate always with respect and always with kindness. 

*The Karpman Triangle is found on page 126 of Engaging Multiple Personalities Vol 1. It is also displayed by Joan, in Chapter 1, who struggled with this almost every night for months.*


## Weighted Blankets and the Sensation of Safety

*Posted on June 25, 2019*

There is a general bias in identifying a pharmaceutical agent as a better, effective, or more scientific way to overcome a symptom than a natural method. In addition, it is extremely difficult to apply for a research grant to prove that such a natural method may be better than a pill for insomnia. Certainly not from the pharmaceutical industry! So, I doubt if grants are available to study how effective a weighted blanket is compared to a pharmaceutical agent for insomnia. On the other hand, there are now many anecdotal reports on the benefits of weighted blankets.

When I first read of the use of weighted blankets as an aid for sleep, decades ago, I thought it would make sense if it helped people with insomnia. I seldom have insomnia, so the idea of purchasing one never came to me.

Recently, I read some postings in DID Facebook groups that reawakened my interest. I also found out that weighted blankets have become a common commodity. I just stopped into a shop that specialized in things that promote sleep and bought a weighted blanket. It is 15 pounds; the recommended weight for someone my size. I wanted to explore the first hand experience of using one. Here is my report after using it for 3 weeks.

In the beginning, I felt mildly resentful because I felt restricted in my movements due to the weight. It seemed to be a hindrance to moving around in bed. I quickly realized that what I was seeing as an impediment was a mistaken understanding. It was an obstacle to manifesting my agitation physcially in bed. But when I stopped fighting that sensation, it seemed that what it was actually generating was the sensation of safety a baby might experience being “tucked-in.” So, I imagined I was a baby in a “wrap.” Sleep came over me soon. True to my expectations, I did experience a positive feeling as if I were being held and hugged while under the heavy blanket.

Three weeks have gone by. My sleep, in general, feels deeper. The number of times I wake up to use the toilet has decreased. In the evening, I look forward to the experience of going under the heavy blanket. I feel more refreshed in the morning. I cannot rule out that it might just be a placebo effect. Placebo or otherwise, with the blanket, I quickly settle into sleep regardless of any sense of resentment at the restriction caused by the weight.

**Conclusion**

1. The simplest way for me to fall asleep has always been to be still, to stop tossing and turning. This heavy blanket is like a gentle reminder to me just to keep still. I believe “tossing and turning” is the most commonest reason people who have difficulty falling asleep get into a pattern of insomnia. It is like the phenomenon of scratching an itch: The more one scratches, the more itchy one feels. Tossing and turning make people more restless, which makes them toss and turn even more. 

2. I can feel the sensation of being tucked-in and held. There is an immediate shift from the physical sensation to the emotional. 

3. Some people may resent the sensation of restriction of the blanket stopping you from freely tossing around, as I did initially and still do to a lesser extent. It is easy to get over this, because the sensation of being safely tucked-in, that good feeling, quickly takes over.

Considering this from the viewpoint of someone with DID, how might this be helpful? For someone with early childhood trauma, the sensation of being touched is often frightening – the opposite of being safely tucked in. This early trauma impacts those with DID for decades into the future. So, a question in therapy is how can the therapist help a patient re-learn the experience of that sensation of safety without touching the patient? Further, how can the patient experience safety at home, perhaps at night when it might be most needed? Knowing the difficulties DID patients often experience with close body contact with their partners, how can a partner help engender that experience of safety in a way that eliminates any trigger of sexuality? And finally, how can someone with DID that doesn’t have a partner experience that sense of safety alone in their home.

I want to be clear that I do not believe there is *any* approach to DID that will successfully address the problems of all individuals with DID. However, given that different approaches can be helpful to different patients, I thought it was both interesting and possibly important enough to post these thoughts. If readers of this post have read my books on DID, the Engaging Multiple Personalities Series, you will know that I believe that re-learning the experience of safety in the here and now, the experiential sensation of being safe, is a critical component in the healing journey. The question for therapists is how to deliver that sensation. 

I have written in my books about using a large bolster cushion to push lightly against a patient’s chest to have them experience the sensation of a grounding safe touch without me actually touching them directly. There was always the large bolster between us both for ethical concerns and for avoiding potential triggers. The weighted blanket seems to serve a similar function, but can be used at home, alone or with your partner, and is in your control which has the additional benefit of self-empowerment. 

I told the spouse of one of my former patients that I wanted to experiment with this.  He wrote back letting me know they had purchased one already. He wrote that the first night of use his spouse was irritated with the weight of the blanket. She commented that she really didn’t see any difference and didn’t like it particularly. Nevertheless, without prompting, she has used it every night since. No longer getting up repeatedly to use the washroom, no longer waiting for the spouse to fall asleep first before drifting off herself to sleep, and other positive results have happened.

So, in short, I think it may be of benefit. There are many versions and at different price points. I am not well versed enough to comment on which weighted blanket might be better than some other one. If people have tried this and had a negative reaction or no positive reaction, please post that as well.  It may be helpful for others in the DID community to get a sense of whether or not it is something that has a likelihood of being helpful to them.

I do have to add a disclaimer: I do NOT hold any commercial interest associated with sleep promoting products whatsoever. To my knowledge, neither my former patient nor her spouse has any economic interest in weighted blanket companies.


## The Sensation of Touch

*Posted on June 30, 2019*

In the previous post regarding weighted blankets, I spoke about the importance of experiencing safe touch and that the use of a weighted blanket may, for some people, be a safe way to re-learn that experience. Most people usually think of touch as a pleasant or painful sensation, but rarely a highlight of life in the absence of the heightened experience of touch related to sexuality or pain. Touch, more than merely the interface between our bodies and the outside world, is probably the most misunderstood sensation. 

The sensation of touch may be differentiated into several categories: light touch, deep sense of pressure, temperature and pain, vibration, proprioception or sense of position in space (such as joint sense ) and others. It is said that there are 20 different types of highly specialised receptors associated with touch. These are sensory neurons found in all parts of the body except the brain. They vary in density and sensitivity to stimuli.

Touch is a fundamental part of our daily experience. The sense of touch gathers information about our surroundings as well as being a means of establishing trust and social bonds with others, both people and animals. It is crucial to creating our unique human experience. No wonder we use phrases such as calling something a “touching experience”, saying someone is “touchy”, or feeling “soft-hearted.” We often use the word “feeling” to reference emotional states rather than solely the sense perception.

The human brain has two distinct but parallel pathways for processing touch information. 

1. The first pathway is sensory, which conveys some dry facts: vibration, pressure, location and fine texture. It can tell you if someone is stroking you, up or down your arm. That part of the sensory pathway is a brain region called the primary somatosensory cortex, which is the first region to be triggered by the experience of touch. 

2. The second pathway processes social and emotional information. This pathway identifies the emotional content of mostly interpersonal touch using different sensors in the skin. This pathway activates brain regions associated with social/psychological bonding, pleasure and pain centers.

Touch is critical for child development. This is something researched for many decades, such as Harlow’s experiments on monkeys. We know a parent’s touch, whether positive or negative, is a crucial factor in a child’s development.

Most people wouldn’t have difficulty distinguishing between a friendly touch of social support and a touch involving sexual suggestion or seduction. An arm around the shoulder coming from a person will change the way you experience that touch based on your relationship with that person. Our brain processes the sensorial experience with information about the social context from other parts of the brain. Usually the social context enables us to tell whether the gesture is genuine or insincere, whether it is straightforward or perhaps cloaks a hidden agenda. Identifying a gesture as insincere or containing a hidden agenda then appropriately triggers the need for further investigation.

### Therapeutic Touch {-}

A large body of research suggests that therapeutic massage can be helpful for a number of physical and mental ailments. These include pain relief and addiction recovery, as well as maintaining emotional equilibrium, cognitive function and mobility among an aging population. Others have also suggested that massage may be an effective way to treat anxiety, insomnia, headaches and digestive problems. 

The popularity of therapeutic touch has not received its due recognition. This is partly due to the dominant status of the pharmaceutical approach and partly due to the lack of vigorous scientific proof of its efficacy. However, those with trauma in their background must remain aware that it may be difficult to identify the very moment that touch may change from a healing procedure into a sexual transgression. Always be as clear as possible about your personal boundaries and in maintaining them. It may be a good idea to tell your massage therapist at the very beginning that you have very strict boundaries that must not be crossed. Doing this may avert the danger of the massage therapist inadvertently or even intentionally blurring/crossing the ethical boundary between the therapist and the client being touched.

I am especially interested in establishing healthy self-soothing practices in our daily routines. Self-soothing happens when we need to be soothed. We use all kinds of methods to be soothed – some are safe, some are unsafe and some are neutral, depending on how they are applied. Given the general phenomenon of addiction related to nicotine and alcohol along with the uncontrolled use of comfort foods (especially sweetened foods), and their attendant unhealthy consequences of obesity, diabetes, high blood pressure etc, safe self-soothing options are critical. Advertising for alcohol, nicotine and processed foods are designed to seduce us without concern as to their negative attributes. 

In my experience with DID patients, grounding and self-soothing are part and parcel in healing those who were subjected to early childhood trauma. Helping them re-experience the literal sensation of “safe” was critical to therapy. Learning to self-sooth, the self-empowering process of being able to generate that sensate of safety is an essential part in healing. 

It is in this context that I wrote an earlier post on the therapeutic potential of weighted blankets. I think any self-soothing practice that does not cause harm is worth very serious consideration. Consider comparing the negative aspects of self-soothing with drugs or alcohol (or any other addictive behavior) with simply resting under a weighted blanket. If the weighted blanket works for you then there is no contest.


## Countering the Far Reaching Effects of Humiliation Part 1 – Disempowerment

*Posted on September 19, 2019*

To humiliate someone is to make them feel ashamed or stupid, to make them feel like they have lost, and are undeserving of, the respect of other people. Humiliation is a common tactic abusers employ to subjugate a child. It is accomplished by debasing a child’s status, through breaking their spirit and pushing down their ego to the point of abject submission. 

Humiliation is always connected with a power imbalance. In short, an abuser is communicating that “I am stronger than you/I have authority over you/I will overpower you. Therefore, you will submit to me/my wishes/my demands.”

The result of humiliation is dis-empowerment. And, as with any experience of dis-empowerment, the consequences ongoing traumatic humiliation are far reaching.

Michael J. Fox said, “One’s dignity may be assaulted, vandalized and cruelly mocked, but it can never be taken away unless it is surrendered.” For an adult, there may be a choice to not surrender, or to surrender only in part. An adult can decide to fight it out, or to maintain a spirit of rebellion when there is no possibility of physically fighting back. In other words, an adult can choose not to surrender (in spirit) or to physically fight back, rather than to silently accept defeat and fully accept the role of being a victim. An adult may, perhaps, blame him or herself. They may feel guilty and deserving of the humiliation, but they have adult tools to fight back with or to work with those feelings.

Now imagine the gross confusion and bewilderment that arises when humiliation is heaped upon a child. Imagine, as a child, being forced to participate in the obscene act of being sexually violated, being physically beaten, or being otherwise abused, and to accept that humiliation in a spirit of submission. Escape through dissociation is likely the only logical or even possible outcome. 

For a young child being abused by an adult or older child, surrender is not a choice but is rather an inescapable outcome. For very young children, survival through submission is the only option. When early childhood abuse and humiliation is a repetitive experience, dissociation becomes the default response – regardless of age.

Keep in mind that humiliation is not the sole goal of the abuser. Crushing the spirit of the victim is part and parcel of establishing the power dynamic that permits the abuse of that child in the future when and as the abuser may wish while limiting the possibility of genuine push-back from, or exposure by, the child. Humiliation enables this by the piecemeal or violent erasure of personal boundaries by the abuser, normalizing the humiliating conduct and eroding further a child’s sense of having any place in the world.

Many of the difficulties people encounter in daily life can be traced to experiences of humiliation; in adults, in children and in society. The impact of humiliation seems to include a baseline, different for each individual, beyond which a person will be unable to pull back from its clutches. When a person’s spirit is crushed in this way, unremitting depression sets in. The choiceless acceptance of humiliation is often followed by powerless rage. 

Consider the intensity of that choicelessness coupled with powerless rage. In so doing, one might get a sense, a glimmer, of the importance of angry alters. They keep open both the chance of survival and the healing potential of the system. The trapping of rage in those angry alters keeps the system alert to identifying potential dangers, albeit often hyper-alert with its attendant difficult consequences. At the same time, trapping that rage in the angry alters allows dissociated submission that enables survival while experiencing abuse.

Humiliation can often be a non-physical assault. Some people may think that because it is not necessarily physical, it therefore is not so big a deal. However, looking forward, it can have the extraordinarily destructive result of setting up an abused child for ongoing future assaults both psychological and physical.


## Countering the Far Reaching Effects of Humiliation Part 2 – Elements of Humiliation

*Posted on September 22, 2019*

Humiliation is not a defined term in the DSM 5, although it is used in a few isolated instances. This presumes a common understanding of humiliation which is unlikely to be as common as people may think. But, like other forms of trauma, particularly those lacking an initial specific motivation occurring out of callousness or lack of empathy, the way humiliation is experienced by the one harmed dictates their future pathological responses. 

Generally speaking, there are 3 elements to humiliation in the abuse context: 

1. Denying the status of the victim through a subjugation that undermines the pride, humanity or dignity of that person. 

2. Reducing the victim to passivity as the method for rendering them powerless. It uses a gross power imbalance in subjugating the will of the victim, of even their experience of self-hood. 

3. Violently destroying the personal boundaries of the abused, leaving a damaged psyche. The end result is the decimation of their self-confidence. The person is dis-empowered, often with life-long disabling consequences.

Stepping back, consider the role humiliation plays in the case of corporal punishment. Caning in schools, or in the family, immediately establishes a hierarchy of physical power, with the one who administers the punishment over the one being punished. For the child, if inwardly rebellious and able to silently remain angry, their buttocks may be bruised or scarred, but damage to their psyche is mostly spared. In those circumstances, humiliation is countered by refusal to identify as a powerless victim. Such a child faces punishment with a fighting spirit, rather than surrender. 

But contrast that with a critical factor in DID etiology – that the abuse occurs at an extremely early age. For those with DID, humiliation in connection with abuse (physical, sexual and/or emotional) often occurs before the child is old enough to have established a psychological structure with enough stability to even envision fighting their abuser. It is here that the real damage to the child happens, when there is such an intense subjugation as to prevent the child from establishing the foundation for any sense of safety in life. At the same time, the dissociative response often enables the arising of angry alters whose importance to healing is critical, as is discussed in Part 4 of this extended blog post.


## Countering the Far Reaching Effects of Humiliation – Part 3 Dignity, Humiliation, Respect

*Posted on September 22, 2019*

Dignity is the state or quality of being worthy of honor or respect. It is the inherent right of people to be treated with dignity. From a religious point of view, dignity may be seen as God’s gift to each individual. From a secular point of view, dignity can be seen as one’s human right to act and have their own agency in the world based on the simple fact of their human existence.

Dignity is displayed in a calm and controlled demeanor. But, it can be harmed through a humiliating experience or crushed through repeated humiliations. Dignity is a sense of pride in oneself, of self-respect. The polar opposite of dignity is humiliation.

Humiliation is the crushing of dignity by an outside agency – in the case of DID etiology, by an abuser attacking a young child. Unfortunately, dignity and humiliation are usually outside the language spoken by psychiatrists, or mentioned in diagnostic formulations.

Humiliation is mentioned a few times in the DSM 5, but not in the context of DID etiology. But, it remains undefined in the DSM so far as I have been able to determine. It is used (on page 703) in this way: “Sustained feelings of shame or humiliation and the attendant self-criticism may be associated with social withdrawal, depressed mood, and persistent depressive disorder (dysthymia) or major depressive disorder.” 

This quote from the DSM infers that shame and humiliation are interchangeable terms, but that is not the case. They are not identical. Nevertheless, it should be instructive to clinicians that the listed symptoms resulting from sustained (or one might say repeated) such feelings are often presented by individuals with DID. Despite this, such symptoms are instead usually seen as pathology markers on their own rather than in the context of a potential DID diagnosis.

While humiliation and shame both make a person feel bad about himself, it is important to distinguish between them. Humiliation is always provoked by someone else, while shame is connected to one’s own actions or simply chance circumstances. With shame, people mostly focus on themselves and how others might perceive them. With humiliation, there is the added traumatic factor that the other person is intentionally causing them harm. Abusers often seek to instill shame in those abused by blaming them for the abuse itself. This is true in early childhood abuse, in spousal abuse and in other abusive circumstances.

In short, we bring embarrassment upon ourselves and may feel ashamed as a result. But, humiliation is brought upon us by others. From a therapeutic point of view, it is clearly an abuser’s assertion of power over a child that cuts far deeper, leaving both scars and open wounds which show up as triggers in the future. Because humiliation is traumatic, it is kept hidden by the one humiliated while being simultaneously used as a weapon by the humiliating abuser. Fundamentally, humiliation involves abasement of pride and dignity, along with a loss of status both personally and socially.

Respect is something earned through one’s actions. Self-respect is a state of mind that is founded upon pride and confidence in oneself. It is a feeling that expresses itself through behaving with honour and dignity. Self-respect means proper esteem or regard for the dignity of one’s own character. This self-respect is part of both the path and a marker of healing.

We can easily trace many negative character traits to their origin in a loss in dignity, in those with DID and others whose negative conduct does not rise to the level of being pathological. This can happen when a child is under assault in the form of bullying or massively disproportionate and severe punishment. The result may be perpetually defending oneself even when one is not under attack, in excessive one-up-man-ship. It may show up in excessive social competitiveness, aggressive or even abrasive personality or social phobia and excessively passivity. Mistrust and paranoia can often be linked to pronounced early childhood humiliating experiences.

Alternatively, it can result in a child developing an overwhelming passivity. In the face of ongoing humiliation, a child may internalize the message of the abuser that the child has no ability to defend themselves – even internally. In effect, such a child may end up adopting an abuser’s weapon of humiliation as an adaptation of survival. By giving up any fight, the child survives another day with the abuser. 

As noted in Part 1 of this extended sequence of posts, because humiliating experiences are not necessarily physically overwhelming, they may not be seen by an outside person – therapist or other adults – as being genuinely traumatic. This is a tremendous mistake. This kind of humiliation, this abusive power dynamic, is often no less damaging than physical trauma. But, it is easier for a therapist or other adult to ignore because the evidence does not show up externally – at least not immediately – the way one can see a broken arm or the bruise from a punch.

One must consider instead the fact that the damage may show up in the future as violence directed inwardly as self-harm or outwardly against others. When it appears primarily as a psychiatric morbidity, as depression for example, therapists as well as patients may miss the possibility of humiliation as a causative agent. The result may then be medication to suppress the depression rather than helping the patient process the early-childhood psychological trauma through therapy. 

When anti-depressant medications don’t work, it may lead to a diagnosis of “treatment resistant depression.” I don’t consider treatment resistant depression to be an accurate categorization. Rather, in the current environment of prescribing antidepressants as the primary method of treating depression, it should be seen as drug resistant depression. When medication doesn’t treat the cause, and instead solely treats the a symptom, the cause remains intact. If the cause remains intact, it will continue to manifest in some way, shape or form despite the medication. The unfortunate result can often be over-medicating patients to the point that the medication causes dysfunction separate and apart from the cause of the depression.

With unresolved early childhood trauma, the antidepressants may have limited benefit but that does NOT mean that you should just stop taking them. Instead, work with your doctor to have meaningful psychotherapy with the antidepressant as an adjunct to therapy rather than the principle method. With proper psychotherapy, as you heal from the trauma, the medication should be able to be successfully and safely reduced. Because suddenly stopping a psychoactive medication has potentially quite a bit of risk, if you are on antidepressants, only stop taking them under your doctor’s guidance.


## Countering the Far Reaching Effects of Humiliation Part 4 – The Power of Angry Alters

*Posted on September 24, 2019*

The best indicator of a positive prognosis for those with DID is found in those with defiant angry alters. In effect, it is those parts that say “You have no right to humiliate me. I will not surrender to your will. You have not subjugated me. I will fight you always.” The implication for those treating DID patients is to remind those patients that their angry alters are generally the ones that refused to simply surrender to their abuser. Even though they may only have the initial capacity to express their anger in ways that are frightening to others both internally and externally, a path forward to healing can be found through engaging with them in therapy.

Engaging the angry alters is the opportunity to access that positive defiance, that refusal to accept humiliation as defining them. Appreciating their strength and insight is a genuine method to develop support within the system so that alters can begin to work in concert rather than in conflict. In my practice, the patients with the best prognoses were those that were able to connect with their anger – which often meant engaging with those angry alters again and again. By ongoing engagement in that way, one invites their assessment and potential trust in the therapy. 

A common and negative outcome for the victim is submitting to the punishment without harboring some internal rage. In short, succumbing to the abuser’s humiliation of them. 

There are several possible changes in the personalities of people who emerge from significant childhood humiliation experiences. They range from inability to relate to others which may appear as awkward socialization to severe psychopathic behaviour. 

In the worst scenarios, the victims of humiliation – in the case of DID it may be one or more alters – over-compensate. As noted in the previous post, they may develop a powerful urge to gain personal power to control all social interaction. The drive to control can be so strong that it eliminates any sense of sympathy and compassion for others – including other alters – as well as when interacting with other people. Extreme levels of self-protection take over. It is this manifestation that makes angry alters both powerful and difficult. But, please don’t see those alters as identical or inextricable with their difficulties. To do that will mean that you miss their capacities as keys to healing.

For many with DID who have had their spirit seemingly crushed through humiliation, instead of acting out for revenge externally, that rage against powerlessness is turned inward. Chronic depression may be coupled with generalized fear with the loss of self-confidence as the outcome. Social relationships, including familial and marital, are compromised because of deep inherent mistrust. To heal this, and it is possible to heal this, calls for powerful transformational changes. 

Once again, humiliation crushes the child’s spirit. It is intended to undermine any possibility of self-confidence and to infuse the child with fear. It impacts the child by giving them a twisted perspective of human relationships. The result is often to eliminate the capacity for genuine intimacy. It attacks that human capacity for intimacy by convincing them to distrust all relationships that might appear safe.

It does so by convincing them that they will never be safe, certainly never from the abuser. It seeks to convince them that “Anyone trying to convince you that they are safe is only presenting an appearance of safety because safety doesn’t exist.”

This is a critical barrier for therapists to be aware of and to overcome in dealing with anyone with DID. In my practice, the only path to overcoming that barrier was to respectfully engage the alters including the angry ones and to always gently invite them all to participate in therapy even by simply listening in as I engaged others in the system. 


## Countering the Far Reaching Effects of Humiliation Part 5 – Healing From Early Childhood Humiliation

*Posted on September 24, 2019*

Alice Miller wrote: 

> As long as they are loved, children can recover from abuse and even the horror of war.

Humiliation is a form of severe child abuse when the child experiences it on a repeated or ongoing basis beginning in their childhood. The path to recovery from humiliation is through love. Love starts from the ability to accept love, from oneself as well as from others. However, it is extremely difficult to practice self-love in the absence of love from others. 

The characteristics an individual displays depends upon whether a person is given love, protection, tenderness and understanding or experiences rejection, coldness, indifference and cruelty in the early formative years. These characteristics are not innate but rather are dependent on what stimulus a child experiences. For example, the stimulus indispensable for developing the capacity for empathy is the experience of loving care. 

When a child is forced to grow up neglected, emotionally starved and subjected to physical abuse, this innate capacity will fail to develop or its development will be stunted. It is important to appreciate that while the negative experiences of children from infancy to early childhood explain their later behaviour, subsequent positive influences can be effective agents for change. 

Alice Miller also wrote that if a traumatized or neglected child can later come to know what she calls an “enlightened or knowing witness,” he or she can process the effects of childhood trauma with positive results. 

While remaining open to the opportunity to experience love, or positive influence, one should continue to pay attention to one’s boundaries and protectors. At the same time, pay attention to the following in sequence:

*1. Become aware of the connective link between your styles of engaging with others and your childhood experiences of humiliation.*

Repeatedly noticing, and paying attention to the causal connections, is the beginning of making changes. The more you pay attention to this, the more you come to realize that you are not alone. You will see that such experience (of humiliation) is a human drama played out unfortunately and repeatedly every day in so many situations for so many people. Looking at it this way, one begins to transcend the isolating aspect of humiliation’s personal pain and hurt – you are not alone. Eliminating that isolation is another foundation of healing.

One can cultivate this through cognitive restructuring. Reminding yourself of this in a daily quiet time. You can set up a regular time to do this, such as going out for a walk in the morning on a definite consistent schedule. 

And again, remember, you are not alone. 

*2. Learn to distinguish the past from the present.* If you are standing on the bank of the mighty Amazon river and take two pictures a minute apart, each photo shows different water. The water in the first picture has already moved on towards the Atlantic, replaced by entirely different water – even if it looks pretty much the same. In just that way, we are not exactly the same person as we were a minute ago.

This shows that the future is not exactly the same as the past. Use that truth to healthily correct the hangover of feeling humiliated in the past. You can do this by training to focus on the present moment. As Tolstoy wrote, “Remember that there is only one important time and it is Now. The present moment is the only time over which we have dominion.” 

By recognizing the impact of one’s difficult personal history and bringing one’s awareness to focus on the now, we can begin to wipe out the negative influences of the past.

*3. Protect others from humiliation, particularly children.* Should you come across a child being humiliated, or perhaps on the edge of being humiliated, step in and say exactly what you would have wanted to hear so many years ago. At the same time, be protective of yourself as well and, if necessary, call the police or child protective services to the situation. For just that moment, be the protector for a child in the present that you needed in the past. 

Learning that you can protect a child from humiliation is a path to healing for yourself. While you cannot travel back in time to when you were humiliated to undo the impact of the humiliation, you don’t have to. If you see a child being humiliated or abused, you can help that child right then and there. You will be letting that child know they are not alone, that there is protection in the world. You will also be giving that very same message to the child you were years ago. 

