# Engaging Alters in Conflict

## Working with Angry Alters

*Posted on April 23, 2015*

This is in response to several postings on Facebook about potentially dangerous alters. These are angry alters that may harm the body or harm others. This touches on some very basic and frequently misunderstood issues pertaining to DID therapy.

The original function of the angry alter is protection. It is an ingenious defense mechanism for an abused child to establish a self-protective function when they are faced with repetitive abuse that often extends over years. Without that protective function, it is unlikely that a child could survive such impossibly difficult situations. It has the aspect of asserting power, that the child is not solely a victim. There is at least one part that is still fighting the abuser.

The angry alter is *not* the enemy. These alters arise from a deep survival instinct, filled with power and energy. Without these alters, the trauma would likely overwhelm the child – or, later in life, overwhelm the DID system. These alters keep the system alive within the context of and following the trauma. Without connecting to that energy, the prognosis in therapy is not good. The likelihood of the system simply giving up increases tremendously. In my practice, I had patients who were unable to access the energy of those alters and therapy was, fundamentally, a failure. The key point is to work with the energy, with the alter, rather than seeking to eliminate it. Far from being the enemy, these alters are potential partners in healing the system.

As a result of the hypervigilance that results from ongoing trauma, the anger that arises as that alter is often directed towards other alters or the host. This is despite the fact that the dissociation and resultant alters arose because there was no other way to survive the abuse. They usually blame the host or other alters for “allowing” the abuse to take place. This mistake in perception by the angry alter can lead to debilitating internal conflict. That same anger can also be turned on anyone outside that the angry alter might see, presume or experience as threatening – including the therapist.

The therapist must be sensitive to the presence of the angry alter(s). An alter’s subtle but definite show of power in a threatening manner is often discernible to the alert therapist – just as it would be in treating any non-DID patient.

Early in therapy, as soon as I had confidence that DID was the correct diagnosis for a patient, and regardless of whether or not I communicated the diagnosis to the patient at that time, I stated aloud that in order to proceed with therapy I needed the patient to understand and agree that they could not seek to frighten or threaten me. Without that agreement, one cannot proceed with therapy. This is because a proper therapeutic alliance cannot be established if the therapist has concerns about their own safety.

I would inform the DID system that if I felt unsafe, I simply could not be an effective therapist. I would make that statement while concurrently expressing appreciation for the protective function the alter was fulfilling. This is an honest approach that was much appreciated by my DID clients – particularly when that message was coupled with the message that you appreciated – and all the other alters should appreciate – that the function of the angry alter was to enable the system to survive at the time of the original trauma(s).

Following that, whenever I sensed that an angry alter was around, I would seek to engage that alter directly. This is a priority. Genuinely, always genuinely, I would thank the alter for having protected the system in the past. I let the alter know that it is good that they are keeping an eye on me, the therapist. Acknowledging this – because it is true – is telling the alter that it is no longer necessary to try to instill fear in me as a protective shield. This was because their function, along with the DID system in general, was now safely in the open. The system and all the alters within it were within the container of compassionate therapy. That was further assuring the alter that between the two of us, therapy could be conducted in a safe and secure manner.

I would invite the angry alters out if they were willing to engage me, but I would *never* provoke them to come out. I would point out that they needed to remain vigilant to continue to protect the system – definitely encouraging them to keep their watchful eye on me – but that being hypervigilant was not so helpful. Being watchful without being hypervigilant was the healthy quality of their protectiveness. It was something to be maintained and applied to the other alters as well as to people they might encounter in their daily life. In this way, they were invited to reclaim their original role as a guardian.

Generally speaking, prior to DID therapy, alters have not been recognized, acknowledged or appreciated. When directly engaged in communication, they have the capacity to change. Like any patient, they appreciate the experience of being treated with kindness and dignity. In most cases, over time, they understand and change their protective view from one of hypervigilance to appropriate vigilance.

Unfortunately, many therapists take the opposite approach. There is a general reluctance to engage alters for various reasons, especially angry alters, including fear and the consequent denial of alters. It is the therapist's fear that cuts off communication and solidifies the mistaken view that the angry alter is the enemy. They are potentially potent collaborators in healing. On looking back on my decades of experience treating DID, I still find cases where I wish I had taken a more direct approach to engaging the alters, particularly the angry ones, in therapy.

Alters behave like other patients in therapy. They get relief when encouraged to express themselves and feel reassured when they are understood. Once the hypervigilance is transformed into vigilance, they respond to reason and very often make appropriate changes.

DID patients can heal, even after years of neglect and/or abuse. I hope that DID individuals read this so as to gain confidence in the importance of making friends with all their parts. I also deeply wish that therapists consider these points so that they may overcome their reluctance to engage and learn from alters. 

I have written Engaging Multiple Personalities Volumes 1 and 2, and continue to write this blog, in retirement. It is my opportunity to reflect back, to acknowledge my past mistakes in my practice, and to offer my painfully learned experience to others so that DID individuals and their therapists can further and quicken the healing process.


## Working with Despair and Anger

*Posted on March 21, 2015*

My patients who connected with their anger safely were the ones that made the strongest and safest recoveries. Those unable to connect with their anger had more difficult journeys. This is clear in the case histories discussed in Engaging Multiple Personalities Volume 1.

Despair arises because it seems that there is no way out of that depression and fatigue. But there is: It is to work with the anger. Angry alters can often be converted to protectors in DID therapy because they usually arose originally in a protective function. It is getting back to that basic protective energy so therapists take note: We don’t get rid of the angry alter. He/she can be a highly valuable co-therapist or protector in the healing of a DID client. 

It is very common for survivors of trauma and dissociation to feel tired, depressed and hopeless. Energy has been and continues to be drained away dealing with the pain of the past. Colin Ross clearly explained, in the chapter “The Healing Power of Feeling: Anger and Grief” in his book Trauma Model Therapy, that “Anger and depression are psycho-physiologically incompatible states.” The polar opposite of depression is “anger, (which) is energy, arousal, adrenalin, good posture, aggression, and the fight response.” He continues, “Assisting clients to step into their anger leads to stepping out of depression. That is partly because of the state switches to an energized, activated state, and partly because it takes considerable energy to repress all that anger.” 

It is much preferable that you have a therapist who assists you to step into that anger. If you are doing it by yourself, through journaling or otherwise, be extremely careful and following these guidelines: 

1. Go into it slowly. Instead of trying to do it all in one sitting, be prepared to do it over weeks or over as long a time as is needed to do it safely! 

2. Take baby-steps. The first step is to learn how to stop, and to be able to go for a walk to ensure that you are establishing safety and control of the anger. It is like when I first learned how to drive a car – I made sure I knew how to step on the brake correctly to stop the (slowly) moving car first before I went driving around on the real roads. Control is the key. 

3. Be kind to yourself – to every part of your dissociative self. The usual mistake is going too fast. Old anger, when it is first released, tends to go overboard. The risk of getting in touch of your anger is that it may become destructive, such as getting physical and breaking furniture. So, I do not recommend doing this alone without the strong support of a significant other or supervision by a therapist.

Every survivor of abuse has the right to be angry. They were abused – often by people that should have protected them but instead betrayed the relationship in the most vile ways imaginable. Get in touch with that anger SLOWLY AND IN A CONTROLLED SAFE MANNER. It will generally lead you out of depression and fatigue.


## When Alters Despair

*Posted on November 24, 2015*

A question came up from one of the readers of Engaging Multiple Personalities who is DID. As it seemed to be a topic that was relevant perhaps to many DID individuals, I thought I would share some of my thoughts. As always, it is important to understand that I am retired and cannot offer therapeutic advice to anyone. Please do work with your therapist and know that healing is possible.

The basic question was not about angry alters, rather it was about alters that hold so much depression and trauma that the only solution they see is to die. They don’t want to harm any of the other alters or the host, they just see no exit from their pain.

I can tell you that my life experience (I am almost 80 years old at this point) is that no one wants to suffer. Whether they are DID, have PhDs, are poor, are wealthy, are young or old, no one wants to be in pain. Much of our lives are spent simply trying to avoid pain and seek comfort.

My DID patients usually had severely depressed alters that would present their logic for why they (and everyone else in the system) would be better served if they were gone. With only the experience of holding traumatic memories – and walled off by the DID from any experience other alters might have of laughter, enjoying food, and a warm glance from a genuine dear friend – their desire to give up on life is understandable.

It was always difficult to establish a bridge of communication to help those alters shift their perspective. But, when that bridge was established they were able to begin to shift their perspective, if only for a moment and if only just a little bit. Once that happens, it is as if the clouds are starting to soften and maybe even part after a huge storm. The thick black clouds begin to get a touch of grey. The sun may not yet be fully visible, but at least there is more confidence that it is up there somewhere. 

Alters stuck in their despair understand that each alter shares the body with all the other alters, including the host, so a peaceful death of one alter without affecting the body simply doesn’t work. They don’t wish to harm anyone, therefore they are looking for something other than suicide. Like other alters who are holding the most difficult trauma, they simply don’t see a way out. That is because they arose in response to an abuser psychologically hammering into them the belief that there was no escape from the pain then nor would there be in the future.

The fact is that these alters have taken on an incredible amount of pain so that the system can survive and function. In fact, I had patients with alters that had sequentially arisen to take care of a certain level of trauma and then, within and during the same traumatic event, when the pain increased too much for that alter, another alter would arise to take on that increased level of pain – and so on. These alters were taught that there is no relief that will ever be available to them. Nevertheless, relief is what they want and the only solution they see, because of amnestic barriers, is to die.

I would sometimes give my patients, and specifically those alters, an analogy to their experience that some of them found helpful: I would point out that for one person to lift a 500 pound weight is generally impossible. But, if 500 people share the lifting of that weight then each one is only taking on 1 pound – easy to do. In this case, the intensity of the pain held by the alter in despair is the 500 pound weight. Clearly they can never lift it alone, and therefore see no escape from the pain.

However, the more other alters engage, befriend and share with that alter, the burden being borne solely by that alter eases a bit. Maybe at first from 500 pounds down to 499 pounds. That is still too much for any one to bear, but with each engagement, if a few pounds are shifted, then the path to relief starts to become clear – even for the severely depressed alters. That is the point when the black skies lighten just a bit. Sharing their burden is not easy for the despairing alters to do, and is also something that many of the other alters don’t wish to try. After all, holding that despair walled off within an amnestic barrier is why that alter was likely created. So, effort needs to be made to encourage the non-despairing alters to take on just a small touch of the pain.

The corollary to this is that when you share joy, it increases. Kind of like when everyone is watching a movie and laughs at a funny line. It is experienced as much funnier than one experiences the line watching that same movie alone. So, the guidance is to try to share the burden and share the joy. Both of these are difficult for an alter in despair to try because it goes against the imprinting by the abuser that no relief is possible.

Without pressuring them, make sure the alters that want to die begin to listen to the joy that some alters feel. They don’t have to immediately experience it if they don’t want to or cannot, but it is kind of like inviting them to at least listen at the door until they feel safe enough to come join in – even just enough to stick their toe inside. In short, this is how you and that alter who really wants to put an end to the suffering without harming the commonly shared body can proceed.

The above suggestions are methods to work in the mind(s) of the system. How this might be done in the body is the next issue. 

Sometimes, I suggested to my patients that they might invite the despairing alter to go for a restful sleep. This is not to tell them they are unwelcome. In fact, it is just the opposite. It is like when someone is ill, you want to bundle them up safe in a warm bed with warm honey tea and buttered toast. They can stay in bed resting while you guard the door, so to speak. 

I would suggest for this alter to go on a short “retreat.” Let me elaborate further by giving an example. An ideal retreat for me is going to a place that has a quiet garden, eating very simple food and spending some time walking in a forest, smelling the wild plants, listening to the birds and maybe the noise of a small babbling brook. If you can do this even for a few minutes, for a few hours, or for a few days, without books, radio, e-readers, i-Pods etc., it can be very healing.

Allow nature – here meaning the outside world and your body’s interaction with it through the senses – to bring you back to the complete “here and now.” Try to bring a complete attention to the present, the present breath, the gentle tired feelings in your legs and the slight hunger in the stomach before a nourishing simple meal. This is a way to use the sense experience of the body to comfort the distressed alter.

Invite the troubled alter specifically to join you in that simple retreat, without being heavy handed. If they say they don’t want to come, no problem. When you go, they will automatically be there with you so long as you leave the door open for them through your good heart. Again, it is like inviting someone waiting just outside the door to listen in, perhaps they are too frightened to enter but they want to hear what is happening. 

I know this suggestion may be met with resistance by some individuals who do not like its possible religious overtones, but the Earth holds all of us. Being undistracted in nature, allowing our senses to engage it, is not particularly religious. 
If it is too difficult to get to a forest or garden space, my other suggestion is simply giving that alter a period of therapeutic sleep. Invite him/her to go for a long weekend of therapeutic sleep. Let them know that this kind of sleep is to allow a period of deep safe rest and healing rather than simply a time of avoidance. When you do this, make sure that as part of the invitation, they know that when the therapeutic sleep is over, you will have a meeting with them, speak directly to them, invite them to be your friend and share your experience of peace and safety of the garden/forest walk. At the meeting, listen to them speak of what is on their mind without judgment. As with any alter, they need to process their trauma safely.

Healing does not depend only on talking and thinking, it also requires rest and re-organization. It is like setting a fractured bone. You put the fracture in good alignment with the main bone and keep it in a plaster of Paris cast. The cast is a safe, protected place where the pieces can grow back together. The good alignment is kindness. As best you can, always be kind. 


## Engaging with Many Voices

*Posted on March 10, 2018*

Letters from readers applying the information contained in my books and blog are a rich reward in my retirement. Trauma and dissociation is widespread and, unfortunately, so often dismissed by professionals in the field of mental health. So, nothing is more satisfying than to learn that my humble writing efforts reach around the Globe and offer some help to individuals with DID. With blogs and social media support groups, there are now additional vehicles to bring comfort to many who continue to suffer from trauma and dissociation.

I received some kind words about my books, along with a question, from a reader who is both a DID therapist and patient. While he may post a review, the more important message was in his question. I felt his message included something in particular, a way to communicate the experience of DID, to those in the mental health field as well as to those outside of it.  I think this reader nailed perfectly his experience of dealing with many voices.

The reader described his experience as being “like an uncontrollable, undisciplined meeting where everybody is speaking at the same time” or “like listening to 15 radio stations at the same time, but being unable to understand or sort out what they say.”

Part of educating non-DID individuals as to the experience and truth of DID is figuring out how to communicate the DID experience. The analogy given by the correspondent, that it is like turning on 15 radios set on different stations simultaneously, is accurate and instructive to non-DID individuals. If your friends or therapist doesn’t understand or appreciate the experience, bringing in 15 radios tuned to different stations might be incredibly helpful. Perhaps this is something that should be done at each and every meeting of therapists who deny DID because they simply cannot connect with the experience.

The questions had to do with dealing with that experience of so many voices clamoring for attention at the same time. I suggested to begin journaling. My patient Ruth, presented in Chapter 5 , volume 1, had hundreds of alters all trying to communicate at the same time. We sorted that out fairly quickly. I asked her to invite the alters who wished to introduce themselves and write about their grievances to allow Ruth to bring in a few pages of messages to therapy sessions, according to degree of urgency or severity. The alters very quickly realized they all had a chance to get their problems addressed. They became very cooperative and took turns to be “heard.”

Reading out the messages and responding to the specific alters directly, it became a method to quickly engage them individually. The approach was problem orientated, rather than alter orientated.

Journal writing can be very effective, both as a form of self-therapy or incorporated into the therapy session. Writing has a calming effect in organizing what appears to be chaotic and confusing thoughts.

As a child, I learned that most of the time, if I could put my problem or question clearly in words, I have often come close to the answer myself. That is because the process of writing helps organize ideas and thoughts. If, having organized the ideas and thoughts by writing, with your therapist’s support you can begin to come close to the answer –  which is the beginning of processing the trauma. Once Ruth’s alters were assured that they were being taken seriously, they would take turns to present their concerns. I did not try to go through a checklist of all the alters but only listened to those with the most urgent messages. Not all the alters needed to go through individual therapy. I encouraged communication among the alters, and the breaking down of memory barriers. In that way, when one was helped, others felt that their problems were helped as well because many do have similar problems and issues.

As readers of my books and blog know, I think it is very important to connect to one’s sense perceptions in order to understand the here and now experience. Grounding exercises, using the 5% rule and one-breath meditation are all techniques that can be helpful to address the concerns of all parts of the system.


## Communicating With Alters That Don’t Speak

*Posted on March 15, 2018*

A reader wrote to me asking my thoughts about a problem that affects many DID individuals. The question was about working with alters who are mute, perhaps too young to speak, or, in general, uncommunicative. This raised a common concern: how can we communicate when they do not speak?

The foundation of this is the understanding that communication with alters in need is essential for healing. Ignoring alters will simply make matters worse.

When we consider the possibilities of communication, it can take place directly or indirectly, verbally or non-verbally. Direct verbal communication is usually, though not always, somewhat straightforward. Indirect verbal communication can refer messages routed through a 3rd party. In the case of DID, this 3rd party routing can be very useful. I had patients that established one or more alters as the spokesperson and/or message deliverer between me and alters that for whatever reason did not wish to communicate directly. Sometimes, the communication gateways were alters that knew the silent ones inside enough to approach them, or be approached by them, to pass messages in both directions.

With respect to young alters that were pre-verbal, these had usually arisen at the time of early abuse that took place when the host was pre-verbal. For those, it seemed that alters who were just a bit older and already verbal were the best at communicating to those very young alters, and could facilitate communications.

In short, I suggest that encouraging alters to take on that role can be very helpful. Some may be willing to do so, some not. Inviting alters to try, even if they don’t succeed, is a positive step forward – like cracking open a door that has been long closed. The door won’t readily swing on hinges that have been frozen in place after so long, but the first little opening enables a second to take place and a third until eventually the hinge begins to swing more easily.

Sometimes, among all people, communication involves messages that say one thing on the surface but make another, sometimes different statement, at the same time. In DID, the internal conflict can play out in that kind of communication. For example, the communication might come from a very angry protector saying “I hate you – so stay away or else…” But that same message may be commingled or be an overlay of a message from a frightened very young alter testing whether or not the therapeutic alliance is genuine or just another opportunity for betrayal.

Non-verbal communication takes place all the time and is a very important way of communication. Take the example of communication between species, we all know for example a dog owner and his dog can be in deep communication without use of words. Most of us have heard of dolphins being trapped in a fish net,  who express their gratitude after being cut loose by a diver. I believe all this is true— we humans just get a little carried away by over-dependence on the use of words.

Non-verbal communication is powerful and often overlooked. We all have experienced hunches and “6th sense” warnings, alerting us of danger or conveying respect and positive regard from total strangers speaking in an unfamiliar language.

How does this relate to individuals with DID? Often the body language will be the communication – unadorned and straightforward. This is true whether it is rage, fear or laughter. Again, one can use that body language as a way to open another long-closed door. For example, an alter (male) of one of my patients became angry at home one afternoon and just started banging her head really hard against the floor as she grunted. It was quite frightening for the spouse.

The intensity of the anger and the head-banging didn’t make any sense. There hadn’t been any argument but something had triggered this reaction. Taking the approach of trying to engage what was obviously an alter, the spouse said that he didn’t understand why she was banging her head against the floor but really wanted to understand because it was obviously important to know the “why.”

Taking that body language and grunting as communication rather than as psychosis, allowed the spouse to ask that genuine question. The spouse asked for help to understand what the head-banging meant. Because a genuine question was asked respectfully, and because the spouse was genuinely trying to engage, the 5 year old alter answered in words that it was how he protected the system from the abuser. This didn’t make much sense to the spouse. How was it protective to be smashing your head against the floor?

The alter first glared at the spouse – pretty much indicating that the spouse was obviously too slow-witted to get it. But then, again because the spouse was genuinely trying to engage on the alter’s own terms, the alter was quite explicit that he did the head-banging because he knew it would frighten the abuser. If he frightened the abuser then he was the one in control – not the abuser. He explained that if he hurt the body’s head, they (meaning the host and the family abuser) would end up at the hospital. The abuser didn’t want that because then he would have to explain how the head injury occurred to the police or doctors at the hospital.

When the spouse remarked that it was incredibly brave and insightful to have come up with that on the spot, the alter straightened up his body – head up, shoulders back, the chest swelling with pride. Why? Because the spouse understood and appreciated the hidden message. The spouse understood that banging the head against the floor was a brilliant and sane thing to do by a five year old under the circumstances. It was *not* something crazy. As the alter swelled with pride, the spouse started laughing and then the alter started grinning – a gigantic grin.

A bridge was built on the spot in that way. That was the beginning of the spouse being able to successfully invite a shift in an angry protective alter and turn that alter into a support in healing.

That same patient had alters that would come out at night. Having already developed a relationship with the alter described above, the spouse was told that these were really really little ones. They would come out crying in fetal positions, wracked with sobbing. With the information from the 5 year old alter that these were likely infants, the spouse had them lay their heads on his chest so they could feel his heartbeat, his slow breathing, and his arms softly holding their back, protecting them. In holding them the way a parent would hold an injured infant, these alters would cry for a while and then leave when they had been held enough for that moment. After a few months, they wouldn’t come out sobbing but rather would come out crying just a bit and finally would sometimes fall asleep on the spouse’s chest. Their appearance became increasingly rare until they no longer seemed to need to come out. Nothing else really needed to be done but to be there for them, acknowledging that they had been hurt and needed comforting.

I think we can strive toward communication with alters who do not use verbal communication. Try to be sensitive to their needs, their unprocessed trauma. By being there, being genuine and sometimes simply being still, conveying the willingness to listen and to understand, we may be able to help those with DID accomplish quite a bit of healing.


## When Alters Attack Inside

*Posted on April 7, 2018*

**TRIGGER WARNING**

**The following is in response to an enquiry which I think may have a general relevance to our readers. As the question involves violence within a DID multiplicity system, please note that this post comes with a trigger warning.**

A reader with DID spoke to her therapist about an alter who was attacking small alters inside, including sexually. The therapist told her to get over it because it didn’t really happen. I believe this is a mistaken approach to therapy that will undermine the possibility of a genuine therapeutic alliance with those alters. In my view, it perpetuates the belief in the system that no one believes them about their trauma. This experience is not particularly different from when one angry alter does physical harm to another alter, like cutting or cigarette burning. The alters experience it in the same way – they are under attack, they cannot defend themselves, and they are not being believed.

In establishing a therapeutic relationship with DID individuals, the therapist has to get over their conventional view, their own ties to the logic of a unitary consciousness. They have to accept how the alter that is communication genuinely feels rather than impose their own logic on to his/her patient. To an outsider, an individual cutting himself is hurting himself. It is visible to the therapists eyes. In the context of a DID system, this is often seen as one alter trying to cause harm and injury to another alter. When the damage is not visible to the therapist, that doesn’t mean it isn’t happening. 

I remember the case of Ruth in Chapter 5 of my book. Ruth was hospitalized against her wish to keep her from bleeding to death, because of her continuing attempts to cut herself. She was forcibly kept in a general hospital for 5 continuous months.  She was discharged with the case-note indicating that she was still alive. Despite the clear dissociative symptoms, she was not given a dissociative diagnosis. 

So, how was she able to survive and heal? Most important, she wanted to heal. She interviewed me as a potential psychiatrist to help her. Treatment was quickly instigated through weekly psycho-therapeutic sessions, and by inviting her alters to air their complaints. For Ruth, it took the form of therapy through journaling and discussing the written material she brought to the therapy sessions.  While she never responded to anti-depressant medication, involving years on heavy dosages including in the hospital, her “depression” responded to psychotherapy.  Her cutting was quickly reduced as a result and did not pose any more danger to her life.   So long as she felt hopeful, I never worried that she would succeed in killing herself.

Therapists have to get over the hurdle of understanding that the experience of a DID individual is based on understanding the context in which alters engage each other and the outside world. The most effective way to do this, in my experience, was to engage the alters as they presented. In considering this seemingly “illogical” proposition of one alter sexually abusing another, it could be seen quite straightforwardly as one alter angry enough to want to cause physical and psychological harm to another alter.

The therapeutic task with the angry alter is then to engage that angry alter to understand what function the rage and conduct is serving, why they feel it is necessary to do this. It is no doubt related to that alter’s own trauma and the seeds of healing will be found in that engagement. The therapeutic task with the abused alter is, as always, to engage that alter to allow them to process their trauma. While there is no “one size fits all” approach in helping alters process their trauma, engaging each alter as they present their feelings, their experience, opens the gate for healing. In my practice, I would often suggest that other alters engage with the angry alter, to listen to that one as well as to intervene as a friend just as I would suggest that other alters engage with the abused alter to listen as well as intervene as a friend.

It is not appropriate for an outsider, therapist or otherwise, to debate what they see as the impossibility of one alter abusing another, when they are sharing the same body.   It misses the entire point of the dissociative response.

We, as therapists, have to accept how an alter feels, which is genuine and real, no matter how “illogical” this may appear to an outsider. Without that acceptance, a genuine therapeutic alliance simply will not take root.


## Encouraging Empathy Within DID Systems

*Posted on May 11, 2018*

Recently, I posted a two-part piece on the importance of cultivating and training therapists in empathy. I am confident that if a therapist has empathy, or even the seeds of empathy, that quality can be nourished, enhanced and cultivated which will necessarily increase their capabilities as a therapist. The distinction was made between sympathy and empathy in that piece, identifying them with compassion as critical components in therapy.

An equally important question for DID individuals is that if empathy can be taught among therapist-trainees, can we engender and help cultivate empathy in alters? In my experience, it is definitely possible and can be vital in DID therapy. Let’s examine the possibility of suggesting to patients (and to others with DID) that alters can begin to connect with other alters inside in ways that are both kind and safe.

In practice, encouraging connections among alters needs to be done slowly, gently and over time. Remember, empathy requires the ability to place oneself in the position of the other. Alters are, very correctly, scared of this. After all, it was early childhood trauma on an ongoing basis that is the general origin of DID. For an alter to fully experience and express empathy for another traumatized alter is extremely difficult. Why? Because the system actually does know how terrible the trauma was – it is not just projection and guesswork as it may be for a therapist.

Many alters are frightened of other alters, in particular those that act out internally and externally in extreme ways. They are often frightened of the intensity of the trauma other alters hold. After all, protecting the system’s parts is the reason the dissociative response often produces amnestic barriers. So, disturbing the protection established very early on with the amnestic barriers is something to be done only with the agreement of the alters, which can be gently invited but never demanded.

Some alters are dismissive of other alters, denigrating them for a perceived weakness. Some alters are angry so as to keep their armor up and attuned to potential attack. It is important when you see the myriad of presentations inside a system, even your own, to know that it is not necessary to try to speak to each and every alter about the importance of empathy.

The fact is that beginning a connection between one alter with just one other can have a fundamentally powerful impact on the relationships among all the alters. Why? Because it demonstrates the possibility of safe interaction. It demonstrates the power of simple warmth along with the ability and benefit of gently dissolving some of the amnestic barriers.

Imagine a radiator. It will have a scary quality if your first experience of a radiator is burning yourself on its hot surface. You might never get close to a radiator again out of fear. But, if you are cold, and someone shows you that staying 5 feet away from the radiator will make you feel a little warmer but not too much warmer, you can learn that the radiator isn’t always dangerous at that distance. Then, you can stay 3 feet away and see how much warmth you experience there. When it gets a little too warm, say at 1 foot away, then you have learned the boundary of safety in terms of that particular radiator.

The warm connection of empathy inside can be the same for the alter that is frightened to connect to another. That is true on both sides, the alter considering extending warmth – who may not want to get too close to the trauma material of another alter – as well as the alter considering accepting warmth – who may not want to get too close to another for fear of betrayal or of retraumatization if they open up even a little bit. Encourage the alters to express and to feel the warmth a little at a time, like being 5 feet away from the radiator, or even 10 feet. It is the intention, the aspiration to connect, which opens the gate of and to support.

Don’t suggest that any alter truly try to take on the trauma of another, or to go deep into their imagination of the trauma material held by another. The system knows what is and has gone on, even if individual alters only hold a piece of the memory. Just as with the approach I took with my patients, it is never necessary to pry into the trauma material, just be available to listen to and for what an alter might present. That is enough for empathy inside. 
Pushing further increases the risk of retraumatization. So, go safely, small step by small step, while asking the protectors to watch over the process to ensure it doesn't go too fast. Even inside, [the 5% Rule](https://www.engagingmultiples.com/the-5-rule/) is a key protective mechanism to remember. 

Many alters hold specific traumas or parts of trauma, and have done so since the trauma occurred. In so many ways that is their identity, their reason to exist. The trauma they hold was affixed to them in a dissociative experience, one that no doubt terrified the system. This resulted in the arising of that alter and perhaps others.

While memories may be walled off internally between alters, many alters know of the others, or at least some of the others. Many alters know which alters they want to stay far away from and which ones they might be willing to connect a bit closer to. You can start with encouraging an alter to simply be there to listen to another alter who may be crying, who may need the experience of a kind word inside, who may simply need the experience of not being alone. You are not trying to have one alter fix another, just to confirm a connection – like catching someone’s eye across the room and nodding to them. That connection can be a balm which sets healing in motion. 

In my experience, once alters start helping one another, the rate of healing is tremendously accelerated.  Encouraging an alter to explore the possibility of helping has to come very slowly and very skillfully, a subtly suggested invitation. The initial response is usually a big NO. Why? Because to suggest that alters help each other goes against the foundation of dissociation. It goes against the amnestic barriers that arose originally for protection and to minimize pain.

Even just the idea that there are alters inside that will befriend or at least listen to another alter – that will listen to that sadness, anger, whatever – is extraordinarily powerful. It establishes the sense, correctly, that there is the possibility of comfort and even help 24/7 – right there within the system. It can become one of the pillars that allows for co-consciousness and for eliminating the sharp edges of internal conflict. This is self-empowerment.
