# Advice to Clinicians

## Support group feedback

*Posted on March 27, 2014*

When I received feedback from the founder of a DID support group letting me know that they wished to use the book for a study group, I was delighted. This is exactly my hope – that members of the DID community would access the material for their own healing. To read the material in that kind of safe place – with others in a support community – is a wonderful way to protect oneself from re-traumatization while exploring the paths to healing that are presented in the book. This is something I had not previously considered. It is truly a great joy to hear about this and even more positive that the idea came from the DID community itself!


## The Therapeutic Window

*Posted on April 30, 2015*

The concept of “therapeutic window” is discussed in detail in Principles of Trauma Therapy: A Guide to Symptoms, Evaluation, and Treatment by John N. Briere and Catherine Scott. The therapeutic window, as presented by Briere and Scott, refers to a psychological midpoint between the inadequate and overwhelming activation of trauma-related emotion during treatment. It is a hypothetical target where therapeutic interventions can be most helpful. Psychotherapeutic interventions within the therapeutic window are neither so trivial that they provide inadequate memory exposure and processing; nor so intense that the client’s balance between acceptable memory activation and overwhelming emotion is tipped towards the latter. In other words, interventions that take into consideration the therapeutic window are those that trigger trauma memory enough to promote processing but do not overwhelm internal protective systems such that untoward avoidance responses take over.

To put it another way, interventions that “undershoot” the therapeutic window are ineffective and a waste of time. Those that “overshoot” the window constitute re-traumatization. In the former, the client may avoid returning for further treatment because they feel nothing is being accomplished. In the latter, the client may avoid returning for treatment because, having been retraumatized, they are frightened.

The therapist must remain completely attuned to the client, their verbal, emotional and physical presentations give you the keys to see how far to go and how not to go farther. Each encounter between the therapist and client should be more powerful than the titrated exposure to the trauma within that therapeutic window. In that way, each time a client comes to therapy they will leave feeling just a little bit better than when they came in. This is critical to encouraging their hope for recovery and their further establishing of a therapeutic alliance with the therapist.


## David Yeung Comments on Psychiatric Times SRA article

*Posted on March 25, 2014* 

*This is in response to a recent article denying all aspects of Satanic Ritual Abuse.*

Clinicians should be wary of being drawn into this debate. The real issue is the impact of past trauma into present experience. One should not be sidetracked by a debate about the ontological aspect of SRA and therefore miss the point about Dissociative Identity Disorder.

War veterans reliving PTSD flashbacks are not interrogated as to the accuracy of their traumatic memory, while victims of child abuse are met with scepticism and disbelief. The purpose of psychiatry is to treat patients, not to cross-examine them as if their treatment sessions are taking place in a court of law.

Patients traumatized in childhood decades ago, by powerful abusers and under inescapable circumstances, have difficulty reconstructing their experience from non-declarative memory. In converting that experience into words, it is understandable that they will express it as a memory of satanic ritual abuse. After all, if someone who is conventionally seen as your protector violates you in unspeakable ways, that is close enough to an archetypal satanic experience to be seen, at least, as metaphorically true. There may be no other words to describe this indescribable experience of betrayal. The false memory debate pre-supposes that there is only one “true” memory – one that can satisfy a judge and jury. Perhaps those who are fixated on denying SRA should watch Kurosawa’s Rashomon again.

To call it false memory because it might not survive a court challenge will prevent a psychiatrist from helping patients to heal. People abused in childhood are already convinced by their abusers that no one will believe them, no one will take them seriously. For a clinician to do the same thing is to reinforce that abusive imprint.

After years of scientific and liberal education, psychiatrists should understand the difference between factual and metaphorical accounts. The conversation between the fox and the crow in Aesop’s Fable surely did not take place in an historical provable event but it represents metaphorically a deep truth.

I would not dismiss the possibility of ritual abuse. The current unveiling, surely not complete yet, of international child pornography and child sex slave selling rings promoted throughout the Internet is not far removed from what a victim may say using language of SRA in an effort to communicate their experience.


## The 5% Rule

*Posted on May 28, 2015*

I am glad that some readers are finding my books helpful, and that some therapists are open-minded enough to read them. For patients and their significant others, my wish is that they will find hope for healing in the material. For therapists, my wish is that whatever they find helpful will prove of benefit to their own patients.

I recently received a request for more detail on the 5% rule I discussed with my patients. In Engaging Multiple Personalities Volume 1 page 31, I suggested to a patient that she could try to limit her experience of pain to 5% of the actual memory of pain. In that way, she could begin to relate to the pain while remaining in control and avoid being overwhelmed by it. 5% seemed to give the pain a boundary of tolerability, regardless of that boundary’s illusory nature. Further, if 5% was too much to handle, at that point she could decide to only take on 2%. Again, the idea was to create a vehicle through which she could begin to process her trauma on her own terms -rather than being uncontrollably swept away by the memories.

The notion of 5% is a way of pointing out that a difficult task can be divided into small bits, so that each part can be handled successfully without overwhelming the system.  In concrete terms, if one has to climb a tall mountain, it might seem impossible at the beginning.  By dividing it into 20 sections, each part is only 5% of the whole. That small part appears on its own to be manageable. The next 5 % will be likewise manageable too, and so on. When climbing Mount Everest, even the professional climbers acclimatize by spending time in a series of Base Camps that are each a bit higher in altitude than the prior camp before making the final ascent.

When it comes to pain, one has to use some imagination.  I once treated a patient with severe snake phobia. I applied the 5% rule in this way. I suggested that she could imagine 5% of the fear to be like imagining a snake placed in a locked cage, in a locked room in a locked building, situated in the next city block over.  The next step would be for her to imagine allowing the snake to be brought in the locked cage just outside the locked room, but still being kept in the locked building in the next city block. This amounted to her feeling a certain percentage of the fear of the snake without succumbing to panic. In this way, she was able to have some measure of control. Step by step she was able to regain control of her reactions to snakes.

The important suggestion is that one can use one’s imagination to break down into fractions whatever it is that one is frightened of. As in all behavioural therapy, the key point is generating that sense of control in the hands of the survivor. With control, one is no longer a helpless victim. Rather than being a victim of an onslaught of debilitating memories, the patient (NOT the therapist) is then in charge of allowing whatever amount of the distress to come through for processing.

Even simply talking and planning such a technique with the patient in a secure milieu is in itself therapeutic. It is best to engage the patient to fully participate in the therapeutic procedure. The primary default response to a trauma is helplessness—a sense of loss of control. This approach gives the patient the tools to transform the default response of helplessness into a powerful controlled processing response.


## Advice for Novice DID Therapists

*Posted on August 12, 2015*

If you are a therapist who has never treated DID ...

Is there a point to deny, discount or argue with different alters in a DID patient? Bluntly speaking, the answer is no. While DID/MPD deniers will deny the existence of alters no matter what evidence or experience you present to them, I have seen and engaged many different alters in DID cases. Further external validation is unnecessary to proceed with treatment.

There are two key points to keep in mind when acknowledging the presence of different alters:

1. Alters feel strongly about their individuality. To insist that they are just one identity or personality is going to push them away from the therapist and destroy any possibility of a therapeutic alliance. I accept their way of thinking of themselves as separate individuals. I will not impose my own “unitary” concept of personality and try to convince them that they are deluded or simply wrong. This multiplicity aspect of personality is prevalent in all of us. It is only a matter of degree. When I play tennis, I am acting and feeling like a teenager, trying to hit the ball to the other side so that my opponent cannot return it. It is the “teenager” in me that is playing the game. It is a conceit to think that the teenage quality of me playing tennis is not part of the continuum of experience that includes alters in DID patients.

A therapist should never argue or try to convince a client that he/she does not have different alters. It would be akin to attempting to convince that a schizophrenic patient’s voices are not “real.” However, common sense and appropriate therapeutic demands dictate that clients’ alters should all work out a way to handle the practical aspect of day to day business. Alters should obviously find a way to live in a cooperative way because there is only one body – one cannot go to a party and simultaneously rest at home.

2. When treating a DID patient, unless a therapist acknowledges the presence of alters, treatment cannot even begin. Therapists cannot get anywhere if they insist on ignoring an alter because that means shutting down therapeutic communication. This is so basic but is one of the major obstacles in DID therapy for psychiatrists who have no experience in treating such patients. There is a strongly held but erroneous belief that if a therapist talks to an alter, it is going to make things worse. In fact, the opposite is true. Ignoring the alter(s) undermines the therapeutic alliance. The patient will close down this most important support and gateway for healing. It is the equivalent of telling a non-DID patient that the therapist does not want to hear what is really bothering him/her. 

Once these two points are understood and agreed upon by the therapist, treatment of a DID client is no different from treating patients with most other psychiatric diagnoses. In DID therapy, therapists should focus on processing past trauma, and bringing together the alters so that they learn to live together in harmony and mutual support, like a team of athletes with different strengths and skills all pulling together toward the common goal of healing.

Sometimes a therapist who has never treated DID will be open-minded and even read my books to get started in treating DID. Claiming to have no experience is not a good excuse because DID is not rare. Sooner or later the therapist will see or at least recognize another case of DID. No therapist should deprive themselves of the opportunity to learn to treat DID.

If you cannot find a psychiatrist, any psychotherapist from other disciplines can work with DID patients. Social workers, psychologists and others can equally engage in treating DID. Anyone trained in psychotherapy can treat DID if one follows the simple principle of processing trauma and bringing together the different alters to work as a team.


## Treating Massive Multiplicity

*Posted on June 2, 2015*

Chapter 5 in Engaging Multiple Personalities Volume 1 documents Ruth, who eventually told me that she had over 400 personalities. I treated the fact of such a large number of alters in a low-keyed way. In my approach, it didn’t matter if she had 4 alters or 400. The important point is that the therapy was not dependent on the number of alters – it was dependent on some key general guidelines regarding alters.

Alters usually demand to be treated as separate individuals. That is how they experience their own being. In therapy, integration was not the goal. The ultimate goal is to help all the alters to function as one cohesive unit, like a football team with a common aim of winning the game. I tried to teach them to aim for cooperation, communication, and coordination. The approach was for me to help them to respect each other and encourage them to help each other. This needed to be done without my denying their desire to assert their own individuality.

Initially, there are conflicts that are often expressed quite strongly by alters that are not interested in working with or befriending any other alters. There are usually those that are quite angry with other alters and wish to be violent toward them. This approach requires the therapist to proceed with sensitivity and tact. Without hurting their feelings or telling them to drop their individuality, I would point out to them the need to acknowledge that they should work for the common good because they are all sharing only the one body. This is one of the main tasks in DID therapy, to help alters come to terms with the idea that they have to work together, to sacrifice a small measure of their individual demands so as to be able to work together for the bigger and more powerfully functioning unit.

Eventually, after alters have processed their traumatic memory, the need to be separate individuals often diminishes. As a therapist, it is paramount to control one’s curiosity and undue inquisitiveness as to the individual alters’ personality and characteristics. I never said anything other than the truth that all the alters played a part in saving the system from destruction under the direct assault of the trauma and its after-effects. Therefore, all the parts needed to respect all the other parts.

One must conscientiously refrain from trying to treat each and every alter separately as if you have 400 separate patients. My contact with each of Ruth’s alters was limited to whatever and whoever arose in the here and now of therapy. If one alter was suicidal, I would encourage that alter to come out to address that one’s specific issues, *without demanding that she come out*. It is a delicate balance of neither denying their individuality nor encouraging their separateness. As the trauma is processed, the individuality becomes more and more of a non-issue.

On the other hand, therapy for a suicidal alter must be straight to the point. One can explain to the suicidal alter that she is angry and fighting against herself, whereas the real anger should be directed towards the abuser. It was the pain inside that led her into wanting to hurt herself. I then pointed out different things she could do to soothe and ease that pain. Critically important was to point out that she could use the anger itself as a powerful force for healing and recovery.

Empathy from the therapist goes a very long way. One can seek to motivate other helpful alters to rally to the task of facilitating the healing. Other alters may be assigned the task as co-therapists, or at least to hold the hand of the sad or suicidal alter(s) to let them know they are not alone. 

While therapy has to be flexible and dynamic, it needs to be goal-oriented and task-focused. I conscientiously avoided socializing with interesting, colourful and engaging alters. Therapy is not a chit-chatting social event with alters over a cup of tea.

In this way, even with several hundreds of alters, I managed to complete therapy in 2 and half years with Ruth. It is worthwhile to note that in a follow up instigated by Ruth, she reported that she had not needed support from the mental health system since therapy over 20 years ago at this point. This is a far cry from her history prior to psychotherapy that involved 20+ hospitalizations (one of which lasted 5 months), multiple psychiatric emergency visits and ongoing and unsuccessful pharmaceutical attempts at treating her depression.

This is not to say therapy can always be completed in such a short time. There are tremendous individual variations. Nevertheless, this is a confirmation that DID therapy does not have to drag on for years and years.


## Misdiagnosing DID

*Posted on September 9, 2015*

Psychiatric diagnoses are based on clinical features rather than laboratory tests as in organic pathologies. For example, a patient presenting with a fever might have a common cold, a kidney infection, pneumonia or many other illnesses. It is the task of the clinician to determine what disease the symptom, fever, is resulting from.

In psychiatry, it is necessary to maintain a proper index of suspicion in that same way. When a patient presents with depression, it could be that they are bipolar, it could be that they have borderline personality disorder, it could be that they are in the midst of a divorce, or perhaps they have DID. It is the job of the psychiatric clinician to be open to all of the possibilities as they commence the diagnostic investigation.

Psychiatric disorders according to DSM 5 are based on symptoms, just like fever in the case of Malaria. Treating malaria with fever lowering drugs is akin to treating the depression in DID, which are cases of trauma and dissociation, with prescriptions that do nothing to treat that underlying cause. Just as treating malaria solely by lowering the fever will not cure the malaria, treating depression with anti-depressants alone will not necessarily cure the underlying cause of the depression.

When a patient presents with depression, the answer must not always and simply be an anti-depressant. The therapist must understand, first of all, that depression may simply be a symptom, not a syndrome or disorder, and it is not always a pathology. It is often an appropriate human response to difficult situations.

In my practice, it was quite common to see patients referred to me by other psychiatrists with diagnoses of Bipolar Disorder, Borderline Personality Disorder, and Clinical Depression that have not responded to medication. For those patients, it was almost always because the diagnoses were in error. The referring psychiatrists had focused on one symptom rather than the patient’s overall circumstances.

I believe this is due to a failure in training – a failure that I was subject to for many years as a practicing psychiatrist. I had been taught that I would never see a case of DID because it was such a rare phenomenon. Most of my colleagues, all veteran psychiatrists, never had a case of DID either. Looking back over my 40 years of practicing psychiatry, I would correct that statement to say that most of my colleagues (including me at the time) had never recognized a case of DID. Indeed, many referrals I received included notations of dissociative features being displayed by the referred patient but a refusal to include dissociative disorders as a primary or even secondary diagnosis.

I still remember my encounter with a patient in an infectiously happy mood who came to see me for recurrent spells of depression. Applying the DSM 4 criterion applicable at the time, I could not have been more certain that I was encountering a case of Bipolar Disorder. No one could have convinced me otherwise. I had certainty in the diagnosis and felt greatly relieved. I knew exactly what to do, how to follow the well laid-out protocol of mood stabilizers and so on. With the diagnostic certainty, I was confident that my task was virtually accomplished.

As a result, I never even considered the possibility that what I was seeing in my office was an alter who appeared carefree and happy. A careful consideration of the patient’s life history and early incestuous abuse should have alerted me to the possibility of quite a different diagnosis. In fact, after seeing her numerous times, she disclosed that she had been abused by her father. Rather than raising my index of suspicion, as should have occurred, I simply said “Oh, that’s part of your personal history.” Although my response was in accord with the standard psychiatric practices at the time, it was an abject failure that I did not reconsider the bipolar diagnosis.

Thanks to the bravery of some of my DID patients, I can say with confidence that a more appropriate approach to the “hypomanic” part as a possible alter would have opened the door to healing. My conduct at the time, instead, confirmed for the patient that I didn’t think the abuse history was all that important in the context of the bipolar diagnosis – again this conformed to the standard practice of psychiatry at the time. This was ignorance, dangerous ignorance on my part, and a continuing regret.

I should have understood that her opening up that personal history to me was dangerous and frightening for her. It should have been met with gentle kindness and openness. It should have led me to reconsider the therapeutic approach. There existed an alter who could have connected me to the severe inner turmoil and complexity of a psyche suffering from complex PTSD. That would have further established and strengthened the therapeutic alliance. It would have enabled her healing to have proceeded in a safe, supported and appropriate way.

I believe that many therapists make the same kind of mistake as I did for the first many years as a practicing psychiatrist. One must always be aware of the possibility that by simply labeling a patient as Bipolar or Borderline may mistakenly lead the therapist toward concentrating on a pharmaceutical treatment that will only cover up the real pain of a badly traumatized individual. It is often worse than no diagnosis at all as the patient’s difficulties are both compounded and hidden by the cascading effects of psycho-active medications.

What do I suggest to the current and future generations of therapists? Pay attention to the following research statistics:

The incidence of DID is not rare. According to Lowenstein1, DID may occur at a 1% rate in the general population, which is close to that of Schizophrenia.

The prevalence rate for schizophrenia is approximately 1.1% of the population over the age of 18 (source:NIMH) or, in other words, at any one time as many as 51 million people worldwide suffer from schizophrenia. There is an almost identical rate of prevalence for DID.

Physicians and other therapists are all aware that schizophrenia is not uncommon. Let us raise our index of suspicion about DID as it is just as common, statistically speaking. Just because high functioning individuals with DID exist and are well known, such as Dr. Robert Oxnam, Herschel Walker and others, it is not a rare disorder. In my opinion, the diagnostic bias against DID is connected to the discomfort people have acknowledging the constellation of circumstances that give rise to it: early childhood abuse, dissociation, and betrayal.


## Why some clinicians refuse to acknowledge DID

*Posted on September 18, 2015*

I previously posted on the danger of diagnosing a mental disorder based on clinical symptomatology alone. In that post, I discussed my own failure to diagnose DID in a patient because she presented what appeared to be a classic case of Bipolar Disorder. DID is rooted in early childhood abuse. It seems that many psychotherapists, and others throughout society, prefer to avoid the issue of the rampant abuse/molestation by people across all economic, religious, social and cultural boundaries. To acknowledge DID is to acknowledge the epidemic level of abuse that occurs in one’s own societal milieu.

The purpose of this post is to highlight other reasons for the failure to diagnose DID correctly and, in particular, why clinicians affirmatively choose other diagnoses over DID. During my years of practice, I received many referrals of patients that had multiple diagnoses, usually borderline personality disorder, bipolar disorder and schizo-affective disorders. In many, but not all, there were clear acknowledgments of dissociative qualities indications. Nevertheless, in the referral documentation dissociative disorders were simply not considered in the diagnoses.

I have long puzzled over the fact that there are deniers of DID even among seasoned psychotherapists. I think the crucial issue is that in the experience of many therapists, they have never encountered even one patient with DID. With that background it might be understandable why he/she would reject such a diagnosis. But that should *not* be the end of the inquiry.

In my experience, it is not that therapists, certainly the vast majority of those that referred patients to me, never encounter DID; rather, they simply fail or refuse to recognize it.

Human beings have a predisposition to perceive things in a certain way. In psychological terms, this is known as a perceptual set or a perceptual expectancy Numerous studies confirm that perception is highly influenced by what one expects to perceive. For example, because we are highly attuned to hearing our own name, we recognize it even in a loud and chaotic environment. In a similar way, if we believe that our key has been stolen we will fail to see that key even if it is right in front of us.

Applying that same expectancy analysis to psychotherapists and DID, if a clinician believes that DID is rare, its presentation in a patient will be missed. This happened to me on many occasions before I came to realize that DID was no less common than many other disorders. I needed to modify my diagnostic index of suspicion to include DID as a possible diagnosis as likely as bipolar, borderline personality disorder or schizo-affective disorders.

Another common reason for missing DID is that the DID is hidden behind some other presenting symptom. For example, many patients come presenting with depression. Others may be presenting with sexual or other addictions. Still others may present with difficult so-called character flaw problems like pervasive anger. Therefore, it is important to examine the problem of basing diagnoses on mere symptomology without an appropriate index of suspicion.

By way of example, malaria and typhoid are two different diseases but sometimes physicians are unable to diagnose them properly due to certain symptoms they share in common. In the initial stages, both may present with the following clinical features indistinguishable from each other: high fever, abdominal pain and lethargy. Yet they are completely different in etiology and demand. Typhoid fever is caused by a gram negative bacteria named as salmonella typhi whereas malaria is a protozoal disease due to different species of Plasmodium invading the red blood cells, transmitted via mosquito. Treatment for malaria will not help a patient with typhoid, nor will treatment for typhoid help a patient with malaria. Fortunately, some simple lab tests can distinguish between the two. However, there are no such laboratory tests to distinguish between most psychiatric disorders, such as between schizophrenia and DID.

So, again, one must not end one’s inquiry simply because one has seen what one expected. One can see bipolar disorder in mood swings, but the mood swings might also be different alters presenting themselves to the therapist. Depression may be a disorder, but it might also be an appropriate response to difficulties in life or it could be rooted in DID that is held by one or more alters.

Competent therapists need to examine their own index of suspicion. DID should be included in that index of suspicion when seeing patients with presenting symptoms that are found in common with other disorders, whether it be depression, addiction, schizo-affective disorders, bipolar or borderline personality disorder.


## Alters are not the pathology

*Posted on September 14, 2015*

Many years ago, a fellow psychiatrist courteously wrote and explained why he disagreed with my therapeutic approach of speaking to the alters. He clearly considered this an error that would lead to “consolidating a pathology of dissociation.” He was taking DID as a disease in which the 6 year old alter speaking in a 6 year old voice was seen as the illness rather than a symptom. Effectively, he saw the alter as the pathology that needed to be eliminated. Thus, he viewed engaging in dialogue with the “voice” (the alter) as clearly an unwise practice that would only consolidate the problem rather than eliminate it.

In fact, the correct analytic approach should be to consider that the unprocessed trauma is the pathology, not the alter. The alter needs to be brought back into harmony with the other parts because they are all pieces of the same psychological system.

The treatment of DID is to engage the patient’s experience of having an alter as a separate part. Talking to an alter, acknowledging its presence, is a necessary step to draw that split-off piece of the self back in order to bring the whole system into a functioning unit instead of a group of perpetually conflicted and competing parts (alters).

This means that the therapist must be open to the fact that a 6 year old alter in the body of a 46 year old adult is not a symptom to be eliminated. Rather, it is a separated part of a wholeness to be healed, like a fragment of broken bone. With a broken bone, it is the fracture that is the pathology, not the bone fragment. And just as with a fractured bone, the broken piece that manifests as an alter is not garbage to be excised and thrown away. Treat the brokenness, which is the unprocessed trauma, don’t denigrate it.

A fractured bone can become quite strong and functional once it is healed – although never exactly identical to the bone that has never broken. It doesn’t need to be. In that same way, once a DID system is healed, it can likewise become strong and functional – although never exactly identical to a mind that has never been fractured in that way.

I learned over the course of 40 years of practicing psychiatry never to ignore or try to get rid of an alter. This is true however vicious an alter may initially present. Even the most angry and self-destructive alters can be seen as a repository of highly charged energy, worthy to be engaged and brought into harmony, not eliminated. Often they hold the keys to the knowledge of how the system protected itself under the pressure of the trauma as well as clarifying the path to healing.

All of the alters hold gems of insight. With a proper therapeutic alliance, they will show the therapist those gems without interrogation, prodding or challenge. Kindness and connection open the doors to healing. It is the task of the therapist to invite the patient through those doors. Just as setting a broken bone in its proper position will allow the fracture to heal, creating the proper invitation to the alters will allow that fracture the is DID to heal.


## DID and Schizophrenia – Part 1

*Posted on October 1, 2015*

This is a short theoretical and philosophical discussion concerning whether or not there is any difference between DID and Schizophrenia in terms of classification, diagnosis or treatment. There are not necessarily any confirmed definite answers, but I believe there are guideposts to consider.

Schizophrenia is traditionally classified under a group of functional psychoses while DID belongs to a group of neuroses. In the traditional understanding of psychosis, the patient may lose touch with reality. In neurosis, the patient retains some acknowledgment of his illness. From this traditional perspective, Schizophrenia and DID are two entirely different kinds of mental disorders.

The term schizophrenia was conceptualized by Eugene Bleuler and further refined by Kurt Schneider (1959), a German psychiatrist whose delineation of “first rank symptoms of schizophrenia” remains widely adopted. Unfortunately, Schneider’s primary criterion for schizophrenia is the experience of “hearing voices.” Hearing voices is how those with Dissociative Identity Disorder – especially pre-diagnosis – often describe their experience of alters expressing themselves internally. It is crucial to consider as an analogue the fact that having fever and abdominal pain are symptoms common in both malaria and typhoid. In other words, just as malaria and typhoid are two completely different physical illnesses with symptoms in common, Schizophrenia and DID are two distinctly different mental disorders with symptoms in common.

The first rank symptoms of schizophrenia are summarized in the following mnemonic of **ABCD**:

* Auditory hallucinations: hearing voices conversing with one another, voices heard commenting on one’s actions;

* Broadcasting of thought: a form of auditory hallucination in which the patient hears his/her thoughts spoken aloud;

* Controlled thought (delusions of control);

* Delusional perception.

Patients with dissociative identity disorder may report “hearing voices” even more commonly than patients with schizophrenia. If one is trained to presume that hearing voices is always an hallucination, then most therapists will jump to the conclusion that the correct diagnosis is schizophrenia. They will mistake the auditory manifestation of internal conflict between the alters to be an auditory hallucination that comes from nowhere, points to nothing understandable in any context, and is completely disconnected from reality.

Spiegel and Loewenstein have commented on the considerable overlapping of the symptoms of the DID and Schizophrenia. But, if we follow Schneider’s diagnostic criteria with that presumption, we will have to come to the inclusion of DID within the group classification of schizophrenia. This is despite the fact that they are as different as apples and oranges in terms of classification (psychosis vs neurosis), diagnosis and treatment.
In my experience in treating both schizophrenic and DID patients, the hearing of voices in DID is quite distinguishable from the auditory hallucinations of a schizophrenic. This and other mistaken applications of the ABCD as applied to DID patients are discussed in Volume Two of Engaging Multiple Personalities.

A crucial difference between the two disorders is that schizophrenia usually causes the patient to be highly impaired in his/her thinking. Schizophrenic impairment is generally quite pronounced and leaves the individual severely dysfunctional. In the case of patients with DID, some can be extremely high functioning, while others can barely get along, but most have alters that are usually quite capable of relating to the outside world. Nevertheless, they may be impaired in other ways, such as having co-morbidity of drug addiction and/or alcoholism in one or more of the alters. As a side note, this may be why many DID individuals come to the realization that they may have DID in the course of addiction treatment – whether at AA, NA or at addiction treatment facilities.

Generally, specific diagnostic criteria are followed in making a diagnosis, This is necessary for consistency and uniformity so that treatment guidelines can be applied correctly. It is a key tool for clinicians but like all tools, one must know when and how to use it. When one fails to recognize that there are many psycho-pathologies that display identical symptoms to DID on first, second or even third encounters, the clinician will have failed to use the tool of the DSM properly. This highlights the importance of maintaining a proper index of suspicion for all illnesses having common symptoms – physical and/or psychological – until one or another has been definitively excluded or confirmed.

Simply put, a patient presenting with “hearing voices” may be schizophrenic but, based on the percentage of incidence in the general population, may be equally likely to have DID. This highlights the limitations inherent in relying on one or two symptoms alone in making a diagnosis for mental disorders. One must examine the entire milieu of the presenting patient. This is completely analogous to the danger of diagnosing either malaria and typhoid based on fever and abdominal pain alone.

It is an inconsistency in logic to force a psychiatrist to choose whether to follow Schneider all the way and call DID a true schizophrenia with dissociative features, while understanding that in nosology (classification in medical science,) Schizophrenia is a form of psychosis while DID is a form of neurosis. At the moment, I am merely explaining the dilemma in psychiatry. While I have no definitive answer to that dilemma, I do have my experience of treating patients with both disorders that I relied upon in my practice.

I can say, definitively, that when the logical inconsistency is ignored, psychiatrists are more and more led down an incorrect path of treatment for individuals with DID. This has dire consequences that may take years to play out, investigate and correct. Unfortunately, for many patients, the dire consequences mean more trauma is inflicted in the attempt to heal as a result of the psycho-pharmaceutical blinders the incorrect diagnoses place on the therapists, in the patient files, and on the patient directly. Having a schizophrenic patient talk to the voices he hears will exacerbate his Schizophrenia. Having a DID patient engage in communicating with the voices of alters is part of the necessary treatment of his DID disorder. So, it is crucial to be able to distinguish the two in order to properly treat, and not harm, the patient.


## DID and Schizophrenia – Part 2

*Posted on October 1, 2015*

Colin Ross, a pioneer and authority on DID, proposes to consider DID as a type of schizophrenia with dissociative features. He made this decision because “two thirds of people with DID meet structured interview criteria for schizophrenia or schizo-affective disorders.” (p. 131 Trauma Model Therapy, Ross and Halpern (2009).) While this approach enables one to conform to the DSM Criteria, in essence it is making a DID diagnosis more palatable to the general community of psychiatrists who are more comfortable identifying patients as schizophrenic than dissociative.

Despite my view presented in part 1 of this topic, of the logical inconsistency of merging a disorder that is classified as a neurosis (DID) with a disorder classified as a psychosis (Schizophrenia), there may be other tangible benefits to Ross’s re-definition of DID as a schizophrenia subtype. Such an inclusion of DID as a subtype of schizophrenia may prove effective for heightening awareness of DID within the psychiatric community. As such, it may be very helpful to DID patients, so long as the therapy is correctly targeted to the DID rather than the conventional (and drug treatment related) approach to schizophrenic patients. Without that refinement in treatment understanding, this may prove difficult for practitioners to truly grasp and implement. Below, I have paraphrased Ross’s explanation of this view, and as such, any error in the paraphrase and explanation is entirely my responsibility.

1. “A proposal of having a dissociative subtype of schizophrenia facilitates the technique of talking to the voices, otherwise therapists will never talk to the voices.” This is a reasoning that may have wide benefits in the treatment of DID, if it enables psychiatrists to grant themselves the permission to indeed engage directly with alters.

2. “A large number of schizophrenic or schizo-affective patients do not respond to conventional treatment using medication. The ethical burden or political barriers of talking to the voices are reduced when conventional treatment has not worked.” This is a subcategory of 1 above with an important added benefit of a specific criteria indicating the need for directly talking to the voices – that the medication that has been proven to work with schizophrenics has not worked for the patient in question.

3. “Talking to the voices often works.” As I said before, the proof is in the pudding. It seems to me the main purpose of including DID under the broad rubric of schizophrenia is to remove mainstream psychiatry’s roadblocks to the technique of direct engagement with alters. It is my hope that the more psychiatrists experience the treatment benefit of speaking directly to alters, the more they will understand the efficacy of that approach in healing the trauma that is at the root of DID.

Returning again to the ABCD of schizophrenic symptomatology, when speaking to the voice(s) respectfully, a genuine schizophrenic will likely respond with a statement that indicates a wide gap in his connection to reality while DID patients respond with contexts that make the content understandable in that specific context. The statement from the patient could be as simple as “ There is no way I can speak to you.” A true schizophrenic may give an explanation along the lines of “The clouds this morning were shaped like pumpkins so clearly I am unable to communicate with you.” No matter how you go at that kind of response, there isn’t a bridge to enable understanding. A DID patient would say something quite different that does indeed give a context that enables understanding.

This example comes from a DID patient that trusted me enough in our first meeting to tell me, unprompted, of her abuse history. Then, in a somewhat different voice, shd immediately said that she couldn’t continue therapy because there was no way she could speak to me. This made no sense as she clearly had just spoken to me on an extremely deep level revealing core trauma issues. A few moments later, when I asked why she felt she couldn’t speak to me, she gave the context: She had been abused by someone named David. Therefore, she (or one of the alters then presenting) simply could never trust me nor anyone else with that name. I immediately understood the issue and did not argue. Instead, I referred her to another therapist with a different first name.

Nevertheless, I could have mistakenly convinced myself of an ABCD analysis fairly easily. I could have presumed that the different sounding voice telling her she could never trust me was an auditory hallucination she was simply describing out loud, the non-trusting voice was broadcasting thought to the “actual” patient, the non-trusting voice was asserting control over the thoughts of the “actual” patient, and finally that the “actual” patient had the delusional perception that I was irrevocably related, solely through the link of my first name, to an abuser.

While this ABCD analysis may seem trivial or specious, I saw many such analyses in patients diagnosed as schizophrenic that were referred to me – even as their files indicated strong dissociative features. The impact on such patients of the incorrect diagnosis followed by the impact of inappropriate medications – often over long periods of time – was incredibly harmful to the patients and their families. 

I included a few examples of success using the approach of speaking directly to alters in Volume One of Engaging Multiple Personalities. I also included failures when that approach was not used. Without talking to the voices, the patients who succeeded in healing would not have stood a chance of any recovery. In Volume Two of Engaging Multiple Personalities, I make recommendations to therapists concerning implementing the technique of direct engagement with alters.

Again, it is my aspiration that more therapists will at least explore directly communicating with alters in patients with DID, or suspected cases of DID, so that they will have their own experience to consider. They can then make their own assessment as to “the proof in the pudding.”


## Characterizing DID: Illness or Injury?

*Posted on October 19, 2015*

Language has power. Whether you examine it from the point of view of ordinary communication, advertising, or threats, words and how we use them have tremendous impact – some of which is intentional and some of which isn’t. This is because the words are chosen based on the experience of the speaker/writer while the impact of the words is based on the experience of the listener/reader. For those with DID, words are tied intimately to the body language of the abuser. For people without DID, they often fail to understand the power that words have to trigger retraumatization – because they fail to understand the physicality, violence and/or threats of violence, that accompanied those words.

Given that a word may have one meaning to one person and be experienced quite differently by another, I want to look at the use of the terms illness and injury in DID. I had not thought about this before, but in a DID Facebook group, one member defined himself as injured, not ill. In considering the refusal to consider himself ill, going against most therapeutic models, he was quite clear: he had been injured. He advised me that this distinction came from a therapist at Del Amo’s National Treatment (Trauma) Center. I believe this critical distinction is both accurate and subtle.

Illness and injury are often used as synonyms. Conventionally speaking, this is not usually a big deal but while they can sometimes be used interchangeably, they are not exactly the same. An illness is something that people understand to be bacterial, viral and, at least subconsciously in almost every circumstance, potentially infectious. An injury is something that is the result of some external force exerted on a person, whether deriving from a fall, a chemical, or something done by one person to another. This is not something that people, even subconsciously, generally view as potentially infectious.

The truth is that the trauma of child abuse is not an illness that arises due to a microscopic life form such as a bacteria or virus invading one’s body. Those attack one at a cellular level. The body’s defenses rise to fight the illness, sometimes successfully on its own as in a common cold, and sometimes successfully with medicines.

Child abuse is an external force – physical, psychological or, often, both – that attacks and injures the child as an entire individual. In situations of child abuse, there is no cellular defense that can rise to fight the abuser. In the case of trauma resulting in DID, the mind’s defenses rise in the form of multiplicity to survive the external force of the abuser.

When someone breaks a child’s arm, the broken arm is classified as an injury. If the bone protrudes from the break and becomes infected, the infection would be considered an illness but the broken bone would continue to be classified as an injury. In fact, the root of the illness (the infection) was the injury. We must keep this distinction in mind when examining the etiology and resultant manifestation of DID.

Characterizing DID as an injury, rather than an illness, has the potential to benefit those with DID as it is a more accurate classification of the source of DID. Thinking of DID as an illness implies, conventionally speaking, that one needs rest, medicine and homemade chicken soup. But, no patient with DID got it because someone sneezed near them in a crowded bus, or because they ate at a restaurant where the chef didn’t wash his hands before cooking. No patient got DID because they stepped on a rusty nail. Patients manifest DID as a result of very real injuries that are unrelated to the microbial world.

This re-characterization may enable those with DID, and those without it that engage them – whether therapists, family, friends – to see them the same way one would see a person who has a broken leg. That person, perhaps with a cast, needs extra help. They need to be protected from anything or anyone banging into the broken leg intentionally (an abuser continuing the abuse) or by accident (a non-abuser unaware of interpersonal triggers). Just as a bone takes time to knit as part of the healing process, DID takes time to process the trauma as part of its healing process. Let us understand the injury so that we – patient, therapist and supporters – understand the importance of protecting both the mind and body during the course of healing.


## The Body Keeps The Score

*Posted on November 5, 2015*

If someone breaks a leg, is burned, or is otherwise physically injured, it is easy to see. It shows right there on the surface of their body. Maybe they are wearing a cast, or have a scar, or some other clear sign of damage. But when someone has been traumatized, it is not always so easy to see. Nevertheless, it is there – locked in the body. Often you can see it in someone’s posture, in the way they flinch when a sudden noise surprises them, or in the way they try to hide from a gaze.

We all lie to ourselves and to others, usually in small ways that are not a big deal like, “I am walking out the door right now” when we are still inside getting on our shoes. But we are capable of lying in ways that are quite dangerous, to ourselves and others. Why is this important to understand when dealing with trauma? It is important because lying is conceptual, it is manipulating thoughts and strategies. While the mind can do that quite easily, the body cannot. The body doesn’t operate like that. When working with trauma, remember that words can be deceiving. Words can misdirect the attention both of the patient and the therapist. Instead, trust the body. The body doesn’t have the capacity to lie. The truth is locked into the body, and the body will confirm the words that are true.

Memories of early childhood trauma usually do not come in logical, sequential verbal narratives. This is because it is mostly implicit memory rather than explicit, demonstrative memory. Explicit memory is simply not available when abuse happens in infancy, when it happens to you as a toddler, or when you were a young child. In other words, when the abuse occurred before a child’s developmental unfolding of logic, of conceptual grasping of reality and thinking, one cannot expect to recall it as if describing last night’s television show that you watched as an adult. Abusers count on this, knowing that the child will be unable to express a logical, sequential and, for the most part, fact-checkable explanation of their pain – now or in the future.

As a psychiatrist, my primary concern was with treatment, with healing an injured patient. For both the patient and therapist, my advice is to refrain from searching for a logical, sequential, and verbal expression of the abuse experience. This is personal experiential stuff. If your body is telling you that you were abused, that is the foundational truth. Searching for confirmation of details is not nearly as important as trusting the truth held by your body.

How it happened, when and where it happened, are less relevant unless you are still in the physical orbit of the abuser. Trying to force the implicit bodily memory of abuse into an explicit narrative memory will likely cause further confusion and doubt. The body will allow access to the implicit memory when the patient feels safe enough to permit it, or when there is enough stress that the patient’s ability to suppress the implicit memory is overwhelmed.

When the implicit memory arises, don’t dissect or argue with it. It is true on its own foundational terms. Appreciate the wisdom of the body in keeping a record of the trauma, and the wisdom of the child to have survived the abuse. Allow the memory to be as it is, to be expressed as needed, but this time in the safety of the therapeutic environment. This enables the patient to start to experience the distinction between an explicit memory of the past and the present discharge of implicit memory.

Practice the “here and now” formula. In short, you are, at the time of this one breath in the therapist's office or in your protected place at home, safe and whole. In the midst of implicit memory, breathe. You are breathing anyway, so why not pay just a bit of attention to it. In the moment of this very breath, one can access a powerful feeling of stability. Practice just experiencing that feeling without trying to extend it, manipulate it or otherwise hold on to it. Why not try to hold on to it? Because it is now the next moment, the next fresh breath, the next opportunity to experience safety.

The more often you can experience the safety of a here and now moment, the more that experience – on its own – will leak into your everyday life. Work on creating the habit of noticing your breath when any past difficult memory starts to arise, implicit or explicit. Each time you connect with that safety in the breath during the remembering, whatever happened in the past begins to weaken its present grip on you. 

It is a process of very small steps. The past will not suddenly lose its power, but it will begin to do so gradually. With processing the trauma gently, slowly and safely, the past will cease being so potent. It will become more and more like an ordinary memory, with limited impact on the present.

As the trauma is processed in therapy, the body will shift just a bit, letting go a little bit. What I said to my patients was that I wanted them to leave my office feeling just a little better than when they came in. In that way, there was no pressure to have a giant breakthrough with the attendant pitfalls of loading such pressure on them. Instead, my patients would make small gains without retraumatization. It was with gratitude that I could see a patient walk out of the office a little more gently, a little more erect, and feeling a little more safe inside, than when they entered.

This is not to say that patients were on a continuously uphill trajectory of healing. Everyone’s life has ups and downs. This is true whether seen over the course of days, weeks, or months but also over the course of minutes, at times. So, each session with a patient was a new starting point – how did they come in that very day and how did they leave.

The body keeps the score, and communicates it every moment. Be open to its messages. 


## Guidelines for Therapists On First Encounters with a DID Alter

*Posted on December 9, 2015*

I am writing this because, in my psychiatric practice, I made many mistakes over the course of learning to work with DID. From the perspective of having been retired for the last 9 years, I have reviewed my patient histories so that others may learn from those mistakes. This is the core of my purpose in publishing Engaging Multiple Personalities Volumes 1 and 2.

The education and training I received as a psychiatrist gave me no clue as to how to identify and treat DID patients. In particular, there was no guidance or even discussion of how to relate to a DID alter that might appear in a client session. Because the first encounter with an alter is critical to establishing the necessary therapeutic alliance required for treatment, psychiatrists and other therapists need to be aware of the pitfalls of not being prepared for such an event as well as the benefits that can arise from proper preparation.

In general, DID is rarely diagnosed during the first many therapeutic sessions. According to various authors and studies, most DID patients are only diagnosed after cycling in and out of the mental health care system for several years. This is because, unlike other disorders, DID cannot be discovered through questioning or “digging out” information from the patient.

The foundation of therapy is understanding that the diagnostic procedure is a mutual process: The therapist is assessing the patient just as the patient is also assessing the therapist. Until the patient feels safe with the therapist, and thinks the therapist is or may possibly be trustworthy, the patient is not going to share their innermost secrets or confidential material with the therapist. The DID patient, in particular, due to amnestic barriers between the host and alters, will likely be barred from even being able to access that information. Through decades of experience interacting with people, alters are hyper-vigilant in evaluating who is likely or unlikely to understand their plight. They will not risk being ridiculed by someone unlikely to listen with empathy, although they may conduct themselves with aggression if they feel threatened by the therapist and/or therapeutic environment.

In the event that the DID system deems the therapist worthy of being shown an opening to those innermost secrets, an alter may suddenly “jump out” in the middle of a therapeutic session. In such a case, at least for me in every case in which this happened, the therapist will likely feel “a shiver up the spine” sensation. It is a somewhat indescribable experience. To see a little boy suddenly appear in the body of a 45 year old woman in a business suit, with a young boy’s posture, manner of speech, and emotional presentation, amounts to more than a simple surprise. I developed a code of behavior for myself to follow when first knowingly encountering an alter.

These are the rules I established for myself (the therapist) in such a situation. I hope they will be of benefit to others. 

1. I shall remain stable in my own mind, calm and non-reactive.

2. I shall treat the alter with respect and appreciation that he/she is willing to be seen by me and to talk to me directly.

3. I shall contain my curiosity and refrain from asking for a complete personal history of the alter as that could be interpreted as an interrogation.

4. I shall just wait in a silence of empathy. The alter will likely tell me all he/she wants me to know, with minimal leading questions.

5. The ultimate guideline of decorum is that I behave as if I were being introduced to a new person at a social event: I metaphorically shake his/her hand and sincerely say, “It is nice to meet you.”

The most common mistake therapists make is based on the idea that getting rid of the alters is the prime goal of treatment. In fact, the therapist should realize that the appearance of an alter is a golden opportunity to access and clarify the confusion created by the dissociation. The alter is the main path, the highway so to speak, to access the information needed to enable the alter(s), and the system overall, to process the trauma. Because of amnestic barriers, in many cases the host is not even cognizant of the abuse history. The alters hold the keys to the mystery of what is hidden behind the compartmentalization of the alters, what is being blockaded by the amnestic barriers in the personality structure of the patient. 

Avoid seeing the appearance of an alter as the pathology. The amnestic barrier of dissociation is the real pathology. The priority now is to get acquainted with that sequestered part, which is essential in the healing process. That part may hold much information about the abuse history. Be prepared that there may be an abreaction in detailing the abuse history. So, do not demand details of the trauma and do not provoke the patient to recount them. Letting the alters feel comfortable and secure enough to establish a proper therapeutic alliance is the best, quickest and safest approach to avoid retraumatization. With a proper therapeutic alliance, therapy can generate a positive cathartic experience. Without it, there is only retraumatization.

The first question to ask is not about the personal history of the presenting alter. Rather, it is to find out the age and function of this alter. The age is important so that you use language that is age appropriate to the alter. If the alter doesn’t wish to say their age, then take your cue from how they are speaking to you in terms of how you respond to them. In my experience, the alter will usually tell you whether he/she is, for example, a protector, a persecutor, or perhaps a fearful and suffering child still holding the abuse memory so that the system can function in some capacity without the constant burden of the trauma. The alters generally are quite aware of their function, and sometimes can phrase it exactly in that way.

It is critical to understand that an improper reaction on the part of the therapist can lead to disastrous results and will probably close off any future communication. The unwary therapist taken by surprise may make inappropriate demands when a 45 year old patient starts behaving like a toddler, and blurt out an admonishment like, “Don’t play games with me. Act your age. Go back and sit on your chair.” In other words, harshly denying the alter right in front of you! Such a reaction, spontaneous or otherwise, is negating the person-hood of what appears in front of you. There can be no therapeutic alliance if you deny that alter. 

An alter sincerely considers him/herself a separate identity. Why not just accept the alter on his/her own terms, exactly the way you would when meeting any patient who first comes into your office? No therapist can dismissively brush off a client and expect to work with that same client in any genuine way. You are going to have to work with this alter so treat him/her respectfully. This is the first rule. 

In chapter 1 of Engaging Multiple Personalities Volume 1, the suicidally-depressed woman patient in her business suit suddenly morphed into an arrogant and proud 5 year old boy, boasting about his bravery and dismissing me as an idiot. I reacted calmly, and respectfully thanked him for talking to me. I addressed him in a matter of fact way inquiring for his name and purpose in being there. The result was to establish a therapeutic alliance with that alter but also to all the other alters that were listening in and watching. It was the key to the system preparing to trust me.

Conventionally speaking, of course the boy is not a separate person. But we are not meeting the alter in a circumstance where a government ID is required for entry into our office. We are talking about meeting an alter in the context of psychotherapy. Psychiatrists should have the flexibility of mind to accept that if there has been severe ongoing early childhood trauma, DID and the consequent appearance of alters, is reasonable, logical and appropriate to the circumstances. In this context, it is ridiculous to hold on to some argument about whether or not alters truly “exist” at all!

Don’t argue with an alter, trying to convince her that she is really the host. You may be legally correct but therapeutically it will be a disaster. We need to remain focused on what works as therapeutic intervention for healing from such trauma rather than trying to force our understanding of our own experience onto the patient.

Therapeutically, the boy alter should indeed be treated as a person in need of healing in his own right. For those therapists that simply cannot wrap their head/mind around the notion of an alter, perhaps an analogy would be helpful. To refuse to treat the DID patient because the alters are doing the talking rather than the host that you think you should be speaking with is ludicrous. It would be like saying you won’t treat a mute patient because they can’t tell you how they contracted their illness. You would not feel justified in denying treatment to a mute because someone else in their household told you they were running a fever, vomiting and sobbing all night long.

Please respect the bravery of the alters to come out and communicate directly. Anything other than that will ruin the therapeutic contact. Treat the alter as if he or she were a completely separate identity and the result is that you will benefit all the others, including the massively unhappy frightened host.

The other common mistake is to be anxious to learn the details of what is hidden. In the past, therapists were so focused on getting that information, on an almost gossip level, that injections of sodium amytal, hypnosis, or outright interrogations were used. Instead, by preparing the alter by letting him/her know that you are ready to listen, and providing a milieu of reassurance and support, a cathartic experience will naturally follow. You will get all the information you need to conduct psychotherapy.

There is no need to push. A cathartic experience is only therapeutically useful if done in a secure environment making sure the patient is not re-traumatized in the process. It should be done in a gentle way, as if the therapist is holding the hand of a child revisiting the trauma scene. The role of the therapist is bearing witness to a crime often committed decades ago, guiding and comforting the survivor as he/she goes through the journey once more, but this time with the critical difference being that he/she is no longer going through it alone.

Another task the therapist has to perform is to gently remind the survivor that the “here and now” is where safety is found. This has to be repeated many times until it hits home. There are all kinds of ways to convey this message. Mostly I would point this out through the “touch sense” (the kinesthetic sensation), reminding the alter that the traumatic experience happened in a different place, at a different time, and with people that are not now in the room. Often the alter is stuck in the past, usually decades past, and feels surrounded by the enemies that were the original abusers. Replacing the palpable fear of the past with a comfortable bodily sensation of warmth and relaxation, of heaviness in the limbs and so on, is often quite helpful. The therapist is now helping the system process the PTSD symptoms. This pointing out of “the past and the present” is essential. I would use all kinds of signs and clues to point out the passage of time and the difference in location.

Trust your own experience but be prepared so that you remain stable should an alter jump out to meet you. Know that it is a sign that the patient is showing his/her trust in you. The alter is giving you, the therapist, the chance to prove that you understand and will treat the alter with respect and acceptance, that you will not laugh at him/her, and that therapy will now take a positive turn. The alter is sharing with you a deep secret. Don’t waste this golden opportunity for therapy. Do the right thing!


## When Patients Present Memories of Abuse

*Posted on December 29, 2015*

For most people, and for many therapists encountering DID patients, the first question that comes to mind is whether or not to take the reported memories of abuse to be truth or fantasy. But, there is an even more fundamental question that is at the heart of the matter: *Why* is that the first question for so many people, whether they are trained as therapists or not?  

In my experience, it is because most people simply don’t want to believe that another human being would do something so evil to an infant, to a toddler or to any small child. People don’t even want to believe such things when it is adults doing evil to adults. This is clearly shown by the disbelief during World War II of the initial reports of the concentration camps, of the genocide in Rwanda, and of the Cultural Revolution in China – among other horrific events. And so, people continue to suspend belief, and such horrors continue without protest, until the evidence overwhelms the bias against looking at the evil of which human beings are capable. The same is true with child abuse.

The raw unvarnished truth is that the abuse of children, physical and sexual, happens. The raw unvarnished truth is that such evil has happened in the past, is happening in the present and in all likelihood will happen in the future. The terrible consequences echo throughout the life of the child with ramifications in future generations in that family and for all of society. This is clear for anyone to see, if they are willing to actually look at the abuse and its cascading effects.

Consider the inclusion of fantasy as part of that first question arising when one hears a tale of abuse. To the abused individual, the use of the word fantasy, whether it is said out loud or is expressed in the subtext of a therapist’s body language, can only sound offensive and demeaning. But still worse, it is a confirmation of the ongoing fear ingrained by their abuser that no one will believe them that such things happened.

It usually takes months of waiting to see a specialist, after perhaps years of gathering the courage to tell a doctor one’s innermost private and excruciating history of early sexual abuse. How would you feel if you were finally able to disclose even a hint of the trauma, and then consider how you would feel if the person you are looking to for healing and support, the person in authority evaluating your trauma history, is hesitating as they consider whether or not your memory is some kind of fantasy. It is important to know that they are generally not hesitating because they think you are lying. That is a second step. They hesitate because they simply don’t believe that another human being, particularly a parent or close family friend, could or would do such a thing.

But, no therapist can establish a genuine therapeutic alliance with a patient if they cannot listen deeply to such trauma material, remaining present without judgment. This means keeping one’s own mind stable without doing an on-the-spot calculus concerning the details of the patient’s recounting of abuse. Forget the calculus, you will get the truth of the trauma far more directly and accurately by remaining fully present and grounded for the patient. In that way you can see the totality of the context, presented verbally as well as in body language. The assessment needs to be about whether or not there has been trauma is the point, not the details.

My advice to therapists is to sit still and project genuine empathy, empathy based on understanding that any individual talking about being abused has experienced trauma. As with any memory, traumatic memory does not need to be 100% accurate in its detail because it will be accurate in its context.

Look at an ordinary memory, for example my memory of my childhood bedroom. I remember it as being quite large. There is no doubt that if I were to walk into that bedroom today, it would appear to be quite small. But no one would challenge my memory of that bedroom as being fantasy. It would be taken for granted that when I was a small child (the context of the memory), I would definitely have experienced it as much larger than I would experience it as an adult.

So, when listening to a patient’s memory of trauma, particularly a flashback of trauma, don’t be stuck on proving or disproving “fantasy.” To proceed with therapy, it is enough to know that there was trauma that is reaching into the present and trapping the patient in its past.

The use of the word "fantasy" can be traced back to the very beginning of psychoanalytic theory. When Freud formulated his theory of neurosis by the end of the 19th century in Vienna, he had already encountered many patients who talked about early sexual experiences with their fathers. He privately wrote to a friend that it was a highly significant discovery, like discovering the source of the Nile. The discovery suggested, for the first time, that there was a causal link between hysteria and early childhood sexual molestation.

When Freud delivered his first lecture on this causal connection, the academic and medical authorities were quite unreceptive to this discovery. He explicitly used the terms incest, rape and gross sexual abuse in describing the experiences related to him by his patients. Krafft-Ebing, then one of the most prominent physicians of the time who was senior to Freud both in age and professional stature, described Freud as “spinning a fairy tale.”

Having felt the ice-cold response to his discovery, Freud then changed his theory and used the term “fantasy” to describe the recounted sexual experiences he heard from his patients. He then postulated that it was a kind of wishful thinking that infant girls had for their father.

There have been many explanations for this change in his view: Was it beyond his imagination to believe that these molestations in fact took place? Unlikely, as his original presentation was quite explicitly about molestation, not imagination. Did he change his words and his mind to ensure the survival of psychiatry in the harsh intransigent academic world of Heidelberg and Vienna which at that time was the center of science and medicine in the Western world, or perhaps as a way to preserve his own reputation in order to be able to continue his work? Possibly. Was he afraid to force a confrontation with leading lights of society whose daughters told him of having been abused, a confrontation he might easily lose? Quite possible given that this is something that continues to happen up to this very day, when people are terrified to confront abusers that are leading lights of today’s society.

Regardless of why he changed the theory, and whether or not he then reverted to his original view, his use of the terms “seduction” and “fantasy” enabled society and the abusers to infer participatory intent in the abused children instead of forcing an acknowledgment that the abuse was exactly what it was – rape, incest, and assault, just as he had originally characterized it.*

Later, much later, psychiatrists like Judith Hermann, in her extremely clear and invaluable book “Father-Daughter Incest” published in 1980, elaborated the truly sinister aspects of such early childhood sexual abuse experience.

Today, we should correctly appreciate Freud’s discovery of the link between hysteria and the psychological experience of a patient’s childhood. At that time, it was well beyond the imagination of others. People were then, and many still are, stuck on searching a biological root for the phenomenon which, in Freud’s time, was called hysteria. There are still psychiatrists obsessively denying the impact of early childhood abuse on adult patients as they search for a biological cause of the mental phenomenon that results, whether it be deemed hysteria, DID, PTSD or other diagnoses.

Based on my clinical experience, the odds are that Freud’s patients were indeed victims of incest, sexual assault and abuse. As the studies and news reports continue to highlight the ongoing patterns of molestation across religious, cultural and ethnic lines, it is a phenomenal disservice to patients to presume as a therapist that there is a burden of proof a patient must meet before the therapist is willing to try to establish a therapeutic alliance. The moment such a burden is placed on the patient, the ground for a therapeutic alliance is likely poisoned.

Sit still, be kind, project empathy. A patient will experience anything else as the therapist assigning himself the role of judge and jury. Remember that no memory is foolproof, no memory is incontrovertibly accurate in all details. But also remember that the heart of the matter, the energy of the memory, is accurate in context. Don’t fear acknowledging the context; sit still and listen deeply.

* *“Assault on Truth” by Jeffrey Masson (1984) has some convincing alternative explanations of Freud’s views on abuse as well as the development and possible repudiation of the seduction theory.*


## Roots of Psychiatry: The Reality of Childhood Trauma

*Posted on February 26, 2016*

The first thing that often comes to mind for a patient as well as for the therapist is whether memories of early childhood abuse are truth or fantasy. Often such memories are dismissed automatically as being untrue – even by the adult who had been abused as a child. I believe that the reason for this is that people don’t want to believe that horrific abuse of a child can or has happened – to themselves or to others. This societal issue played out in the earliest history of Psychiatry. It may be helpful to examine the background for the use of the term “fantasy”in psychiatry.

Human communication presupposes that people, in general, present themselves and are taken pretty much at face value. In ordinary conversation, one generally does not assume that what one hears is fantasy. The only time one considers something spoken to be fantasy is when it is explicitly stated to be so or when the content is simply beyond the belief of the listener. The crux of childhood trauma is connected most definitely to the latter.

The use of the word fantasy in psychiatry is tied to Freud’s “seduction theory”of hysteria. But it is important and instructive to note that at the beginning of his work, prior to propounding the seduction theory, he used various words interchangeably in an 1896 paper entitled “The Aetiology of Hysteria” to describe “infantile sexual scenes”: Vergewaltigung (rape), Missbrauch (abuse), Verführung (seduction), Angriff (attack), Attentat (a French term, meaning an assault), Aggression, and Traumen (traumas).” All these words explicitly characterize sexual violence directed against the child by an adult. The infantile sex scenes were not characterized as fantasy according to that original work.

Many of Freud’s patients were suffering from what was then termed “hysteria.” Those working with DID, as patient or therapist, will recognize that the common denominator in all kinds of hysteria discussed at that time in psychiatry is dissociation. Freud’s patients were often daughters of prominent men in society, or even of his colleagues. It may or may not have been beyond his imagination to believe that the sexual misconduct of his own upper class community was factual, although clearly in “The Aetiology of Hysteria” he did not doubt that the molestation memories his patients presented were truth. Nowhere in that paper does he raise the question of the memories being fantasy.

However, having formulated his theory of neurosis at the end of the 19th century in Vienna, he had to find an explanation for the sexual memories that was acceptable to his colleagues, the Viennese circle of eminent neurologists and neuropsychiatrists who dismissed his early work.

The result was the “seduction theory.” My understanding is that Freud used the word seduction to soften the tone describing sexual abuse. Using the word seduction implied a consent by the infant, that the infant consented to have sex in the context of seduction. Even that partial blaming of the infant was too close to accusing adults of abuse, so it was rejected by his peers. Freud ended up repudiating the seduction theory, characterizing the expressed memories of his patients as wishful thinking. In other words, there had been no actual sexual conduct. The fault was in the patient, having fantasized a sexual relationship with their father.

In this way, he made the expressing of memories of early sexual experiences with their fathers acceptable in the context of therapy because there was no actual accusation of molestation. In my opinion, the case histories described genuine examples of incest, rape and gross sexual abuse – not fantasy. The explanation given by the seduction theory was that such molestation never actually happened but rather came from patients’ wishful thinking. In this explanation, Freud chose to use the word seduction and fantasy instead of the explicitly violent terms “sexual assault” and “rape” that he used in 1896.

With Freud having characterized the memories as “fantasy,” the word became embedded in the roots of psychoanalytic thinking about early childhood sexual trauma that has dominated American psychiatry up to the 1950s and beyond. Here then, in the very earliest roots of psychiatry, is the repetition of society’s historical shifting of blame onto the victim and away from the perpetrator. It is a consequence of refusing to consider even the possibility that such evil conduct can be perpetrated on a child – particularly by well-to-do educated adults that are often at the head of the family or at the pinnacle of society. The critical impact of this repetition in psychiatry is that it gave a pseudo-scientific/pseudo-medical gloss to the denial and dismissal of molestation memories.

According to my clinical experience, incest and sexual abuse within a family is not uncommon but is often ignored and disbelieved. A 1988 Finnish study, carried out on 9000 15-year-old schoolgirls, had found the prevalence of incest to be .2% with biological fathers and 3.7% with step-fathers.1 Father-daughter incest is and was not as rare as many would like to believe, even today. In my experience, the rate of incest in certain communities is staggeringly high, such as in aboriginal communities suffering the aftermath of cultural genocide.

DID as the result of early childhood trauma is not uncommon and is almost completely ignored and disbelieved. I am confident that this kind of molestation is widespread. Being part of the upper strata of society, being of any particular religion or ethnic group does not impart any immunity to this. In short, I believe Freud’s insight at the very beginning was correct. It seems far more plausible that Freud’s patients were in fact victims of incest, sexual assault, and abuse.

Returning to the use of the word seduction, it is often misunderstood as not being part and parcel of violence. It infers that there is some form of participation by the child, or that there is a quality of love, as it is conventional understood, embedded in the seduction2. This is because seduction has a soft romantic connotation for most people. However, one must not forget that it has nefarious connotations in cases of fraud or of trapping people into sexual exploitation such as trafficking for example. There can be no “consent” by an infant or child to incest or other early childhood abuse – sexual or otherwise.

Let’s not continue any such misunderstanding. Considering the use of the term “seduction” when analyzing the relationship between an adult and an infant, toddler or other young child is wrong, dangerous and a critical warning that bad things are happening. Calling something seduction, when in the context of sexual contact with a child, whether it be an infant, toddler, or beyond is violent. While it does not necessarily physically injure the child, that is often the case. In all cases of which I am aware, it most definitely injures the child’s psychosocial development – at least through the first 5 stages as categorized by Erickson. Through seeing that injury in a child, one cannot avoid the conclusion that it was the result of violence.

Molestation in the guise of seduction is violence. Do not be deceived by it being dressed up in fancy clothes, fancy language, or accompanied by gifts. Seduction of a child is molestation. It is violence, full-stop.

I have gone into some detail because Freud’s seduction theory and characterization of expressed memories of sexual abuse as wishful thinking had been embraced for a century as a fundamental truth. It is only with the more recent findings of the severity, prevalence and universality of incest and sexual abuse that it is being questioned.

To me, the rate of occurrence of incest and abuse has been – and continues to be – grossly underestimated. Taking sexual abuse as a myth to be dismissed re-traumatizes all those who have been abused. Even as society now begins to acknowledge the violence against young children, in particular young girls, one continues to see the societal prejudice against acknowledging abuse and its effects on boys.

With respect to the statistics on DID, there is reported to be a 6:1 ratio of DID diagnoses for women as compared to men. It is my clinical experience that women tend more often toward direct self-harm and thus are shepherded into the mental health system while men are more likely to engage in physical altercations with the result that they are shepherded into the criminal justice system.

The tension over the question of declaring the memories to be fantasy or reality continues. It prevents many trauma patients from receiving proper diagnoses as well as proper treatment. In my psychiatric practice, after gaining a few decades of experience, it was clear that the body doesn’t lie3. Traumatic events may not be recalled with precision. Whether this is due to the age of the individual when abused or the intensity of the circumstances is irrelevant. The real tension should be understood as the difference between explicit and implicit memory. The body stores only implicit memory when conceptual faculties are not yet developed, or when they are overwhelmed at the time the trauma is inflicted.

Events that might have seemed phantasmagorical to Freud or to a currently practicing therapist may be explicit memory or it may simply be implicit memory being stored and subsequently expressed in archetypal forms. Simply because you cannot imagine the trauma does not mean that the trauma did not happen.

You know a large boat has passed in the ocean by its wake, you don’t need to know what country the boat came from, or how many people were on it, in order to know that it passed by. For treatment, the fact that trauma has occurred is the point to work with. As a therapist, you see the wake of the trauma, you don’t need to dig out the details. The details as expressed by the patient indicate the triggers and the impact of those triggers. They are not points for cross-examination by the therapist. I encourage therapists to avoid this as well as to redirect patients from cross-examining themselves in their internal dialogues.



