# Society and DID

## Reflections On Responding To Reports Of Abuse By Public Figures

*Posted on March 12, 2015*

Reports of famous personalities being accused of sexually abusing young girls decades ago, such as Jimmy Savile (deceased English TV celebrity, knighted by the Queen) or Bill Cosby, appear regularly in the news. People without experience dealing with sexual trauma always ask, ‚ÄúWhy did it take so long for the accusations to come to the public attention?‚Äù The question is asked in a way that is intended to challenge the credibility of the accusers. People with experience dealing with sexual trauma know that, invariably, abusers take advantage of their social position and power to make sure victims are intimidated, frightened, and therefore very reluctant to come forward to report the crime.

Often, when complaints are actually made, they are not taken seriously. They are blocked at the very beginning, by lower levels of administrators, celebrity handlers, and sometimes at the police level. The complaints almost never get to the right place even to be investigated. The abusers are usually not threatened with prosecution until decades have passed and, unfortunately, not until dozens of accusers come forward to break through the ‚Äúhe-is-famous, that-cannot-be-true‚Äù barrier.

Therapists may have the concern that they themselves will be sued by people in power who are accused of abuse. They may worry that they will be attacked on some kind of a claim that they were incompetently affirming a client‚Äôs delusion and, in that way, threaten the therapist. We must remember that we practice psychotherapy for the benefit of patients that have been traumatized. Often it is the therapist that is the first individual to undermine the belief instilled by abusers that no one will take their claims of abuse seriously. We cannot help them heal if we do not communicate our confident belief to our client.

If a client told me that she had been abused by someone revered by the public, like Bill Cosby or Jimmy Savile, a critical question will then follow, implicitly or explicitly, ‚ÄúDo you believe me?‚Äù

I would respond just as I would if they told me that someone not famous, perhaps their parent, had abused them. Experienced therapists usually have developed enough insight to determine whether the client is telling their truth or lying for some ulterior motive. If the client shows all the congruent body-language and demeanor of someone telling me of past trauma, I would have no difficulty recognizing that truth. Within that recognition, the truth I am concerned about is whether or not the patient has been traumatized. As I write in Engaging Multiple Personalities, the exact details are not important to the therapy. What is important is to recognize the truth of the trauma and proceed to support the patient in the healing process.

To show doubt about the traumatic memory, or to demand external checks on the accuracy of any memory, will likely be an experience of re-traumatization for the client. The key to understanding this is that abusers always impress upon their victims that no one will believe them, that they have no power to convince anyone that any abuse has taken place. This is why in the case of Sir Jimmy Savile, it took decades for these cases of child sexual abuse to come to the public awareness.

At the time of the crimes, victims were generally far too scared to tell anyone. Indeed, if they told someone, they were not believed. After all, Sir Jimmy was honored and knighted by Her Majesty the Queen. Her Majesty would never knight anyone who had done such an evil thing. How dare the victim suggest that! A similar logic is used against those accusing Bill Cosby of sexual abuse.

As a therapist, if your assessment is that the client has been traumatized, you need the courage to stand by your client, to support the truth of their painful history of abuse. If, in the unlikely situation the therapist is put on the stand in court, the therapist has every right to affirm and assert that:

1. Yes, I believe the patient was telling me the truth of her abuse experience.

2. No, I did not seek external corroborating proof as no such proof was necessary to proceed with psychotherapy. Investigations are the responsibility of the police. Following those investigations, it is up to the lawyers and judges to argue about whether or not the burden of proof for criminal law purposes has been met ‚Äì which is a very different standard than a therapist needs to determine whether or not a patient has been traumatized. My expertise allows me to determine that the patient has indeed been traumatized, and that is all I need to provide therapy. 

3. The attack by the defense lawyers will likely be based in the argument that the client‚Äôs identification of the abuser to the therapist is hearsay. But, hearsay evidence *is* permitted in court if you are stating it not for confirming the truth of the statement but rather for the purpose of confirming that the statement itself was made. Remain confident. You can clearly state that you are not accusing the public figure, your client is *and you have no reason to doubt her*. In truth, the only reason for doubting the accusers of Jimmy Savile was his public persona. Again, this is the same argument people use for doubting the accusers of Bill Cosby. Any therapist who has dealt with trauma knows that the public persona of abusers is often quite different than their private conduct. The Catholic church is dealing with the repercussions of this dichotomy and their failure to protect innocent children for many decades. 

4. All I need for doing therapy is the confidence that my client is telling me the truth of a past abuse experience, and I have no doubt, based on my training and experience, that she was abused. I am not interested in who abused her, except that in all abuse situations where there is a relationship between the abuser and the abused, the abuser is always someone in a position of power over the abused, that it was someone she could have trusted, and that individual took advantage of her. I do not need a lie-detector test or a police forensic report to confirm that abuse happened for providing therapeutic support to that client.


## The Focus in Documentaries

*Posted on September 19, 2016*

I have been asked to participate in a public television documentary on DID in Hong Kong. While I think a locally produced documentary is an excellent idea for public education in a city of 7 millions in Asia, where DID is considered nonexistent by the mental health care system, I have reservations about it. There are already many MPD documentaries (and movies) in the public media, whether it be on television, YouTube or otherwise.

The effect in the past has been that the public sees DID as a curiosity, a circus show. So far, all the movies about DID continue to create the false impression that it is a rare condition. The movies and most documentaries portray it as a very curious and, for those not afflicted by it, entertaining illness. Marketing clips, for example, show an adult professional woman suddenly turning into a 4 year old girl so that the viewer will think, ‚Äúhow extraordinary ‚Äì I must watch this!‚Äù

The result is that the public is impressed for the wrong reason. The DID community will never overcome the prejudicial idea that DID is very rare. The media focus is on the display of alters rather than the root cause of horrific early childhood abuse. That is where the (sometimes) bright light of documentary journalism needs to focus.

DID only appears to be rare. It is a hidden phenomenon, based on very private and confidential personal histories. It is not like a skin rash that someone on the outside immediately sees. Individuals with DID often include hosts that do not know their alters exist, or hosts that consider this kind of splitting as something private. They don‚Äôt even want their doctors to know for fear of ridicule, disbelief or being insulted.

I personally know of psychiatrists who simply ‚Äúdon‚Äôt believe‚Äù in DID, as if it were an issue of faith. For those psychiatrists, the sudden appearance of an alter as a 4 year old girl sitting on the floor in their consultation room is suppressed. It is met with ‚ÄúGo back to your chair and behave like an adult. You are not four, you are thirty-four.‚Äù But, DID is not an issue of faith. It is a diagnostic category that has been included for decades in multiple editions of the DSM.

There are several psychiatrists in apparent authority who promulgate their mistaken view. For example, there is a well-known authority, a university professor holding a chair in psychiatry, who proclaims that although he has been in his authoritative position for decades, he has never come across a genuine case of DID. Most laymen, and psychiatrists as well, do not challenge his view. They do not challenge that apparently authoritative statement. It can be scary to confront a so-called authority who has the power to belittle you, to attack you. No wonder society cannot get rid of the idea that DID is a very rare condition.

Most psychiatrists in Hong Kong have never seen even one case of DID. I would argue that the psychiatrists have almost definitely seen DID individuals because, statistically speaking, research shows it to be as common as schizophrenia ‚Äì which virtually all would acknowledge having seen. What is the argument one can use with them to help them understand that it isn‚Äôt that they haven‚Äôt seen DID, that they have simply failed to *recognize* DID?  It is to point out that statistics don‚Äôt lie.

Busy psychiatrists looking for symptoms to pigeonhole a patient into a particular diagnostic box of depression, bipolar disorder or perhaps borderline personality disorder, will see how they can fit the patient into their familiar basket of diagnoses. In other words, their index of suspicion ‚Äì which excludes DID ‚Äì will lead them to what they are most comfortable identifying and treating. As a result, DID will not be recognized and therefore not get diagnosed. When that happens, the patient will likely decide that it would be no use to let such a psychiatrist know of the true nature of their affliction. The consequence is that there is once again no feedback and once again a psychiatrist fails to recognize the disorder.

There isn‚Äôt much to be gained in showing an adult speaking as a child on the screen. It becomes another cycle of entertainment, rather than an expos√© of an extremely serious public health and social issue; the issue of early childhood trauma. This is the point to stress. It is critical that the public be educated about the widespread nature of such trauma along with its tremendous and wide-spread ramifications to the individuals traumatized and to society in general.

I understand that movies and television shows seek to show something impressive to grab viewers. Unfortunately, what they think is impressive (and more palatable to viewers) is the display of alters rather than the heart of the issue, which is abuse.

I have not yet confirmed my willingness to participate in the documentary as I am still pondering these points.


## Disclosing Your DID: A Cautionary Note

*Posted on October 16, 2015*

*I am delighted and honored that Robert Oxnam, author of A Fractured Mind: My Life with Multiple Personality Disorder (Hyperion, 2005) has most kindly consented to be a guest blogger on this topic of disclosing one‚Äôs DID to others. I am confident that his generosity in writing this piece will result in much benefit to the DID community. His ongoing willingness to share his experience with others is a tribute to the power of genuinely walking the path of healing.*

‚ÄúDisclosing Your DID: A Cautionary Note‚Äù
From: Robert Oxnam
October 16, 2015

I‚Äôve been asked by my good friend, David Yeung, to offer some advice about the wisdom and dangers of disclosing your DID condition to others beyond your family and a trusted circle of close friends. Having published my DID story a decade ago, he knew I had lots of experience with the ups and downs of openly revealing the disorder.

Looking back, I think my disclosure motivations were similar to many who have struggled privately with DID over many years. I wanted to be honest about who ‚Äúwe‚Äù are inside and how we‚Äôve coped with a difficult life. I wanted to embrace my outer associates ‚Äì family, friends, workmates ‚Äì just as I had learned to embrace my inner identities. As one publisher said to me ‚Äì ‚ÄúI think you‚Äôre writing this book so you can own the rest of your life.‚Äù

And so, I blithely pushed ahead, wrote the book, and awaited the results, good or bad. In retrospect, I was very fortunate to have a relatively favorable outcome ‚Äì roughly 80% of the responses were positive/very positive while 20% very negative/outright vicious. Many in the media world embraced the book and, for a few weeks at least, it became a bestseller. I was deluged with supportive emails and letters, especially from mental health professionals and from fellow DIDs. But nasty anti-DID shrinks unloaded on me and some reviews were laced with haughty and mocking language. Some former friends and even family backed away; while others implied that I was making up the whole story. Just go to Amazon.com, check the reviews of A Fractured Mind, and you‚Äôll see the whole spectrum.

In retrospect, I‚Äôve learned a great deal about the volatility that surrounds our disorder, and ‚Äúwe‚Äù have learned how to find inner strength to cope with the harsher realities of DID disclosure. Most of all, I have come to realize that my 80/20 breakdown was an outright miracle and it could have been much worse. I have also concluded that my relatively-positive experience with DID disclosure has been an exception that proves the rule. What rule? Don‚Äôt go public unless you‚Äôve thought it out carefully and are ready to face difficult consequences, short and long term. Remember, you‚Äôll live with ever-expanding circles of ‚Äúpeople who know and gossip‚Äù for the rest of your life.

Why was my experience an ‚Äúexception that proves the rule‚Äù? I think there were four factors that prompted an 80/20 response rather than 50/50 or perhaps even 20/80.

1. ‚ÄúInner Consensus.‚Äù In 2005, when the book was published, ‚Äúwe‚Äù already had fifteen years of post-diagnosis DID under our collective belt. We had fully identified the whole raft of inner personalities, found ways to break down the walls that separated us, and gone through a long-term merging process. The remaining five identities committed ourselves to a cooperative framework called ‚Äúcohesive multiplicity.‚Äù And then, ‚Äúwe‚Äù openly discussed the pros and cons of going public. Eventually, we reached a heartfelt decision that, for our own sakes, and for the potential good of others, it was essential to write the book. And, we also agreed that each of us would tell his/her story separately so that none of us felt left out or diminished by the experience. In short, we were all ready for the reactions, come hell or high water.

22. ‚ÄúControlling the Narrative.‚Äù The book itself was ‚Äúour story‚Äù in our own words. Before anyone might react to that story, they would presumably have read the book and thus encountered experiences and observations that we ourselves had revealed in context. So we were not just disclosing our DID, but also offering an orderly and positive framework for helping others understand DID. These are the messages in a nutshell: a) DID occurs because of vicious abuse inflicted on very young children, b) DID is an intelligent child‚Äôs way of coping with horrible treatment and staying alive in physical and psychological terms, c) There are great therapists who can treat DID with patience and care, producing remarkable results, and d) In addition, those without DID can learn from the disorder about how multiplicity is embedded in all humankind. And maybe, we hoped, non-DIDs could learn how to deal creatively with those inner forces and perhaps even find their own way to ‚Äúcohesive multiplicity.‚Äù

3. ‚ÄúTiming.‚Äù When the book was published, I was 62 years old, at the end of a multi-faceted and successful career as a specialist in China and Asia. I was already pursuing other activities as a novelist, business consultant, and television journalist. I didn‚Äôt know it at the time, but I was also poised to enter the creative world as an artist working in sculpture and photography. Yes, I suppose one might say that my career trajectory was as diverse as my inner psychology. But my key point is that the timing was right to take a disclosure leap without fearing that I would lose my job and livelihood in the process.

4. ‚ÄúHighly Supportive and Admired Partner.‚Äù Vishakha Desai, my wife, has been and remains a crucial factor in dealing with my DID and coping with ‚Äúgoing public.‚Äù It is impossible to imagine the arduous process of DID therapy and then public disclosure without her at my side. Vishakha has not only helped me in a thousand ways, but she has also become a fervent advocate for DIDs and dissociation therapists. She makes the powerful point that ‚ÄúDID denial‚Äù is really ‚Äúthe second abuse‚Äù ‚Äì first the child is brutally abused and suffers severe dissociation, and then, many in the public and not a few shrinks deny that DID even exists. The fact that Vishakha is now a major figure in global education, culture, and business means that her insightful views are deeply respected. Many now see her as a role model for ‚ÄúDID partners.‚Äù

So my message is this . . . The desire for disclosing your DID is totally understandable, and even noble, but the potential dangers are substantial. You need to think out the strategies and consequences in great detail, producing a DID version of what the business community calls ‚Äúrisk analysis‚Äù, and what professional athletes call a ‚Äúgame plan.‚Äù Without such forethought, it‚Äôs particularly difficult to engage in a ‚Äúpartial disclosure‚Äù: letting a few more people know, trusting they will keep it private, but this risks a rippling effect if someone breaks your confidence. On the other hand, if you, along with your therapist and current circle of supporters, can create a plan that works for your inner DID system, and for your social and professional situation, then it‚Äôs worth considering disclosure.

When thinking about these issues, DIDs and our therapists are fortunate to have a wide array of communication routes, both online and at in-person conferences. One remarkable example is the annual ‚ÄúHealing Together‚Äù gathering expertly hosted by an organization with an appropriately-upbeat title ‚Äì ‚ÄúAn Infinite Mind.‚Äù I have had the honor of keynoting those conferences several times in recent years and will do so again in February, 2016 in Orlando, Florida. The Healing Together conference offers a wonderful chance to meet with hundreds of other DIDs and therapists, allowing attendees to be who they are without apology or having to hide. The conference offers a rich array of speakers ‚Äì including several who are coping with dissociation themselves ‚Äì and ample opportunity to raise whatever questions and viewpoints in a totally confidential environment. Above all, the chance to talk with other DIDs is enormously important, sharing our experiences and escaping the burden of feeling trapped and helpless. It is always helpful when getting ready to walk through a minefield to get advice from those who have already traversed it and can point out the dangers.

I pray for the day when DID is universally seen as a treatable disorder, not caused by something you did, not posing threats to others, and deserving sympathy rather than suspicion. Then we can all reveal our disorder without fretting about unintended consequences.


## The Failure to Acknowledge ‚Äì Comparing Abuse in the Military and Childhood Trauma

*Posted on September 2, 2015*

In my books, Engaging Multiple Personalities Volume 1 and 2, I briefly discuss the fact that PTSD was not really acknowledged until the military was overwhelmed with veterans suffering from it. I pointed out some of the similarities between veterans with PTSD and DID patients whose trauma arose from very early childhood abuse. The key similarities are the inescapability of the danger and the resultant hyper-vigilance. The key difference in PTSD resulting from the battlefield is that a soldier has the support of other soldiers who understand the wartime environment whereas a child being abused is all alone, with no buddies, no peer group to support them or get them help.

[There is now a report from the General Accountability Office of the US Federal government](http://www.huffingtonpost.com/rep-niki-tsongas/support-male-survivors-of-sexual-assault_b_7832846.html) on the ‚Äústaggering number of men in the military that have been sexually assaulted, and hinted at the underlying problem, writing: ‚ÄòDOD has recognized that a cultural change is needed to address sexual assaults but has not yet taken several key steps to further this change.‚Äô For all victims, male and female, the environment frequently acts as a deterrent rather than a support structure; but for men the effect appears to be more significant.‚Äù

It is a societal bias that the issue gets attention when it impacts men but not so much when it impacts women. This is simply wrong ‚Äì terribly wrong. It has been known, and not particularly seen as a ‚Äústaggering‚Äù problem, that women have been similarly victimized. However, the fact that sexual assault in the military is now being scrutinized may have a positive impact on men outside the military ‚Äì particularly those abused as children ‚Äì who have been sexually attacked. Hopefully the changes that the military makes to protect its men will similarly protect its women. From my experience treating both men and women who have been sexually abused, I think it is quite possible that the finding that ‚Äúfor men the effect appears to be more significant‚Äù will be seen as wrong ‚Äì terribly wrong.

The information described in the article ties into my experience treating DID patients, where they were raised in an environment that was a deterrent to reporting and healing, where the risk of retaliation is stupendous, and where the assaulted individual has no safe option to confront their attacker(s). It is instructive that the language within the military report context talks about betrayal: ‚ÄúRetaliation compounds the injustice and personal betrayal survivors experience and has been a lasting concern among survivors, advocates and those of us in Congress fighting to institute reform.‚Äù Betrayal trauma is almost always a key component in child sexual abuse.

The SAPRO report acknowledges the high levels of retaliation, and in May a report conducted by Human Rights Watch drew similar conclusions. Human Rights Watch made the problem vividly clear by sharing candid stories from service members who experienced backlash firsthand.

It is interesting to note that many comments were made about this report questioning who was doing the assaulting. A specific concern was raised that, once again, those doing the assaulting were not being identified, called out or punished for their crimes. All of this is quite familiar to anyone with experience treating the trauma of early childhood abuse.

It is my hope that just as the military‚Äôs concerns about veterans ended up mainstreaming the understanding of PTSD, this report and any follow-up work will clarify for the therapeutic community that betrayal trauma has a lasting deep impact and must be understood and addressed. This is true whether that betrayal affects an adult in the military or a child living in a domestic war zone.

I see it as an optimistic sign that finally there is an opening that may force psychiatry to face the issue of trauma and possible dissociation directly. It is something we can no longer ignore or keep silent with the prescription of a pill.


## Trigger Warning: News of Abuse by Men in Power Part 1

*Posted on November 18, 2017*

The year 2017 is becoming an eye opener for many people about the pervasiveness of sexual abuse. It is now, finally, being widely and publicly acknowledged that 1) sexual abuse is common; 2) sexual abuse is often covered up and under-reported; 3) abusers often hide under a veneer of respectability, and 4) the power dynamic at the center of abuse enables abusers to continue to abuse and suppresses victims from speaking out ‚Äì often for decades.

The recent cascade of reports from abuse survivors accusing men in power of taking advantage of women and children (of both genders) does not shock me, nor does the fact that the events in question often have been hidden far longer than most people can imagine. These dynamics are well known to survivors of early childhood abuse and to members of the DID community. As a psychiatrist who worked for many years on the impact on survivors of early childhood trauma, I feel compelled to comment in support of survivors speaking out. No matter how long ago the abuse happened, and no matter who the abuser was, these testimonies are critical for healing those attacked. They are critical for protecting others from harm right now as well as into the future.

Many of the same arguments used against these survivors of celebrity abuse have been made against early childhood abuse survivors with DID. Despite their lack of celebrity involvement, my clients‚Äô histories of abuse are quite similar to those now being made public. Unfortunately, very few people pay attention when the attackers are non-celebrities who might be parents, siblings, doctors, clergy and others in the community, just as very few people pay attention when the victims are not celebrities. As Jane Fonda pointed out, people are paying attention now because the victims are celebrity white women now coming forward.

The loudest and most common ways survivors are attacked are by assertions that because the abuse happened so long ago, the report is unreliable; because it is a case of he said/she said, the report is unreliable; and because the abuser is a well-regarded person in the community, the report is unreliable or even fraudulent. These statements are the marks of actual ignorance, self-serving intentional ignorance, and/or participatory enabling.

I cannot speak for everyone, but I can certainly speak as to the survivors that were my clients, dealing as adults with their early life unprocessed trauma. Here it is: I have zero doubt about the fact that my clients had been abused. Zero doubt. 


## Trigger Warning: News of Abuse by Men in Power Part 2

*Posted on November 18, 2017*

People ask why it took so long for these celebrities to speak out, just as they ask of individuals abused as children ‚Äì with and without DID. Because the current reports involve adults for the most part, people are now beginning to accept that there is an impact of power dynamics. Where abuse happens in a setting involving a high differential of power between the abuser and the abused, the victim is usually completely intimidated. Whether it is a celebrity predator, an Olympic team doctor, a local clergyman, or a family member, these attacks often happened in one of two ways: 1) so unexpectedly that one is usually taken off-guard, rattled and confused, in which case the first thing that arises in conscious thought is: ‚ÄúWho would believe me?‚Äù or 2) following a period of grooming, a step-by-step dismantling of personal boundaries a little at a time, that appears to shift the abuse to some twisted and illusory appearance of consent. And, again, the conscious thought is: ‚ÄúWho would believe me?‚Äù

Imagine being a very small child, the level of intimidation is life and death. The power differential with respect to adults, particularly adult family members, is incomprehensible.

In most cases, as survivors fear and sometimes learn, the accusations are readily brushed off for an extraordinarily long time. Survivors, DID and otherwise, often find out long after the fact that they were not the only target. Why? Because abusers rarely limit their abuse to a single target. It is part and parcel of the power dynamic that enables ongoing secrecy.

As we see in the current news reports, survivors are told how important and prominent the abuser is. They are told how the survivor‚Äôs life would be destroyed if they speak out. In family abuse, the child is warned that the entire family will be destroyed. Further, reporting abuse usually requires going to or through someone whose responsibility is to screen the information and then to convey it to someone higher up. At any point in the chain, the report can be suppressed, dismissed or ignored. Protection is crafted for the abuser, not the survivor. The survivor‚Äôs life, as they once knew it, is undermined and often destroyed.

How does it work? A scenario like this may help to illustrate it: An abusive man in charge of the local orphanage has dinner with the police chief of the city. The next day, the police receive a complaint about sexual abuse in the orphanage. It would be tempting for the chief to deem the report a lie ‚Äì after all, he just had such a nice dinner together with the purported abuser and nothing seemed amiss. If he thinks there might be even a smidgeon of possibility, it would be much easier to minimize the offence as a simple case of confusion that can simply be brushed off. Isn‚Äôt it more important to protect the reputation of the purported abuser and the institution from such terrible claims? No, it is not.

You can substitute anyone in a position of power for the orphanage director in the above example. You can substitute anyone for the police chief in that example ‚Äì anyone in the money chain connected with the abuser. And remember, abusers are used to hiding their tracks. Even good people often miss the clues that their old friend, a pillar of the community, has an incredibly hidden dark side.

Evil deeds must be called out as quickly as possible ‚Äì even if ‚Äúas quickly as possible‚Äù means decades later! Why? Because any time an evil deed is covered up, it will fester and grow, like a deep infection that periodically erupts to the surface. Old or new, whenever you identify an infection is the time to treat it.

It is quite understandable that the victim, having been caught by surprise, remains silent. The longer they remain silent, the harder it is to speak up. The more they see those who speak up be dismissed as crazy or as liars, the harder it is for them to summon the courage to speak out themselves. A perpetrator, however, takes that silence as encouragement. He is free to do it again because, after all, the victim(s) is (are) too cowed to speak up. The longer the silence, the less believable people will find their words when victims do speak out.

Perpetrators, notoriously, will re-offend. Like thieves, people almost never stop once they have gotten away the first time. The victim meanwhile has the unrealistic wish that this will not happen again to them. Why not listen to the warnings about speaking out, after all, this man is powerful‚Äîhe could throw you out of the school, or ruin any opportunities which you worked so hard for years to approach. Can you stand up to a world class famous coach in hockey, swimming, or gymnastic coach who has taken you under his wing? Especially when you are representing your country at the Olympics and becoming world famous? Could you stand up so easily to a father who has been abusing you from as far back as your memory can go?

We should be shouting to the heavens our support and appreciation for the many celebrities as well as the ordinary men and women who have summoned the courage to speak out. It is only in this way that our children, our friends and our society can be protected from this scourge.

It remains extraordinary that in this day and age, we seem to accept the mind-set of a man that can speak about how he can ‚Äúgrab a woman by her pussy‚Äù and people will still elect him as a leader. The message this has sent continues to reverberate. But, now, that reverberation has resulted in the gathering of strength, of the coming together of survivors who are gaining power by exposing the abuse. Exposure is the disinfectant to protect ourselves and our children. 


## Trigger Warning: Reports of abuse by men in power Part 3

*Posted on November 18, 2017*

What is happening now, people speaking out about having been abused, is incredibly important. For a single victim of abuse to think about speaking out is like thinking about going down a dark alley alone late at night. It is quite scary. From those initial victims speaking out despite the fearful consequences, speaking out is no longer going down a dark alley alone. Instead, it is going with dozens if not hundreds or thousands of friends, holding hands, protecting and cheering for each other. No longer so scary and not nearly so difficult.

Many men have been brainwashed to believe silence means consent, many women have been brainwashed to believe whatever they say or do will not make a difference in a male dominated authority structure. Don‚Äôt accept that brainwashing. Your body knows the truth of its experience. Trust that.

Look at the impact of a few brave women speaking out. #metoo, among other efforts, is forcing some of the abusers out in the light ‚Äì calling them to account for their heedless destruction of the lives of others. This call to account involving adult celebrities has led to starting to open the doors to acknowledge the evil impact that pedophilia have wrought on so many child stars, whose lives often fell apart completely under the pressure of their unresolved trauma.

It is spreading to the music and fashion industries as well as into politics and corporate executive offices. Let‚Äôs continue that push, extend it to all survivors of early childhood abuse. Sunlight is the best disinfectant; natural, bright, and healing.


## Why Ordinary People Deny Testimony of Abuse

*Posted on October 10, 2018*

Weeks of heated debate concerning the appointment of a US supreme court judge, has come to an end and a decision was made ‚Äì a decision by the Republican majority that was not swayed by the bravery of Dr. Blasey Ford. This hearing reminded people of a previous confirmation hearing in 1991, that also revolved around alleged sexual misconduct. The latest hearing went beyond simply bringing the issue of sexual harassment into the public eye. It went beyond that earlier hearing involving workplace sexual harassment, and forced the issue of sexual assault into the light of public scrutiny.

The #MeToo movement has been critical in raising public awareness on the issue of sexual assault. But there remains, in general, serious misunderstandings on the question, function and qualities of traumatic memory. Until the public is better educated about how trauma impacts memory, victims‚Äô statements will always be doubted and misunderstood. In that way, victims of sexual assault will be retraumatized.

This dynamic played out in these hearings where many Senators affirmatively ignored the depth of research into how sexual abuse events are remembered by victims. The logic used by deniers of Dr. Blasey Ford‚Äôs testimony relied on their so-called ‚Äúcommon sense.‚Äù Senators expressed their denial based on the questions people that have as anyone else might raise that has no genuine understanding of sexual trauma:

1. If something so terrible as sexual assault or rape did happen, why does she not even remember the time/place/persons involved, with some clarity? The subtext of that question is barely hidden: *If it was me, I would remember.*

2. If something so devastating did happen, why did she not make a formal complaint right afterwards? This also extends into the scenario pointing out, perhaps, that the victim repeatedly saw (or returned to) the abuser and acted as if nothing serious had happened. The subtext of that question is similarly barely hidden: *She kept seeing him to wait in ambush to make a complaint decades later.*

The public, and certainly elected officials, need to be better educated about the unique phenomenon of traumatic memory and behaviour. When judges, or other people in high position, fail to understand the nature of traumatic memory and phenomenon of victimization, all victims of sexual assault are subject to retraumatization. Unfortunately, one can simply refer to President Trump‚Äôs mocking of Dr. Ford ‚Äì attacking her memory of being sexually assaulted.

Once again, we must go back to distinguishing the different kinds of memory. We can easily access non-traumatic memory. This ordinary explicit memory, which is termed declarative memory, can be expressed in narrative form. An example of this is recalling what you had for lunch, when you had it and with whom you were eating; at around 1 pm, sitting at a corner of such and such eatery, hastily downing soup and a sandwich with my friend John. This is ordinary explicit, or declarative memory.

In contrast to explicit memory, there is implicit or non-declarative memory. This kind of memory is usually without verbal references. Generally speaking, it is vague, all jumbled up non-verbal memory. It often manifests in the body as somatic sensations and visual imageries.

It is in this kind of non-declarative memory that trauma is processed and stored. It is challenged and often disbelieved by people evaluating the memories of victims of abuse. Those who deny this kind of memory misjudge it. They make the mistake of comparing their own explicit memory to a victim‚Äôs implicit memory. In other words, as was seen in the analysis of people denying Dr. Ford‚Äôs testimony, their erroneous logic is, ‚ÄúIf I can clearly remember what I had for lunch with John yesterday, why can‚Äôt you remember clearly where, how and when XX attacked you?‚Äù They make that error in judgment because implicit memory related to trauma and explicit memory related to everyday experience is processed very differently in our brain.

When an experience is encoded in fragmented, non-declarative memory, only raw emotions and physical sensations are accessible in one‚Äôs consciousness. These may manifest in hyper-vigilance, sudden and overwhelming feelings of panic or dread. They usually include intense feelings of alienation, rage, and helplessness as well as terror at loss of control.

Instead of precisely expressive words, victims of assault (such as my patients when I was actively practicing psychiatry) may speak of ‚Äúwanting to throw up,‚Äù or an intensely ‚Äúyucky feeling.‚Äù Often they have intrusions of bizarre visual images. The inability to translate what is so strongly felt into something expressible in words leaves them frustrated, bewildered, angry, and hopeless. Their dilemma is perhaps best expressed by John Harvey (1990): ‚ÄúTrauma victims have symptoms instead of memories.‚Äù

Working with patients in therapy, a psychiatrist must translate this body of knowledge into appropriate therapeutic processes. While therapy is quite a different process than a hearing involving an assault victim‚Äôs statement of recollection, it does not excuse the misjudgment of those denying someone‚Äôs traumatic memories.

The second issue raised in such misjudgments is why a victim would remain in some kind of relationship with an abuser or fail to make a complaint within the ‚Äúright‚Äù time frame. Once again, one has to understand the dynamics of the victim/abuser relationship. Suffice to say that I have encountered a victim of incest who continued to allow the abuse to take place even after she reached the age of 30 and had gotten married.

Even for someone without experience in dealing with trauma, one should consider the following question: ‚ÄúIf I let someone abuse me and have complete power over me at age 3, how could I suddenly have the strength to rebel and stop the abuse at age 3 plus 1 day?‚Äù It is easy to answer that question. Of course one wouldn‚Äôt have that strength at 3 years plus 1 day. But if the power hierarchy is maintained for decades, when does one day finally become different from the previous day? If it happened at age 30, could I have the strength to stop it at age 30 plus 1 day?

When we make an informed judgment, we must make sure we understand the various dynamic factors. We should not jump to conclusions when we have insufficient information or, just as important, insufficient empathy. Empathy, the ability to put ourselves in the other person‚Äôs shoes and try to think and feel as they might, is the real key.

The leadership in society should be willing to be educated in matters related to post-traumatic stress disorder (PTSD) and Complex PTSD. Many women suffered and continue to suffer in the prevailing culture of male entitlement. This cultural view accommodates men taking what they want, treating women as sex objects, and treating women simply as objects over which they can assert power.

This entitlement culture is simply wrong, it opens the door to potential horrors. We only need to open our eyes to cultures that advocate female circumcision, cultures where gang rape is the norm rather than an isolated incident, and cultures where families sell their young girls (and boys) for sex slaves. The President openly admitted to what he called ‚Äúlocker room talk‚Äù, of how he could easily grope women‚Äôs genitals. We have a long way to go before we can arrive at a better world ‚Äì for our daughters, sisters and our mothers. Such a world would be far better for our sons, brothers and fathers as well. Dr. Ford‚Äôs bravery is a poignant marker on this journey. 


## Public Virtue and Private Abuse ‚Äì Part 1 of 2

*Posted on March 16, 2020*

In recent years we have encountered news reports of famous, well respected individuals being exposed as having a dark side in their lives; a very dark side of sexually abusing women or children. Famous philanthropists, spiritual leaders, musical conductors, and people of great wealth have been credibly accused, and now fortunately some of whom are being convicted, of utilizing their position to exploit people under their influence. The list does not exclude psychiatrists, therapists, or healers ‚Äì professional or otherwise.

We presume that those we revere conduct themselves in accord with high moral standards both in public and private. We then feel betrayed and at a loss to understand their (formerly) hidden heinous conduct that has now been exposed.

I am writing this as part of my personal response to the case of Jean Vanier. His life‚Äôs work inspired many people, including me, in their attitude and service towards the mentally challenged. But Vanier, always characterized during his life as a devout Catholic, had ‚Äúmanipulative and emotionally abusive‚Äù sexual relationships with six women in France, between 1970 and 2005. [This is according to a statement by L‚ÄôArche International](https://www.bbc.com/news/world-51596516 ), the organization he founded that did and does so much to benefit the mentally challenged.

While I truly hope the recent charges that surfaced after his death does not harm the work of the L‚ÄôArche International, I have no doubt that it will. Here was a man who for all intents and purposes was an extremely good person in public but whose dark side was kept hidden as he violated women in private.

It is important to remember that his conduct did not just harm the women he abused. He knew or should have known that it would be revealed at some point and, as a result, that it would definitely harm the work of L‚ÄôArche. He put his own self-interests ahead of his care for the marginalized group that was the foundation for the power/charisma that he then abused.

There is a painful and extreme cognitive dissonance for me. I followed his public career with joy as he helped a very marginalized community. But the characterization of Vanier as a ‚Äúdevout Catholic‚Äù doesn‚Äôt compute with the abuse charges confirmed by his own organization. I feel betrayed both by his public persona and by myself in my presumption that his public deeds were in keeping with what I *imagined* were his private morals.

In trying to make sense of this, I thought about when I watched Cowboy movies as a young child. The first thing I did was try to identify who were the good guys and who were the bad guys. Until I did that, I couldn‚Äôt settle in to watch the movie.

Just like me, most young children are told that people are clearly divided into good and bad. This is simply not true. In the real world, that presumption is not useful in navigating one‚Äôs way because people are almost never 100% good nor 100% bad. There is no clear line of demarcation separating them.

For a child, it is their parent(s) that are responsible for protecting them from the bad people and bad circumstances that one encounters in life until they are old enough to have learned how to navigate this world of moral grays for themselves. For a very young child, they cannot possibly navigate the world unaided. For a child being abused by someone who others presume are indeed protecting that child, the level of betrayal is incredibly more horrific ‚Äì as detailed in the work of Dr. Jennifer Freyd.

For such abused children, it is no surprise that abusers often appear to other adults as ordinary decent individuals while behind closed doors they are the exact opposite. A young child keys off of the attitude of other adults toward their abus˘˘˘˘˘er, and so are often unable to understand what is safe, what is normal, and what is simply evil. But children try to bond with their primary caregiver, no matter the conduct of that caregiver, because that bonding to the primary caregiver is a biological imperative.

This episode of Jean Vanier is a painful opportunity for me; a very small echo of the betrayal experienced by an abused child. It remains only a very small echo because Vanier was not responsible for me: I never met him. He did nothing to me personally but it is an echo of sorts because I do feel deeply betrayed. 
At the same time, it confirms the advice I gave my patients when I was practicing psychiatry 1) to never ignore the messages from internal system protectors; 2) to be very careful when engaging with anyone those protectors caution about; and 3) to completely avoid anyone those protectors are going full red alert about. [In particular, I recommend re-reading my posts on the issue of forgiveness](https://www.engagingmultiples.com/meaning-forgiveness-part-1/).

Virtually any human being is capable of great deeds of kindness as well as of evil deeds. The decision to do something virtuous or to do something immoral often happens in a split-second. This is obvious when considering the profound power of peer pressure when a situation presents itself, whether in the context of bullying at school, assisting the murder of countless people in concentration camps, or torturing an animal. It is not easy to resist the group momentum that seeks to carry you along with it. It is also obvious when considering the profound power and opportunity one may have in private over people in thrall to you.

The exertion of one‚Äôs own internal moral authority to overcome such group or internal pressure is difficult, whether one is Gandhi, Martin Luther King, or anyone else willing to lay down his life in the service of protecting the most vulnerable in society. It is extraordinarily difficult for those of us who have not the spiritual strength and discipline to contest such overwhelming pressure and opportunity. Vanier clearly failed to stand up to the seduction of his power in private.

It is human nature that we can do either moral and immoral acts at any moment in our lives. It is not incompatible that one person can do both in their lives. Because our minds are not always stable, each opportunity brings that same choice to us. The important point is that we can also make the decision, again and again, to commit virtuous acts.

We humans are social creatures. That enables us to accommodate unacceptable behavior which to others or even to ourselves later on, is called rationalization. When we are tempted to commit a transgression of either society‚Äôs or our own morals, we all can readily make up a reason to allow us to do so. A famous American public figure once said that he did ‚Äúit‚Äù, an immoral act, simply because it could be done.

I am not making excuses for anyone to commit immoral acts. Rather, I want to discourage cynicism and encourage hope. But it is important to acknowledge that our so-called power of reasoning is often weak and easily influenced by our own as well as other's strong emotions.

Many of us, in a moment of impulsivity, step on the gas just to experience the sensation of going way over the speed limit. We think that we are unlikely to be caught, that no one will ever know, that it is not really going to hurt anyone, and so on.

With sexual transgressions, the rationalization is usually that ‚Äúthis is a special relationship, one that is high and above the usual mundane worldly liaison.‚Äù People can delude themselves that this relationship is special and sublime, that no one is hurt, that it is intensely satisfactory to both parties concerned and that the other person will be ok with it because it is intensely satisfying to me. The bigger picture, including the risks and potential/likely terrible consequences is ignored.

Once this borderline of deluded rationalization is crossed, the second incident begins the habit of thinking that this can be done without a problem. Even the questioning of why or why not becomes weaker. Sexual offenders almost never do it just once. Having experienced violating someone without penalty, with the second and third time the conduct becomes a habit ‚Äì the beginning of.an entrenched pattern.

In most cases involving sexual transgression, the act is almost always predicated on a power differential between the parties. The perpetrator is usually of a higher social status and in a position of power. In the intimacy of therapy or spiritual counseling, it is easy to fall victim to the higher social status of the therapist, counselor or religious figure because they are bestowed in those dynamics with the seemingly magical power of a superior being, just as it is in child sexual abuse.

The perpetrator is always aware of this power differential. It feeds into his ego. In any moment, one can lose sight of and fall under the sway of pride, of greed. One gravitates toward the satisfaction of being admired and the possibility of sexual gratification. One can delude oneself with the rationalization that this time it is the rare experience of true love, a genuine meeting of souls. One ignores the fact that the rationalization is a delusion.

It is hard to be a saint in any public sphere. It is hard to resist the temptation of seeking confirmation of one's power and/or gratification of one‚Äôs sexual desire in a private sphere. It is difficult to resist the temptation of a great sensual (sexual) experience in a life full of stresses and loneliness.

Most people are not able to let go of the cravings of the ego for sensual experiences. Take for instance, a friend of mine who has such strong craving for good food, that he would go to one restaurant for its soup, to another for its orange duck main course, and to a third for its dessert of Tiramisu. No kidding!

Giving in to this kind of craving, played out by choosing this or that item in different particular restaurants is completely different from giving in to a craving that leads to abuse. Moving between restaurants does not involve the traumatization of anyone, so there is no harm. This is a qualitatively different gratification of desire. But other gratification actions may result in severe traumatization of another individual. That is what defines for me what is acceptable and what is not.

My conclusion is that good people are capable of immoral acts just as bad people are capable of kind acts. We should well remember that according to the great book that serves as the foundation of the 3 principal monotheistic religions of Islam, Judaism and Christianity, God‚Äôs chosen heroes were all imperfect specimens. Abraham, was despicable in that he offered his wife Sarah to the Pharaoh to save his own skin. King David coveted Bathsheba so much that he would send her husband to be killed in battle so that he could have her. Lot offered his daughters to be raped before they escaped from Sodom

It is unrealistic to separate people into all good and all bad. In short, we should hesitate to give anyone a blanket ‚Äúcertificate of righteousness.‚Äù Human beings are potentially good and potentially bad. Let us first examine each of our own opportunities, as they arise, to be virtuous and kind then act appropriately.


## Coping With Anxiety in the Pandemic
		
*Posted on March 25, 2020*

Since SARS visited Hong Kong in 2003, the world has had warning visits of Ebola, Swine Flu, Avian Flu and MERS-CoV.  Now, the pandemic of COVID-19 is upon us. We have been watching it grow rapidly in China and aboard the Diamond Princess cruise ship. It has spread rapidly in Italy, Spain, South Korea, and is now severely threatening the US, Canada, and many other countries.  Political leaders around the globe have reacted with varying degrees of alertness. We have witnessed country dependent degrees of control over its spread and growth.

As individuals, how do we handle the fear and anxiety we face with this viral threat? The question of dealing with fear and anxiety is one that is always present for those with DID. But now, we need to understand that just as individual trauma is processed individually, it can also happen in a society or, as now, sometimes on a global scale.

In general, fear has a protective function. Within the context of DID, fear about survival triggers the dissociative experience in a young child. Epidemiologists are characterizing this virus as a survival issue for many people, economists are characterizing it as a survival issue for commerce.

It is fear that is motivating us as a society to adopt drastic measures such as school and factory closures, the cancellation of public gatherings, cruise ship trips, unnecessary vacation flights, and even restaurant dining. These measures will curb the growth and spread of the viral infection. This is an example of vigilance heightened appropriate to the threat.

What is left is handling panic or the excessive fear. This is not unfamiliar to those accustomed to working with trauma and PTSD.  One point that is emphasized in the Engaging Multiple Personality series is the need to slowly transform hair-trigger hyper-vigilance into ordinary protective vigilance. I always point out that we must maintain vigilance, not eliminate it. Why? Because there are dangers in the world and we need to remain alert.

However, the opposite of hyper-vigilance is also on display in this pandemic. There are countries where leader(s) have ignored science and discouraged vigilance (hyper or otherwise) against all apparent facts. We see news reports of some young people in particular that are affirmatively ignoring and denying the social distancing recommendations. They put themselves at risk because they do not believe it is a danger for them that outweighs their need to some immediate gratification ‚Äì like Spring Break.

So let‚Äôs stay appropriately vigilant. In that light, I would like to focus on the following points as a guideline in facing this Corona virus Crisis.

1. Be informed of what you fear.  For most people, COVID-19 infection presents from an asymptomatic state to mild symptoms similar to a cold or flu.  Some complain of a dry cough, abdominal discomfort, and breathing difficulty.   Only a small percentage of those infected may need special care in a hospital setting; for intubation, oxygen in ‚Äúequipped beds‚Äù and so forth.

2. You have a responsibility of protecting others if you are sick. If you suspect you have COVID-19, don‚Äôt go to your doctor and potentially infect everyone in the waiting room. Instead, call the hospital for help and let them know you may have the viral infection. Note that several sitting US Senators self-isolated immediately upon suspicion of the virus while one who is actually a doctor was tested because of his high personal risk exposure. He continued to interact with colleagues for days without telling them he was a potential asymptomatic carrier. He was indeed infected. Again, an example of an inappropriate lack of vigilance putting a wide circle of people at risk.

3. Frequent hand washing is most important as well as avoiding touching door knobs and door handles with your uncovered hand.  Wear disposable gloves or have a tissue/napkin to cover your hand when touching one of those surfaces. Wear face masks if you feel any symptom and avoid touching your own face as a general rule. In person, keep social distancing. Better yet, maintain physical isolation if possible but make sure to connect socially through the phone and/or internet so as to avoid emotional isolation.

4. Having put 1-3 into practice, pay attention to the psychological aspect of coping with the stress. Do grounding exercises throughout the day. Preferably start the exercises before you panic so that when anxiety erupts you are already habituated to grounding yourself. It is a good practice to do them when you get up in the morning, perhaps once mid-day, and before going to sleep at night.

The following is my very personal view of the pandemic, so please take it with as many grains of salt as you think appropriate . . .

In the 14th Century, the plague killed one third of the population of Europe.  Despite subsequent medical advances, the plague has recurred many times since then. The last time that I am aware of was in October 2017 when it hit Madagascar and killed 170 people. Ebola had been hitting certain African states regularly. In modern times, we have had repeated corona virus infections of different varieties that we have hardly any means of control.

These epidemics regularly hit different parts of the world. We generally don‚Äôt hear about them because we (and our local media) tend to ignore them when they do not impact us directly. We usually have other bad news to worry about, such as fighting in Afghanistan, Iraq, Syria, Yemen and elsewhere.

I do not blame God or any extra-natural sources. It doesn‚Äôt seem helpful to me. As humans, we must learn to survive in an increasingly complicated world. This has been the story of humanity throughout our history. A key to what is helpful is learning to appreciate that we are all interdependent. We have a long way to go to reach a world of peace and accord. Perhaps we can use this as an opportunity to move further toward that goal.

Life comes with needing to accept the fact there are periods of adversity and to work with them. For some experiences of adversity, we can learn to face them with insight, compassion for ourselves and others, and eventually with some equanimity. Indeed, it is time for us to rethink our place in the world and the universe. This is an opportunity for each of us, certainly for me, to question why are we here, what is our purpose today.

It goes back to the question I faced when beginning my retirement, what is the reason for me to get up in the morning? The answer began to dawn when going through my patient files as part of closing up my psychiatric practice. It seemed that my DID patients had gone through such profound trauma and taught me so much. It was difficult to be retired, unable to help any more. I began to try to organize my thoughts, which resulted in the Engaging Multiple Personality Series and blog posts.

I believe these writings have been helpful to many people, at least as indicated by emails and Facebook comments I have received from those with DID and their spouses/partners as well as sometimes psychiatrists and other therapists. In this way, the DID community has helped me process the vicarious trauma I experienced listening and trying to assist my patients. It continues to heal my heart.

I offer a quotation from Rabindranath Tagore which I have found inspiring:

> ‚ÄúI slept and dreamt that life was joy. I awoke and saw that life was service. I acted and behold, service was joy.‚Äù

In my retirement, and in this COVID-19 crisis, I am seeking to make contact with some people I know who might benefit from a warm phone call, one that might penetrate their loneliness and isolation. I read books that I have always wanted to read but never before had time. I listen to music that nourishes me. I try to keep my body active and supple, to prevent waking up with pain all over my stiff body. I also do my one-breath-meditation and walking meditation. This is the least I can do to be kind to myself. I also write my blog articles when the circumstances and spirit moves me.

With best wishes for your healing and strength.
