# Afterword {-}

After reviewing the many blog posts I have written since publishing Volume 1 of Engaging Multiple Personalities in 2014, it dawns on me that the message I want to send, refined through my experience working with DID patients, is really about psychological trauma in general. Working with both DID patients and others has led me to believe that all trauma has can cause dissociation.

Dissociation is a much wider spread phenomenon than most realize. Only in its most advanced and crystallized form, dissociative identity disorder, has caught our attention but in the wrong way. Its dramatic appearance distracts our attention away from the true significance of the trauma. In reality, dissociation is present in almost every case. We need to be aware of its prevalence as a human response to trauma rather than seeing it as manifesting only in dissociative identity disorder.

Dissociation is a very effective defensive smokescreen to obscure the real picture in all cases of trauma related psycho-pathology. Given the bias against diagnosing dissociative disorders, it also affects therapists by causing blind spots and inviting a general lack of empathy for those with DID.

The current DSM classification is one way to view psycho-pathology. It helps to triage a patient when we are in a hurry. Another important and complementary approach is looking at progression of ego break-down in the face of accumulating and aggravating traumas. In this way, one goes beyond any rigid and somewhat arbitrary separation of what we see as neurosis versus psychosis, and the application of descriptive classification of personality disorders.

We clinicians are only human, and as such have our individual limitations of empathy. I have repeatedly observed the dangerous old school and simplistic way in defining psychosis when a patient’s utterance is not understood by the clinician. I have always thought it a manifestation of arrogance, that “if I don’t understand you, then you must be psychotic.” A case in point is the classification of “Psychotic Depression.”

Depression may be illogical or irrational from the clinician’s point of view. But, to the patient, depression may be the only rational response to the situation in which they are trapped.

Psychological trauma is such an obvious cause for an individual to become entangled within a psychiatric disorder. Yet, it is a field we generally find difficult to grasp. Much work has yet to be done to understand and help individuals in this situation. Those with DID are often denigrated or shunned by society both in its ignorance and by its unwillingness to confront the widespread evil of early childhood abuse. At the same time, PTSD afflicted war veterans, a group of people that society tends to revere, have some similar symptomology to those with DID such as flashbacks, dissociation, and panic attacks.

The military’s acknowledgment of PTSD opened the minds of therapists and many in society to the fact and power of the dissociative response to war-time trauma. Some therapist see the continuum of dissociation related to trauma in general, which benefits those with DID seeking help. It is my hope that the work in guiding patients and therapists dealing with DID, such as grounding exercises, guidance for spouses and other recommendations made in several of these blog posts, can be applied to benefit all those with dissociative issues, whether they be DID, war-time PTSD, or other disorders rooted in trauma.